import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AcademicResource, AcademicResourceFilters, AcademicResourceType, getAcademicResourceErrorMessage, getResources, isUnauthorizedAcademicResourceError } from "../../services/academic-resource.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: { value: AcademicResourceType; label: string }[] = [{ value: "lecture_notes", label: "Lecture Notes" }, { value: "slides", label: "Slides" }, { value: "lab_manual", label: "Lab Manual" }, { value: "previous_questions", label: "Previous Questions" }, { value: "research_material", label: "Research Material" }, { value: "other", label: "Other" }];
const typeLabels: Record<AcademicResourceType, string> = Object.fromEntries(types.map((type) => [type.value, type.label])) as Record<AcademicResourceType, string>;
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";

export default function AcademicResourcesScreen() {
  const navigation = useNavigation<any>();
  const [resources, setResources] = useState<AcademicResource[]>([]); const [search, setSearch] = useState(""); const [subject, setSubject] = useState(""); const [resourceType, setResourceType] = useState<AcademicResourceType | undefined>(); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!isApplicantRole(session?.user.role)) { setError("Academic Resources are available to students and graduates only."); return; } const filters: AcademicResourceFilters = { search: search.trim() || undefined, subject: subject.trim() || undefined, resource_type: resourceType }; setResources(await getResources(filters)); setError(""); } catch (caughtError) { setError(getAcademicResourceErrorMessage(caughtError)); if (isUnauthorizedAcademicResourceError(caughtError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [resetForUnauthorized, resourceType, search, subject]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;

  return <ScrollView style={ui.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} colors={[colors.primary]} />}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity>
    <Text style={styles.title}>Resources</Text><Text style={styles.subtitle}>Browse academic and career resources shared across CampusX.</Text>
    <View style={styles.searchPanel}><Text style={styles.searchLabel}>FIND A RESOURCE</Text><View style={styles.searchField}><Text style={styles.searchIcon}>⌕</Text><TextInput style={styles.searchInput} placeholder="Search title, description, or subject" placeholderTextColor={colors.textMuted} value={search} onChangeText={setSearch} onSubmitEditing={() => void load()} /></View><TextInput style={[ui.input, styles.subjectInput]} placeholder="Filter by subject" placeholderTextColor={colors.textMuted} value={subject} onChangeText={setSubject} onSubmitEditing={() => void load()} /><Text style={styles.typeLabel}>RESOURCE TYPE</Text><View style={styles.typeList}>{types.map((type) => <TouchableOpacity key={type.value} style={[styles.typeButton, resourceType === type.value && styles.selectedType]} onPress={() => setResourceType(resourceType === type.value ? undefined : type.value)}><Text style={resourceType === type.value ? styles.selectedText : styles.typeText}>{type.label}</Text></TouchableOpacity>)}</View><TouchableOpacity style={ui.primaryButton} onPress={() => void load()}><Text style={ui.primaryButtonText}>Apply Filters</Text></TouchableOpacity></View>
    {error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}
    {!error && resources.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No resources found</Text><Text style={styles.emptyText}>Try another search, add a subject, or check back when faculty publish new resources.</Text></View> : null}
    {resources.map((resource) => <TouchableOpacity key={resource.id} style={styles.card} onPress={() => navigation.navigate("AcademicResourceDetails", { resourceId: resource.id })}><View style={styles.cardHeader}><Text style={styles.cardTitle}>{resource.title}</Text><View style={styles.typeBadge}><Text style={styles.type}>{typeLabels[resource.resource_type]}</Text></View></View><Text style={styles.subject}>{resource.subject || "No subject"}</Text>{resource.description ? <Text style={styles.description} numberOfLines={2}>{resource.description}</Text> : null}<View style={styles.cardFooter}><Text style={styles.creator}>{resource.creator_name ? `Shared by ${resource.creator_name}` : "CampusX resource"}</Text>{resource.resource_url ? <Text style={styles.resourceAction}>Open resource</Text> : <Text style={styles.resourceAction}>View details</Text>}</View></TouchableOpacity>)}
  </ScrollView>;
}

const styles = StyleSheet.create({
  center: { ...ui.centered }, content: { padding: spacing.xl, paddingBottom: 48 }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.lg }, title: { ...typography.screenTitle }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl },
  searchPanel: { ...ui.card, marginBottom: spacing.lg }, searchLabel: { color: colors.secondary, fontSize: 11, fontWeight: "800", letterSpacing: 1, marginBottom: spacing.sm }, searchField: { flexDirection: "row", alignItems: "center", backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md }, searchIcon: { color: colors.primary, fontSize: 23, marginRight: spacing.sm }, searchInput: { ...typography.input, flex: 1, paddingVertical: 14 }, subjectInput: { ...typography.input, marginTop: spacing.md }, typeLabel: { color: colors.textMuted, fontSize: 12, fontWeight: "700", marginTop: spacing.lg, marginBottom: spacing.sm }, typeList: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.lg }, typeButton: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: colors.backgroundElevated }, selectedType: { backgroundColor: colors.primary, borderColor: colors.primary }, typeText: { color: colors.textMuted, fontSize: 12, fontWeight: "700" }, selectedText: { color: colors.onPrimary, fontSize: 12, fontWeight: "800" },
  card: { ...ui.card, marginTop: spacing.md }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, cardTitle: { ...typography.cardTitle, flex: 1 }, typeBadge: { ...ui.badge, backgroundColor: colors.backgroundElevated, borderWidth: 1, borderColor: colors.secondary }, type: { color: colors.secondary, fontSize: 11, fontWeight: "800" }, subject: { color: colors.primary, fontSize: 13, fontWeight: "700", marginTop: spacing.sm }, description: { ...typography.caption, marginTop: spacing.sm }, cardFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider, paddingTop: spacing.md, marginTop: spacing.md }, creator: { ...typography.caption, flex: 1 }, resourceAction: { color: colors.primary, fontSize: 13, fontWeight: "800" },
  empty: { ...ui.emptyState, ...ui.card, marginTop: spacing.lg }, emptyTitle: { ...typography.cardTitle, marginBottom: spacing.xs }, emptyText: { ...typography.caption, textAlign: "center" }, errorBox: { ...ui.errorState, ...ui.card, marginTop: spacing.lg }, error: { color: colors.error, textAlign: "center", marginBottom: spacing.sm }, retry: { color: colors.primary, fontWeight: "800" },
});
