import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { AcademicResource, getAcademicResourceErrorMessage, getResourceById, isUnauthorizedAcademicResourceError } from "../../services/academic-resource.service";

const typeLabels: Record<AcademicResource["resource_type"], string> = { lecture_notes: "Lecture Notes", slides: "Slides", lab_manual: "Lab Manual", previous_questions: "Previous Questions", research_material: "Research Material", other: "Other" };
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";

export default function AcademicResourceDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const resourceId = Number(route.params?.resourceId); const [resource, setResource] = useState<AcademicResource | null>(null); const [loading, setLoading] = useState(true); const [opening, setOpening] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(resourceId) || resourceId < 1) { setError("The resource could not be found."); setLoading(false); return; } try { setLoading(true); const session = await getStoredAuthSession(); if (!isApplicantRole(session?.user.role)) { setError("Academic Resources are available to students and graduates only."); return; } setResource(await getResourceById(resourceId)); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); } }, [resetForUnauthorized, resourceId]);
  useEffect(() => { void load(); }, [load]);
  const openResource = async () => { if (!resource?.resource_url) return; try { setOpening(true); const supported = await Linking.canOpenURL(resource.resource_url); if (!supported) { setError("This external resource cannot be opened on this device."); return; } await Linking.openURL(resource.resource_url); } catch { setError("Unable to open the external resource. Please try again."); } finally { setOpening(false); } };
  if (loading && !resource) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  if (!resource) return <View style={styles.center}><Text style={styles.error}>{error || "Resource not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>ACADEMIC RESOURCE</Text><Text style={styles.title}>{resource.title}</Text><View style={styles.badgeRow}><Text style={styles.type}>{typeLabels[resource.resource_type]}</Text><Text style={styles.status}>Published</Text></View></View><Info label="Subject" value={resource.subject || "Not provided"} /><Info label="Description" value={resource.description || "Not provided"} />{resource.creator_name ? <Info label="Shared by" value={resource.creator_name} /> : null}{resource.resource_url ? <><Info label="External resource" value={resource.resource_url} /><TouchableOpacity style={[styles.openButton, opening && styles.disabled]} onPress={() => void openResource()} disabled={opening}><Text style={styles.openText}>{opening ? "Opening…" : "Open Resource"}</Text></TouchableOpacity></> : null}{error ? <Text style={styles.error}>{error}</Text> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { const isReadingContent = label === "Description"; return <View style={[styles.info, isReadingContent && styles.readingCard]}><Text style={styles.label}>{label}</Text><Text style={[styles.value, isReadingContent && styles.readingValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{...ui.card,marginBottom:spacing.md,paddingVertical:spacing.xl,borderColor:colors.primary},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:28,lineHeight:35},badgeRow:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.lg},type:{color:colors.primary,fontWeight:"700",backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},status:{color:colors.success,fontWeight:"700",backgroundColor:colors.surfaceRaised,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},info:{...ui.card,marginTop:spacing.md},readingCard:{backgroundColor:colors.backgroundElevated,paddingVertical:spacing.xl},label:{color:colors.text,fontSize:14,fontWeight:"800",letterSpacing:.2},value:{...typography.body,color:colors.textMuted,marginTop:spacing.sm},readingValue:{lineHeight:25,color:colors.text},openButton:{...ui.primaryButton,marginTop:spacing.xl},openText:ui.primaryButtonText,disabled:ui.disabled,error:{color:colors.error,textAlign:"center",lineHeight:21,marginTop:spacing.lg},retry:{...ui.textButton,marginTop:spacing.sm} });
