import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AcademicResource, getAcademicResourceErrorMessage, getResourceById, isUnauthorizedAcademicResourceError } from "../../services/academic-resource.service";

const typeLabels: Record<AcademicResource["resource_type"], string> = { lecture_notes: "Lecture Notes", slides: "Slides", lab_manual: "Lab Manual", previous_questions: "Previous Questions", research_material: "Research Material", other: "Other" };
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";

export default function AcademicResourceDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const resourceId = Number(route.params?.resourceId); const [resource, setResource] = useState<AcademicResource | null>(null); const [loading, setLoading] = useState(true); const [opening, setOpening] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(resourceId) || resourceId < 1) { setError("The resource could not be found."); setLoading(false); return; } try { setLoading(true); const session = await getStoredAuthSession(); if (!isApplicantRole(session?.user.role)) { setError("Academic Resources are available to students and graduates only."); return; } setResource(await getResourceById(resourceId)); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); } }, [resetForUnauthorized, resourceId]);
  useEffect(() => { void load(); }, [load]);
  const openResource = async () => { if (!resource?.resource_url) return; try { setOpening(true); const supported = await Linking.canOpenURL(resource.resource_url); if (!supported) { setError("This external resource cannot be opened on this device."); return; } await Linking.openURL(resource.resource_url); } catch { setError("Unable to open the external resource. Please try again."); } finally { setOpening(false); } };
  if (loading && !resource) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  if (!resource) return <View style={styles.center}><Text style={styles.error}>{error || "Resource not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity><Text style={styles.title}>{resource.title}</Text><Text style={styles.type}>{typeLabels[resource.resource_type]}</Text><Text style={styles.status}>Published</Text><Info label="Subject" value={resource.subject || "Not provided"} /><Info label="Description" value={resource.description || "Not provided"} />{resource.creator_name ? <Info label="Shared by" value={resource.creator_name} /> : null}{resource.resource_url ? <><Info label="External resource" value={resource.resource_url} /><TouchableOpacity style={[styles.openButton, opening && styles.disabled]} onPress={() => void openResource()} disabled={opening}><Text style={styles.openText}>{opening ? "Opening…" : "Open Resource"}</Text></TouchableOpacity></> : null}{error ? <Text style={styles.error}>{error}</Text> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:28,fontWeight:"bold",color:"#1E3A8A"},type:{color:"#2563EB",fontWeight:"600",marginTop:7},status:{color:"#047857",fontWeight:"700",marginTop:6},info:{marginTop:20},label:{color:"#333",fontWeight:"700"},value:{color:"#4B5563",lineHeight:22,marginTop:5},openButton:{backgroundColor:"#10B981",borderRadius:10,padding:14,alignItems:"center",marginTop:26},openText:{color:"#fff",fontWeight:"700"},disabled:{opacity:.65},error:{color:"#DC2626",textAlign:"center",lineHeight:21,marginTop:18},retry:{color:"#2563EB",fontWeight:"700",marginTop:10} });
