import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AcademicResource, AcademicResourceFilters, AcademicResourceType, getAcademicResourceErrorMessage, getResources, isUnauthorizedAcademicResourceError } from "../../services/academic-resource.service";

const types: { value: AcademicResourceType; label: string }[] = [{ value: "lecture_notes", label: "Lecture Notes" }, { value: "slides", label: "Slides" }, { value: "lab_manual", label: "Lab Manual" }, { value: "previous_questions", label: "Previous Questions" }, { value: "research_material", label: "Research Material" }, { value: "other", label: "Other" }];
const typeLabels: Record<AcademicResourceType, string> = Object.fromEntries(types.map((type) => [type.value, type.label])) as Record<AcademicResourceType, string>;
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";

export default function AcademicResourcesScreen() {
  const navigation = useNavigation<any>(); const [resources, setResources] = useState<AcademicResource[]>([]); const [search, setSearch] = useState(""); const [subject, setSubject] = useState(""); const [resourceType, setResourceType] = useState<AcademicResourceType | undefined>(); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!isApplicantRole(session?.user.role)) { setError("Academic Resources are available to students and graduates only."); return; } const filters: AcademicResourceFilters = { search: search.trim() || undefined, subject: subject.trim() || undefined, resource_type: resourceType }; setResources(await getResources(filters)); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [resetForUnauthorized, resourceType, search, subject]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity><Text style={styles.title}>Academic Resources</Text><Text style={styles.subtitle}>Browse published course materials and external resources.</Text>
    <TextInput style={styles.input} placeholder="Search title, description, or subject" value={search} onChangeText={setSearch} onSubmitEditing={() => void load()} /><TextInput style={styles.input} placeholder="Filter by subject" value={subject} onChangeText={setSubject} onSubmitEditing={() => void load()} />
    <View style={styles.typeList}>{types.map((type) => <TouchableOpacity key={type.value} style={[styles.typeButton, resourceType === type.value && styles.selectedType]} onPress={() => setResourceType(resourceType === type.value ? undefined : type.value)}><Text style={resourceType === type.value ? styles.selectedText : styles.typeText}>{type.label}</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.filterButton} onPress={() => void load()}><Text style={styles.filterText}>Apply Filters</Text></TouchableOpacity>
    {error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity></View> : null}
    {!error && resources.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No resources found</Text><Text style={styles.emptyText}>Try another search, add a subject, or check back when faculty publish new resources.</Text></View> : null}
    {resources.map((resource) => <TouchableOpacity key={resource.id} style={styles.card} onPress={() => navigation.navigate("AcademicResourceDetails", { resourceId: resource.id })}><Text style={styles.cardTitle}>{resource.title}</Text><Text style={styles.type}>{typeLabels[resource.resource_type]}</Text><Text style={styles.detail}>{resource.subject || "No subject"}</Text>{resource.description ? <Text style={styles.description} numberOfLines={2}>{resource.description}</Text> : null}{resource.creator_name ? <Text style={styles.creator}>Shared by {resource.creator_name}</Text> : null}{resource.resource_url ? <Text style={styles.url}>External resource available</Text> : null}</TouchableOpacity>)}
  </ScrollView>;
}
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A"},subtitle:{color:"#666",fontSize:16,lineHeight:22,marginTop:6,marginBottom:18},input:{borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:12,marginBottom:10,fontSize:16},typeList:{flexDirection:"row",flexWrap:"wrap",gap:7,marginBottom:12},typeButton:{borderWidth:1,borderColor:"#2563EB",borderRadius:8,padding:8},selectedType:{backgroundColor:"#2563EB"},typeText:{color:"#2563EB",fontSize:12},selectedText:{color:"#fff",fontSize:12},filterButton:{backgroundColor:"#10B981",padding:13,borderRadius:10,alignItems:"center",marginBottom:14},filterText:{color:"#fff",fontWeight:"700"},errorBox:{alignItems:"center",marginVertical:16},error:{color:"#DC2626",textAlign:"center",marginBottom:10},empty:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:18,marginTop:8},emptyTitle:{color:"#333",fontSize:18,fontWeight:"700",marginBottom:6},emptyText:{color:"#666",lineHeight:22},card:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:16,marginTop:12},cardTitle:{fontSize:18,fontWeight:"700",color:"#333"},type:{color:"#2563EB",fontWeight:"600",marginTop:5},detail:{color:"#4B5563",marginTop:6},description:{color:"#4B5563",marginTop:8,lineHeight:21},creator:{color:"#4B5563",marginTop:9},url:{color:"#2563EB",fontWeight:"600",marginTop:8} });
