import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { Announcement, AnnouncementFilters, AnnouncementType, getAnnouncementErrorMessage, getAnnouncements, isUnauthorizedAnnouncementError } from "../../services/announcement.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: { value?: AnnouncementType; label: string }[] = [{ label: "All" }, { value: "academic", label: "Academic" }, { value: "assignment", label: "Assignment" }, { value: "general", label: "General" }];
const typeLabel = (value: Announcement["announcement_type"]) => value === "academic" ? "Academic" : value === "assignment" ? "Assignment" : "General";
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";

export default function AnnouncementsScreen() {
  const navigation = useNavigation<any>();
  const [items, setItems] = useState<Announcement[]>([]); const [search, setSearch] = useState(""); const [selectedType, setSelectedType] = useState<AnnouncementType | undefined>(); const [activeFilters, setActiveFilters] = useState<AnnouncementFilters>({}); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false, filters = activeFilters) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Announcements are available to students and graduates only."); return; } setItems(await getAnnouncements(filters)); setError(""); } catch (caughtError) { setError(getAnnouncementErrorMessage(caughtError)); if (isUnauthorizedAnnouncementError(caughtError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [activeFilters, resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const applyFilters = () => { setActiveFilters({ search: search.trim() || undefined, announcement_type: selectedType }); };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;

  return <ScrollView style={ui.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} colors={[colors.primary]} />}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity>
    <Text style={styles.title}>Announcements</Text><Text style={styles.subtitle}>Important university and faculty updates, in one place.</Text>
    <View style={styles.searchPanel}><Text style={styles.searchLabel}>FIND AN UPDATE</Text><View style={styles.searchField}><Text style={styles.searchIcon}>⌕</Text><TextInput style={styles.searchInput} value={search} onChangeText={setSearch} placeholder="Search title or content" placeholderTextColor={colors.textMuted} returnKeyType="search" onSubmitEditing={applyFilters} /></View><View style={styles.choices}>{types.map((item) => <TouchableOpacity key={item.label} style={[styles.choice, selectedType === item.value && styles.selected]} onPress={() => setSelectedType(item.value)}><Text style={selectedType === item.value ? styles.selectedText : styles.choiceText}>{item.label}</Text></TouchableOpacity>)}</View><TouchableOpacity style={ui.primaryButton} onPress={applyFilters}><Text style={ui.primaryButtonText}>Apply Filters</Text></TouchableOpacity></View>
    {error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}
    {!error && items.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No announcements found</Text><Text style={styles.emptyText}>There are no published announcements matching your filters.</Text></View> : null}
    {items.map((item) => <TouchableOpacity key={item.id} style={styles.card} onPress={() => navigation.navigate("AnnouncementDetails", { announcementId: item.id })}><View style={styles.cardHeader}><Text style={styles.cardTitle}>{item.title}</Text><View style={styles.typeBadge}><Text style={styles.type}>{typeLabel(item.announcement_type)}</Text></View></View><Text style={styles.preview} numberOfLines={2}>{item.content}</Text><View style={styles.cardFooter}><Text style={styles.creator}>{item.creator_name ? `Posted by ${item.creator_name}` : "CampusX update"}</Text><Text style={styles.date}>Published {item.published_at ? item.published_at.slice(0, 10) : "recently"}</Text></View></TouchableOpacity>)}
  </ScrollView>;
}

const styles = StyleSheet.create({
  center: { ...ui.centered }, content: { padding: spacing.xl, paddingBottom: 48 }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.lg }, title: { ...typography.screenTitle }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl },
  searchPanel: { ...ui.card, marginBottom: spacing.lg }, searchLabel: { color: colors.secondary, fontSize: 11, fontWeight: "800", letterSpacing: 1, marginBottom: spacing.sm }, searchField: { flexDirection: "row", alignItems: "center", backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md }, searchIcon: { color: colors.primary, fontSize: 23, marginRight: spacing.sm }, searchInput: { ...typography.input, flex: 1, paddingVertical: 14 }, choices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginVertical: spacing.lg }, choice: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: colors.backgroundElevated }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.textMuted, fontSize: 12, fontWeight: "700" }, selectedText: { color: colors.onPrimary, fontSize: 12, fontWeight: "800" },
  card: { ...ui.card, marginTop: spacing.md }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, cardTitle: { ...typography.cardTitle, flex: 1 }, typeBadge: { ...ui.badge, backgroundColor: colors.backgroundElevated, borderWidth: 1, borderColor: colors.secondary }, type: { color: colors.secondary, fontSize: 11, fontWeight: "800" }, preview: { ...typography.caption, marginTop: spacing.md }, cardFooter: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider, paddingTop: spacing.md, marginTop: spacing.md }, creator: { ...typography.caption, flex: 1 }, date: { color: colors.info, fontSize: 12, fontWeight: "700", textAlign: "right" },
  empty: { ...ui.emptyState, ...ui.card, marginTop: spacing.lg }, emptyTitle: { ...typography.cardTitle, marginBottom: spacing.xs }, emptyText: { ...typography.caption, textAlign: "center" }, errorBox: { ...ui.errorState, ...ui.card, marginTop: spacing.lg }, error: { color: colors.error, textAlign: "center", lineHeight: 21 }, retry: { color: colors.primary, fontWeight: "800", marginTop: spacing.sm },
});
