import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { Announcement, AnnouncementFilters, AnnouncementType, getAnnouncementErrorMessage, getAnnouncements, isUnauthorizedAnnouncementError } from "../../services/announcement.service";

const types: { value?: AnnouncementType; label: string }[] = [{ label: "All" }, { value: "academic", label: "Academic" }, { value: "assignment", label: "Assignment" }, { value: "general", label: "General" }];
const typeLabel = (value: Announcement["announcement_type"]) => value === "academic" ? "Academic" : value === "assignment" ? "Assignment" : "General";
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";

export default function AnnouncementsScreen() {
  const navigation = useNavigation<any>(); const [items, setItems] = useState<Announcement[]>([]); const [search, setSearch] = useState(""); const [selectedType, setSelectedType] = useState<AnnouncementType | undefined>(); const [activeFilters, setActiveFilters] = useState<AnnouncementFilters>({}); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false, filters = activeFilters) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Announcements are available to students and graduates only."); return; } setItems(await getAnnouncements(filters)); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [activeFilters, resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const applyFilters = () => { setActiveFilters({ search: search.trim() || undefined, announcement_type: selectedType }); };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity><Text style={styles.title}>Announcements</Text><Text style={styles.subtitle}>Published campus updates for you.</Text><TextInput style={styles.input} value={search} onChangeText={setSearch} placeholder="Search title or content" returnKeyType="search" onSubmitEditing={applyFilters} /><View style={styles.choices}>{types.map((item) => <TouchableOpacity key={item.label} style={[styles.choice, selectedType === item.value && styles.selected]} onPress={() => setSelectedType(item.value)}><Text style={selectedType === item.value ? styles.selectedText : styles.choiceText}>{item.label}</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.apply} onPress={applyFilters}><Text style={styles.applyText}>Apply Filters</Text></TouchableOpacity>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}{!error && items.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No announcements found</Text><Text style={styles.emptyText}>There are no published announcements matching your filters.</Text></View> : null}{items.map((item) => <TouchableOpacity key={item.id} style={styles.card} onPress={() => navigation.navigate("AnnouncementDetails", { announcementId: item.id })}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.type}>{typeLabel(item.announcement_type)}</Text><Text style={styles.preview} numberOfLines={2}>{item.content}</Text>{item.creator_name ? <Text style={styles.creator}>Posted by {item.creator_name}</Text> : null}<Text style={styles.date}>Published {item.published_at ? item.published_at.slice(0, 10) : "recently"}</Text></TouchableOpacity>)}</ScrollView>;
}
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A"},subtitle:{color:"#666",fontSize:16,lineHeight:22,marginTop:6,marginBottom:18},input:{borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:12,fontSize:16,color:"#333",marginBottom:12},choices:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:12},choice:{borderWidth:1,borderColor:"#2563EB",borderRadius:8,padding:9},selected:{backgroundColor:"#2563EB"},choiceText:{color:"#2563EB",fontSize:13},selectedText:{color:"#fff",fontSize:13},apply:{backgroundColor:"#10B981",borderRadius:10,padding:13,alignItems:"center",marginBottom:10},applyText:{color:"#fff",fontWeight:"700"},errorBox:{alignItems:"center",marginVertical:16},error:{color:"#DC2626",textAlign:"center",lineHeight:21},retry:{color:"#2563EB",fontWeight:"700",marginTop:10},empty:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:18,marginTop:8},emptyTitle:{color:"#333",fontSize:18,fontWeight:"700",marginBottom:6},emptyText:{color:"#666",lineHeight:22},card:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:16,marginTop:12},cardTitle:{fontSize:18,fontWeight:"700",color:"#333"},type:{color:"#2563EB",fontWeight:"600",marginTop:5},preview:{color:"#4B5563",marginTop:8,lineHeight:21},creator:{color:"#6B7280",marginTop:8,fontSize:13},date:{color:"#047857",fontWeight:"600",marginTop:7,fontSize:13} });
