import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { Announcement, deleteAnnouncement, getAnnouncement, getAnnouncementErrorMessage, isUnauthorizedAnnouncementError, updateAnnouncement } from "../../services/announcement.service";

type Props = { managementRole: "faculty" | "admin"; listRoute: string; editRoute: string };
const typeLabel = (value: Announcement["announcement_type"]) => value === "academic" ? "Academic" : value === "assignment" ? "Assignment" : "General";
const audienceLabel = (value: Announcement["audience"]) => value === "all" ? "All users" : `${value.charAt(0).toUpperCase()}${value.slice(1)} users`;

export default function AnnouncementDetailsScreen({ managementRole, listRoute, editRoute }: Props) {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const announcementId = Number(route.params?.announcementId);
  const [item, setItem] = useState<Announcement | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(announcementId) || announcementId < 1) { setError("The announcement could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || session.user.role !== managementRole) { if (!session) await resetForUnauthorized(); else setError("You are not allowed to manage announcements."); return; } setItem(await getAnnouncement(announcementId)); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [announcementId, managementRole, resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const changeStatus = async (status: "published" | "archived") => { try { setWorking(true); setError(""); await updateAnnouncement(announcementId, { status }); await load(); Toast.show({ type: "success", text1: status === "published" ? "Announcement published" : "Announcement archived" }); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  const remove = async () => { try { setWorking(true); setError(""); await deleteAnnouncement(announcementId); Toast.show({ type: "success", text1: "Announcement deleted" }); navigation.navigate(listRoute); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Announcement not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate(listRoute)}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}><TouchableOpacity onPress={() => navigation.navigate(listRoute)} disabled={working}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity><Text style={styles.title}>{item.title}</Text><Text style={styles.type}>{typeLabel(item.announcement_type)}</Text><Text style={styles.status}>{item.status}</Text><Info label="Audience" value={audienceLabel(item.audience)} /><Info label="Content" value={item.content} /><Info label="Published" value={item.published_at ? item.published_at.slice(0, 10) : "Not published"} />{item.creator_name ? <Info label="Created by" value={item.creator_name} /> : null}{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()} disabled={working}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}<TouchableOpacity style={[styles.edit, working && styles.disabled]} disabled={working} onPress={() => navigation.navigate(editRoute, { announcementId })}><Text style={styles.editText}>Edit Announcement</Text></TouchableOpacity>{item.status === "draft" ? <TouchableOpacity style={[styles.publish, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Publish announcement?", "The selected audience will be able to view it.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void changeStatus("published") }])}><Text style={styles.publishText}>{working ? "Saving…" : "Publish"}</Text></TouchableOpacity> : null}{item.status !== "archived" ? <TouchableOpacity style={[styles.archive, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Archive announcement?", "It will no longer be visible to its audience.", [{ text: "Cancel", style: "cancel" }, { text: "Archive", style: "destructive", onPress: () => void changeStatus("archived") }])}><Text style={styles.archiveText}>Archive</Text></TouchableOpacity> : null}<TouchableOpacity style={[styles.remove, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Delete announcement?", `Delete “${item.title}”? This cannot be undone.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void remove() }])}><Text style={styles.removeText}>Delete Announcement</Text></TouchableOpacity></ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24,backgroundColor:"#fff"},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:28,fontWeight:"bold",color:"#1E3A8A"},type:{color:"#2563EB",fontWeight:"600",marginTop:7},status:{color:"#047857",fontWeight:"700",textTransform:"capitalize",marginTop:6},info:{marginTop:20},label:{color:"#333",fontWeight:"700"},value:{color:"#4B5563",lineHeight:22,marginTop:5},edit:{borderWidth:1,borderColor:"#2563EB",borderRadius:10,padding:14,alignItems:"center",marginTop:28},editText:{color:"#2563EB",fontWeight:"700"},publish:{backgroundColor:"#10B981",borderRadius:10,padding:14,alignItems:"center",marginTop:12},publishText:{color:"#fff",fontWeight:"700"},archive:{borderWidth:1,borderColor:"#D97706",borderRadius:10,padding:14,alignItems:"center",marginTop:12},archiveText:{color:"#D97706",fontWeight:"700"},remove:{borderWidth:1,borderColor:"#DC2626",borderRadius:10,padding:14,alignItems:"center",marginTop:12},removeText:{color:"#DC2626",fontWeight:"700"},disabled:{opacity:.6},errorBox:{alignItems:"center",marginTop:18},error:{color:"#DC2626",textAlign:"center",lineHeight:21},retry:{color:"#2563EB",fontWeight:"700",marginTop:10} });
