import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AnnouncementAudience, AnnouncementStatus, AnnouncementType, createAnnouncement, getAnnouncement, getAnnouncementErrorMessage, isUnauthorizedAnnouncementError, updateAnnouncement } from "../../services/announcement.service";

type Props = { mode: "create" | "edit"; managementRole: "faculty" | "admin" };
const types: { value: AnnouncementType; label: string }[] = [{ value: "academic", label: "Academic" }, { value: "assignment", label: "Assignment" }, { value: "general", label: "General" }];
const audiences: { value: AnnouncementAudience; label: string }[] = [{ value: "student", label: "Student" }, { value: "graduate", label: "Graduate" }, { value: "faculty", label: "Faculty" }, { value: "recruiter", label: "Recruiter" }, { value: "all", label: "All" }];
const statuses: AnnouncementStatus[] = ["draft", "published", "archived"];

export default function AnnouncementFormScreen({ mode, managementRole }: Props) {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const announcementId = Number(route.params?.announcementId); const isEdit = mode === "edit";
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [type, setType] = useState<AnnouncementType>("academic"); const [audience, setAudience] = useState<AnnouncementAudience>("student"); const [status, setStatus] = useState<AnnouncementStatus>("draft"); const [loading, setLoading] = useState(isEdit); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!isEdit) return; if (!Number.isInteger(announcementId) || announcementId < 1) { setError("The announcement could not be found."); setLoading(false); return; } try { setLoading(true); const item = await getAnnouncement(announcementId); setTitle(item.title); setContent(item.content); setType(item.announcement_type); setAudience(item.audience); setStatus(item.status); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); } }, [announcementId, isEdit, resetForUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const normalizedTitle = title.trim(), normalizedContent = content.trim(); if (!normalizedTitle) return setError("Announcement title is required."); if (normalizedTitle.length > 200) return setError("Announcement title must be 200 characters or fewer."); if (!normalizedContent) return setError("Announcement content is required."); if (normalizedContent.length > 5000) return setError("Announcement content must be 5000 characters or fewer."); try { setSaving(true); setError(""); const session = await getStoredAuthSession(); if (!session || session.user.role !== managementRole) { if (!session) await resetForUnauthorized(); else setError("You are not allowed to manage announcements."); return; } const data = { title: normalizedTitle, content: normalizedContent, announcement_type: type, audience, ...(managementRole === "admin" || isEdit ? { status } : {}) }; if (isEdit) await updateAnnouncement(announcementId, data); else await createAnnouncement(data); Toast.show({ type: "success", text1: isEdit ? "Announcement updated" : "Announcement created", text2: !isEdit && status === "draft" ? "Saved as a draft." : undefined }); navigation.goBack(); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setSaving(false); } };
  const availableAudiences = managementRole === "faculty" ? audiences.slice(0, 2) : audiences;
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>Cancel</Text></TouchableOpacity><Text style={styles.title}>{isEdit ? "Edit Announcement" : "Create Announcement"}</Text>{!isEdit && managementRole === "faculty" ? <Text style={styles.subtitle}>Your announcement will start as a draft.</Text> : null}<Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Content" value={content} onChangeText={setContent} editable={!saving} multiline /><Text style={styles.label}>Type</Text><View style={styles.choices}>{types.map((item) => <Choice key={item.value} label={item.label} selected={type === item.value} onPress={() => setType(item.value)} disabled={saving} />)}</View><Text style={styles.label}>Audience</Text><View style={styles.choices}>{availableAudiences.map((item) => <Choice key={item.value} label={item.label} selected={audience === item.value} onPress={() => setAudience(item.value)} disabled={saving} />)}</View>{(managementRole === "admin" || isEdit) ? <><Text style={styles.label}>Status</Text><View style={styles.choices}>{statuses.map((item) => <Choice key={item} label={item} selected={status === item} onPress={() => setStatus(item)} disabled={saving} />)}</View></> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>{isEdit ? "Save Changes" : "Create Draft"}</Text>}</TouchableOpacity></ScrollView>;
}
function Choice({ label, selected, onPress, disabled }: { label: string; selected: boolean; onPress: () => void; disabled: boolean }) { return <TouchableOpacity style={[styles.choice, selected && styles.selected]} onPress={onPress} disabled={disabled}><Text style={selected ? styles.selectedText : styles.choiceText}>{label}</Text></TouchableOpacity>; }
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A"},subtitle:{color:"#666",lineHeight:22,marginTop:6,marginBottom:20},group:{marginTop:16},label:{color:"#333",fontWeight:"600",marginBottom:6},input:{borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:12,fontSize:16,color:"#333"},multiline:{minHeight:130},choices:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:18},choice:{borderWidth:1,borderColor:"#2563EB",borderRadius:8,padding:9},selected:{backgroundColor:"#2563EB"},choiceText:{color:"#2563EB",fontSize:13,textTransform:"capitalize"},selectedText:{color:"#fff",fontSize:13,textTransform:"capitalize"},save:{backgroundColor:"#10B981",padding:15,borderRadius:10,alignItems:"center",marginTop:16},saveText:{color:"#fff",fontWeight:"700",fontSize:16},disabled:{opacity:.65},error:{color:"#DC2626",lineHeight:21,marginTop:4} });
