import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { Announcement, deleteAnnouncement, getAnnouncement, getAnnouncementErrorMessage, isUnauthorizedAnnouncementError, updateAnnouncement } from "../../services/announcement.service";

type Props = { managementRole: "faculty" | "admin"; listRoute: string; editRoute: string };
const typeLabel = (value: Announcement["announcement_type"]) => value === "academic" ? "Academic" : value === "assignment" ? "Assignment" : "General";
const audienceLabel = (value: Announcement["audience"]) => value === "all" ? "All users" : `${value.charAt(0).toUpperCase()}${value.slice(1)} users`;

export default function AnnouncementDetailsScreen({ managementRole, listRoute, editRoute }: Props) {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const announcementId = Number(route.params?.announcementId);
  const [item, setItem] = useState<Announcement | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(announcementId) || announcementId < 1) { setError("The announcement could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || session.user.role !== managementRole) { if (!session) await resetForUnauthorized(); else setError("You are not allowed to manage announcements."); return; } setItem(await getAnnouncement(announcementId)); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [announcementId, managementRole, resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const changeStatus = async (status: "published" | "archived") => { try { setWorking(true); setError(""); await updateAnnouncement(announcementId, { status }); await load(); Toast.show({ type: "success", text1: status === "published" ? "Announcement published" : "Announcement archived" }); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  const remove = async () => { try { setWorking(true); setError(""); await deleteAnnouncement(announcementId); Toast.show({ type: "success", text1: "Announcement deleted" }); navigation.navigate(listRoute); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Announcement not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate(listRoute)}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} />}><TouchableOpacity onPress={() => navigation.navigate(listRoute)} disabled={working}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>CAMPUSX UPDATE</Text><Text style={styles.title}>{item.title}</Text><View style={styles.badgeRow}><Text style={styles.type}>{typeLabel(item.announcement_type)}</Text><Text style={styles.status}>{item.status}</Text></View></View><Info label="Audience" value={audienceLabel(item.audience)} /><Info label="Content" value={item.content} /><Info label="Published" value={item.published_at ? item.published_at.slice(0, 10) : "Not published"} />{item.creator_name ? <Info label="Created by" value={item.creator_name} /> : null}{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()} disabled={working}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}<TouchableOpacity style={[styles.edit, working && styles.disabled]} disabled={working} onPress={() => navigation.navigate(editRoute, { announcementId })}><Text style={styles.editText}>Edit Announcement</Text></TouchableOpacity>{item.status === "draft" ? <TouchableOpacity style={[styles.publish, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Publish announcement?", "The selected audience will be able to view it.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void changeStatus("published") }])}><Text style={styles.publishText}>{working ? "Saving…" : "Publish"}</Text></TouchableOpacity> : null}{item.status !== "archived" ? <TouchableOpacity style={[styles.archive, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Archive announcement?", "It will no longer be visible to its audience.", [{ text: "Cancel", style: "cancel" }, { text: "Archive", style: "destructive", onPress: () => void changeStatus("archived") }])}><Text style={styles.archiveText}>Archive</Text></TouchableOpacity> : null}<TouchableOpacity style={[styles.remove, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Delete announcement?", `Delete “${item.title}”? This cannot be undone.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void remove() }])}><Text style={styles.removeText}>Delete Announcement</Text></TouchableOpacity></ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { const isContent = label === "Content"; return <View style={[styles.info, isContent && styles.readingCard]}><Text style={styles.label}>{label}</Text><Text style={[styles.value, isContent && styles.readingValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{...ui.card,marginBottom:spacing.md,paddingVertical:spacing.xl,borderColor:colors.primary},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:28,lineHeight:35},badgeRow:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.lg},type:{color:colors.primary,fontWeight:"700",backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},status:{color:colors.success,fontWeight:"700",textTransform:"capitalize",backgroundColor:colors.surfaceRaised,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},info:{...ui.card,marginTop:spacing.md},readingCard:{backgroundColor:colors.backgroundElevated,paddingVertical:spacing.xl},label:{color:colors.text,fontSize:14,fontWeight:"800",letterSpacing:.2},value:{...typography.body,color:colors.textMuted,lineHeight:22,marginTop:spacing.sm},readingValue:{color:colors.text,lineHeight:25},edit:{...ui.outlineButton,marginTop:spacing.xl},editText:ui.outlineButtonText,publish:{...ui.primaryButton,marginTop:spacing.sm},publishText:ui.primaryButtonText,archive:{...ui.outlineButton,marginTop:spacing.sm,borderColor:colors.warning},archiveText:{...ui.outlineButtonText,color:colors.warning},remove:{...ui.outlineButton,marginTop:spacing.sm,borderColor:colors.error},removeText:{...ui.outlineButtonText,color:colors.error},disabled:ui.disabled,errorBox:{...ui.errorState,...ui.card,marginTop:spacing.lg},error:{color:colors.error,textAlign:"center",lineHeight:21},retry:{...ui.textButton,marginTop:spacing.sm} });
