import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AnnouncementAudience, AnnouncementStatus, AnnouncementType, createAnnouncement, getAnnouncement, getAnnouncementErrorMessage, isUnauthorizedAnnouncementError, updateAnnouncement } from "../../services/announcement.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

type Props = { mode: "create" | "edit"; managementRole: "faculty" | "admin" };
const types: { value: AnnouncementType; label: string }[] = [{ value: "academic", label: "Academic" }, { value: "assignment", label: "Assignment" }, { value: "general", label: "General" }];
const audiences: { value: AnnouncementAudience; label: string }[] = [{ value: "student", label: "Student" }, { value: "graduate", label: "Graduate" }, { value: "faculty", label: "Faculty" }, { value: "recruiter", label: "Recruiter" }, { value: "all", label: "All" }];
const statuses: AnnouncementStatus[] = ["draft", "published", "archived"];

export default function AnnouncementFormScreen({ mode, managementRole }: Props) {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const announcementId = Number(route.params?.announcementId); const isEdit = mode === "edit";
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [type, setType] = useState<AnnouncementType>("academic"); const [audience, setAudience] = useState<AnnouncementAudience>("student"); const [status, setStatus] = useState<AnnouncementStatus>("draft"); const [loading, setLoading] = useState(isEdit); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!isEdit) return; if (!Number.isInteger(announcementId) || announcementId < 1) { setError("The announcement could not be found."); setLoading(false); return; } try { setLoading(true); const item = await getAnnouncement(announcementId); setTitle(item.title); setContent(item.content); setType(item.announcement_type); setAudience(item.audience); setStatus(item.status); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); } }, [announcementId, isEdit, resetForUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const normalizedTitle = title.trim(), normalizedContent = content.trim(); if (!normalizedTitle) return setError("Announcement title is required."); if (normalizedTitle.length > 200) return setError("Announcement title must be 200 characters or fewer."); if (!normalizedContent) return setError("Announcement content is required."); if (normalizedContent.length > 5000) return setError("Announcement content must be 5000 characters or fewer."); try { setSaving(true); setError(""); const session = await getStoredAuthSession(); if (!session || session.user.role !== managementRole) { if (!session) await resetForUnauthorized(); else setError("You are not allowed to manage announcements."); return; } const data = { title: normalizedTitle, content: normalizedContent, announcement_type: type, audience, ...(managementRole === "admin" || isEdit ? { status } : {}) }; if (isEdit) await updateAnnouncement(announcementId, data); else await createAnnouncement(data); Toast.show({ type: "success", text1: isEdit ? "Announcement updated" : "Announcement created", text2: !isEdit && status === "draft" ? "Saved as a draft." : undefined }); navigation.goBack(); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setSaving(false); } };
  const availableAudiences = managementRole === "faculty" ? audiences.slice(0, 2) : audiences;
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingText}>Loading announcement…</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>‹  Cancel</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>CAMPUS COMMUNICATION</Text><Text style={styles.title}>{isEdit ? "Edit Announcement" : "Create Announcement"}</Text><Text style={styles.subtitle}>{!isEdit && managementRole === "faculty" ? "Your announcement will start as a draft." : "Share a clear update with the right CampusX audience."}</Text></View><View style={styles.formCard}><Text style={styles.sectionTitle}>Announcement details</Text><Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Content" value={content} onChangeText={setContent} editable={!saving} multiline /><Text style={styles.label}>Type</Text><View style={styles.choices}>{types.map((item) => <Choice key={item.value} label={item.label} selected={type === item.value} onPress={() => setType(item.value)} disabled={saving} />)}</View><Text style={styles.label}>Audience</Text><View style={styles.choices}>{availableAudiences.map((item) => <Choice key={item.value} label={item.label} selected={audience === item.value} onPress={() => setAudience(item.value)} disabled={saving} />)}</View>{(managementRole === "admin" || isEdit) ? <><Text style={styles.label}>Status</Text><View style={styles.choices}>{statuses.map((item) => <Choice key={item} label={item} selected={status === item} onPress={() => setStatus(item)} disabled={saving} />)}</View></> : null}{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text></View> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text style={ui.primaryButtonText}>{isEdit ? "Save Changes" : "Create Draft"}</Text>}</TouchableOpacity></View></ScrollView>;
}
function Choice({ label, selected, onPress, disabled }: { label: string; selected: boolean; onPress: () => void; disabled: boolean }) { return <TouchableOpacity style={[styles.choice, selected && styles.selected]} onPress={onPress} disabled={disabled}><Text style={selected ? styles.selectedText : styles.choiceText}>{label}</Text></TouchableOpacity>; }
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
const styles = StyleSheet.create({ center:ui.centered,loadingText:{...typography.caption,marginTop:spacing.md},page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{marginBottom:spacing.xl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:typography.screenTitle,subtitle:{...typography.caption,marginTop:spacing.sm},formCard:ui.card,sectionTitle:{...typography.cardTitle,marginBottom:spacing.sm},group:{marginTop:spacing.lg},label:{color:colors.text,fontWeight:"700",marginBottom:spacing.sm},input:ui.input,multiline:{minHeight:138,paddingTop:14},choices:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginBottom:spacing.sm},choice:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},selected:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{color:colors.textMuted,fontSize:13,textTransform:"capitalize",fontWeight:"700"},selectedText:{color:colors.onPrimary,fontSize:13,textTransform:"capitalize",fontWeight:"800"},save:{...ui.primaryButton,marginTop:spacing.xl},disabled:ui.disabled,errorBox:{backgroundColor:"rgba(255,113,128,0.12)",borderRadius:radius.md,borderWidth:1,borderColor:"rgba(255,113,128,0.35)",marginTop:spacing.lg,padding:spacing.md},error:{color:colors.error,lineHeight:21,textAlign:"center"} });
