import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { CampusNotification, deleteNotification, getNotificationErrorMessage, getNotifications, isUnauthorizedNotificationError, markAllNotificationsAsRead, markNotificationAsRead } from "../../services/notification.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const typeLabel = (type: string) => type.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());

export default function NotificationsScreen() {
  const navigation = useNavigation<any>();
  const [items, setItems] = useState<CampusNotification[]>([]);
  const [unread, setUnread] = useState(false);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [working, setWorking] = useState(false);
  const [error, setError] = useState("");
  const reset = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { setItems(await getNotifications(unread ? { unread: true } : {})); setError(""); } catch (caughtError) { setError(getNotificationErrorMessage(caughtError)); if (isUnauthorizedNotificationError(caughtError)) await reset(); } finally { setLoading(false); setRefreshing(false); } }, [reset, unread]);
  useEffect(() => { void load(); const off = navigation.addListener("focus", () => void load()); return off; }, [load, navigation]);
  const open = async (item: CampusNotification) => { try { if (!item.is_read) await markNotificationAsRead(item.id); navigation.navigate("NotificationDetails", { notificationId: item.id }); } catch (caughtError) { setError(getNotificationErrorMessage(caughtError)); if (isUnauthorizedNotificationError(caughtError)) await reset(); } };
  const markAll = async () => { try { setWorking(true); await markAllNotificationsAsRead(); Toast.show({ type: "success", text1: "Notifications marked as read" }); await load(); } catch (caughtError) { setError(getNotificationErrorMessage(caughtError)); if (isUnauthorizedNotificationError(caughtError)) await reset(); } finally { setWorking(false); } };
  const remove = (id: number) => Alert.alert("Delete notification?", "This notification will be removed from your inbox.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void (async () => { try { setWorking(true); await deleteNotification(id); Toast.show({ type: "success", text1: "Notification deleted" }); await load(); } catch (caughtError) { setError(getNotificationErrorMessage(caughtError)); if (isUnauthorizedNotificationError(caughtError)) await reset(); } finally { setWorking(false); } })() }]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;

  return <ScrollView style={ui.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} colors={[colors.primary]} />}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity>
    <Text style={styles.title}>Notifications</Text><Text style={styles.subtitle}>Important CampusX updates and activity appear here.</Text>
    <View style={styles.controlRow}><View style={styles.filters}><TouchableOpacity style={[styles.filter, !unread && styles.selectedFilter]} onPress={() => setUnread(false)}><Text style={!unread ? styles.selectedText : styles.filterText}>All</Text></TouchableOpacity><TouchableOpacity style={[styles.filter, unread && styles.selectedFilter]} onPress={() => setUnread(true)}><Text style={unread ? styles.selectedText : styles.filterText}>Unread</Text></TouchableOpacity></View><TouchableOpacity style={[styles.markAll, working && ui.disabled]} disabled={working} onPress={() => void markAll()}><Text style={styles.markAllText}>{working ? "Saving…" : "Mark all read"}</Text></TouchableOpacity></View>
    {error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : items.length === 0 ? <View style={styles.emptyState}><Text style={styles.emptyTitle}>No {unread ? "unread " : ""}notifications</Text><Text style={styles.emptyText}>New CampusX updates will appear here.</Text></View> : items.map((item) => <View key={item.id} style={[styles.card, !item.is_read && styles.unreadCard]}><TouchableOpacity disabled={working} onPress={() => void open(item)}><View style={styles.cardHeader}><View style={styles.cardTitleWrap}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.type}>{typeLabel(item.type)}</Text></View>{!item.is_read ? <View style={styles.unreadBadge}><Text style={styles.unreadBadgeText}>New</Text></View> : <Text style={styles.readText}>Read</Text>}</View><Text style={styles.message} numberOfLines={2}>{item.message}</Text><Text style={styles.date}>{item.created_at.slice(0, 16).replace("T", " ")}</Text></TouchableOpacity><TouchableOpacity disabled={working} onPress={() => remove(item.id)}><Text style={styles.delete}>Delete</Text></TouchableOpacity></View>)}
  </ScrollView>;
}

const styles = StyleSheet.create({
  center: { ...ui.centered }, content: { padding: spacing.xl, paddingBottom: 48 }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.lg }, title: { ...typography.screenTitle }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl },
  controlRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm, marginBottom: spacing.lg }, filters: { flexDirection: "row", gap: spacing.sm }, filter: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: colors.backgroundElevated }, selectedFilter: { backgroundColor: colors.primary, borderColor: colors.primary }, filterText: { color: colors.textMuted, fontWeight: "800", fontSize: 12 }, selectedText: { color: colors.onPrimary, fontWeight: "800", fontSize: 12 }, markAll: { borderWidth: 1, borderColor: colors.success, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, markAllText: { color: colors.success, fontSize: 12, fontWeight: "800" },
  card: { ...ui.card, marginBottom: spacing.md }, unreadCard: { backgroundColor: colors.surfaceRaised, borderColor: colors.primary }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, cardTitleWrap: { flex: 1 }, cardTitle: { ...typography.cardTitle }, type: { color: colors.secondary, fontSize: 12, fontWeight: "700", marginTop: spacing.xs }, unreadBadge: { ...ui.badge, backgroundColor: colors.primary }, unreadBadgeText: { color: colors.onPrimary, fontSize: 10, fontWeight: "800" }, readText: { color: colors.textMuted, fontSize: 11, fontWeight: "700" }, message: { ...typography.caption, marginTop: spacing.md }, date: { color: colors.textMuted, fontSize: 12, marginTop: spacing.md }, delete: { color: colors.error, fontWeight: "800", fontSize: 13, marginTop: spacing.md },
  emptyState: { ...ui.emptyState, ...ui.card, marginTop: spacing.lg }, emptyTitle: { ...typography.cardTitle, marginBottom: spacing.xs }, emptyText: { ...typography.caption, textAlign: "center" }, errorBox: { ...ui.errorState, ...ui.card, marginTop: spacing.lg }, error: { color: colors.error, textAlign: "center" }, retry: { color: colors.primary, fontWeight: "800", marginTop: spacing.sm },
});
