import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AvailableSkill, getAvailableSkills } from "../../services/skill.service";
import { addOpportunitySkill, getOpportunitySkillError, getOpportunitySkills, isUnauthorizedOpportunitySkillError, OpportunitySkill, removeOpportunitySkill } from "../../services/opportunity-skill.service";

const managerRoles = new Set(["faculty", "recruiter", "admin"]);

export default function OpportunitySkillsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId);
  const [skills, setSkills] = useState<OpportunitySkill[]>([]); const [catalogue, setCatalogue] = useState<AvailableSkill[]>([]); const [search, setSearch] = useState(""); const [canManage, setCanManage] = useState(false); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [savingId, setSavingId] = useState<number | null>(null); const [error, setError] = useState(""); const [searching, setSearching] = useState(false);
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const handleError = useCallback(async (requestError: unknown) => { setError(getOpportunitySkillError(requestError)); if (isUnauthorizedOpportunitySkillError(requestError)) await resetForUnauthorized(); }, [resetForUnauthorized]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(opportunityId) || opportunityId <= 0) { setError("The opportunity could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); setCanManage(managerRoles.has(session?.user.role || "")); setSkills(await getOpportunitySkills(opportunityId)); setError(""); } catch (requestError) { await handleError(requestError); } finally { setLoading(false); setRefreshing(false); } }, [handleError, opportunityId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (!canManage) return; let active = true; const searchCatalogue = async () => { try { setSearching(true); const result = await getAvailableSkills(search.trim()); if (active) setCatalogue(result); } catch (requestError) { if (active) await handleError(requestError); } finally { if (active) setSearching(false); } }; searchCatalogue(); return () => { active = false; }; }, [canManage, handleError, search]);
  const attached = useMemo(() => new Set(skills.map((skill) => skill.skill_id)), [skills]);
  const add = async (skillId: number) => { try { setSavingId(skillId); setError(""); await addOpportunitySkill(opportunityId, skillId); await load(); Toast.show({ type: "success", text1: "Required skill added" }); } catch (requestError) { await handleError(requestError); } finally { setSavingId(null); } };
  const remove = (skill: OpportunitySkill) => Alert.alert("Remove required skill?", `${skill.name} will no longer be required for this opportunity.`, [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => void (async () => { try { setSavingId(skill.skill_id); setError(""); await removeOpportunitySkill(opportunityId, skill.skill_id); await load(); Toast.show({ type: "success", text1: "Required skill removed" }); } catch (requestError) { await handleError(requestError); } finally { setSavingId(null); } })() }]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Opportunity</Text></TouchableOpacity><Text style={styles.title}>Required Skills</Text>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.back}>Retry</Text></TouchableOpacity></View> : null}{skills.length === 0 ? <Text style={styles.empty}>No required skills have been added yet.</Text> : skills.map((skill) => <View key={skill.skill_id} style={styles.skillRow}><Text style={styles.skillName}>{skill.name}</Text>{canManage ? <TouchableOpacity disabled={savingId !== null} onPress={() => remove(skill)}><Text style={styles.remove}>{savingId === skill.skill_id ? "Removing…" : "Remove"}</Text></TouchableOpacity> : null}</View>)}{canManage ? <View style={styles.searchPanel}><Text style={styles.sectionTitle}>Add Required Skill</Text><TextInput style={styles.input} value={search} onChangeText={setSearch} placeholder="Search skills" autoCapitalize="none" /><Text style={styles.helper}>Select an existing skill from the catalogue.</Text>{searching ? <ActivityIndicator color="#2563EB" style={styles.spinner} /> : catalogue.filter((skill) => !attached.has(skill.id)).map((skill) => <TouchableOpacity key={skill.id} style={styles.catalogueRow} disabled={savingId !== null} onPress={() => add(skill.id)}><Text style={styles.skillName}>{skill.name}</Text><Text style={styles.add}>{savingId === skill.id ? "Adding…" : "Add"}</Text></TouchableOpacity>)}{!searching && catalogue.length > 0 && catalogue.every((skill) => attached.has(skill.id)) ? <Text style={styles.helper}>All matching skills are already required.</Text> : null}{!searching && search.trim() && catalogue.length === 0 ? <Text style={styles.helper}>No matching catalogue skills found.</Text> : null}</View> : null}</ScrollView>;
}
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 28, fontWeight: "bold", color: "#1E3A8A", marginBottom: 18 }, empty: { color: "#666", textAlign: "center", marginTop: 18 }, skillRow: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 10, padding: 14, marginBottom: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, skillName: { color: "#333", fontWeight: "700", flex: 1 }, remove: { color: "#DC2626", fontWeight: "700", marginLeft: 14 }, searchPanel: { borderTopWidth: 1, borderColor: "#E5E7EB", marginTop: 18, paddingTop: 20 }, sectionTitle: { color: "#1E3A8A", fontWeight: "700", fontSize: 18 }, input: { borderWidth: 1, borderColor: "#D1D5DB", borderRadius: 8, padding: 11, marginTop: 12 }, helper: { color: "#4B5563", marginTop: 8 }, spinner: { marginTop: 16 }, catalogueRow: { borderWidth: 1, borderColor: "#BFDBFE", backgroundColor: "#EFF6FF", borderRadius: 8, padding: 12, marginTop: 10, flexDirection: "row", justifyContent: "space-between" }, add: { color: "#2563EB", fontWeight: "700", marginLeft: 14 }, errorBox: { alignItems: "center", marginBottom: 14 }, error: { color: "#DC2626", textAlign: "center", marginBottom: 8 } });
