import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { AvailableSkill, getAvailableSkills } from "../../services/skill.service";
import { addOpportunitySkill, getOpportunitySkillError, getOpportunitySkills, isUnauthorizedOpportunitySkillError, OpportunitySkill, removeOpportunitySkill } from "../../services/opportunity-skill.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const managerRoles = new Set(["faculty", "recruiter", "admin"]);

export default function OpportunitySkillsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId);
  const [skills, setSkills] = useState<OpportunitySkill[]>([]); const [catalogue, setCatalogue] = useState<AvailableSkill[]>([]); const [search, setSearch] = useState(""); const [canManage, setCanManage] = useState(false); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [savingId, setSavingId] = useState<number | null>(null); const [error, setError] = useState(""); const [searching, setSearching] = useState(false);
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const handleError = useCallback(async (requestError: unknown) => { setError(getOpportunitySkillError(requestError)); if (isUnauthorizedOpportunitySkillError(requestError)) await resetForUnauthorized(); }, [resetForUnauthorized]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(opportunityId) || opportunityId <= 0) { setError("The opportunity could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); setCanManage(managerRoles.has(session?.user.role || "")); setSkills(await getOpportunitySkills(opportunityId)); setError(""); } catch (requestError) { await handleError(requestError); } finally { setLoading(false); setRefreshing(false); } }, [handleError, opportunityId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (!canManage) return; let active = true; const searchCatalogue = async () => { try { setSearching(true); const result = await getAvailableSkills(search.trim()); if (active) setCatalogue(result); } catch (requestError) { if (active) await handleError(requestError); } finally { if (active) setSearching(false); } }; searchCatalogue(); return () => { active = false; }; }, [canManage, handleError, search]);
  const attached = useMemo(() => new Set(skills.map((skill) => skill.skill_id)), [skills]);
  const add = async (skillId: number) => { try { setSavingId(skillId); setError(""); await addOpportunitySkill(opportunityId, skillId); await load(); Toast.show({ type: "success", text1: "Required skill added" }); } catch (requestError) { await handleError(requestError); } finally { setSavingId(null); } };
  const remove = (skill: OpportunitySkill) => Alert.alert("Remove required skill?", `${skill.name} will no longer be required for this opportunity.`, [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => void (async () => { try { setSavingId(skill.skill_id); setError(""); await removeOpportunitySkill(opportunityId, skill.skill_id); await load(); Toast.show({ type: "success", text1: "Required skill removed" }); } catch (requestError) { await handleError(requestError); } finally { setSavingId(null); } })() }]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingText}>Loading required skills…</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.primary} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>‹  Back to Opportunity</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>OPPORTUNITY SETUP</Text><Text style={styles.title}>Required Skills</Text><Text style={styles.subtitle}>Define the skills applicants need to succeed in this opportunity.</Text></View>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}<View style={styles.skillsCard}>{skills.length === 0 ? <View style={styles.emptyState}><Text style={styles.empty}>No required skills have been added yet.</Text></View> : skills.map((skill) => <View key={skill.skill_id} style={styles.skillRow}><View style={styles.skillChip}><Text style={styles.skillName}>{skill.name}</Text></View>{canManage ? <TouchableOpacity disabled={savingId !== null} onPress={() => remove(skill)}><Text style={styles.remove}>{savingId === skill.skill_id ? "Removing…" : "Remove"}</Text></TouchableOpacity> : null}</View>)}</View>{canManage ? <View style={styles.searchPanel}><Text style={styles.sectionTitle}>Add Required Skill</Text><TextInput style={styles.input} value={search} onChangeText={setSearch} placeholder="Search skills" placeholderTextColor={colors.textMuted} autoCapitalize="none" /><Text style={styles.helper}>Select an existing skill from the catalogue.</Text>{searching ? <ActivityIndicator color={colors.primary} style={styles.spinner} /> : catalogue.filter((skill) => !attached.has(skill.id)).map((skill) => <TouchableOpacity key={skill.id} style={styles.catalogueRow} disabled={savingId !== null} onPress={() => add(skill.id)}><Text style={styles.skillName}>{skill.name}</Text><Text style={styles.add}>{savingId === skill.id ? "Adding…" : "Add"}</Text></TouchableOpacity>)}{!searching && catalogue.length > 0 && catalogue.every((skill) => attached.has(skill.id)) ? <Text style={styles.helper}>All matching skills are already required.</Text> : null}{!searching && search.trim() && catalogue.length === 0 ? <Text style={styles.helper}>No matching catalogue skills found.</Text> : null}</View> : null}</ScrollView>;
}
const styles = StyleSheet.create({ center:ui.centered,loadingText:{...typography.caption,marginTop:spacing.md},page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{marginBottom:spacing.xl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:typography.screenTitle,subtitle:typography.caption,errorBox:{backgroundColor:"rgba(255,113,128,0.12)",borderRadius:radius.md,borderWidth:1,borderColor:"rgba(255,113,128,0.35)",alignItems:"center",marginBottom:spacing.lg,padding:spacing.md},error:{color:colors.error,textAlign:"center"},retry:{...ui.textButton,marginTop:spacing.sm},skillsCard:ui.card,emptyState:ui.emptyState,empty:typography.caption,skillRow:{borderBottomWidth:1,borderColor:colors.divider,paddingVertical:spacing.md,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},skillChip:{backgroundColor:"rgba(74,168,255,0.14)",borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},skillName:{color:colors.text,fontWeight:"700",flexShrink:1},remove:{color:colors.error,fontWeight:"800",marginLeft:spacing.md},searchPanel:{...ui.card,marginTop:spacing.lg},sectionTitle:typography.cardTitle,input:{...ui.input,marginTop:spacing.md},helper:{...typography.caption,marginTop:spacing.sm},spinner:{marginTop:spacing.lg},catalogueRow:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.input,borderRadius:radius.md,padding:spacing.md,marginTop:spacing.sm,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},add:{color:colors.primary,fontWeight:"800",marginLeft:spacing.md} });
