import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { getPlannerErrorMessage, getPlannerItems, isUnauthorizedPlannerError, PlannerFilters, PlannerItem, PlannerItemStatus, PlannerItemType } from "../../services/planner.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: { value?: PlannerItemType; label: string }[] = [{ label: "All" }, { value: "assignment", label: "Assignment" }, { value: "exam", label: "Exam" }, { value: "meeting", label: "Meeting" }, { value: "personal", label: "Personal" }, { value: "thesis_research", label: "Thesis / Research" }];
const statuses: { value?: PlannerItemStatus; label: string }[] = [{ label: "All" }, { value: "pending", label: "Pending" }, { value: "completed", label: "Completed" }, { value: "cancelled", label: "Cancelled" }];
const label = (value: string) => value === "thesis_research" ? "Thesis / Research" : value.charAt(0).toUpperCase() + value.slice(1);
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";
const overdue = (item: PlannerItem) => item.status === "pending" && new Date(item.due_at).getTime() < Date.now();

export default function PlannerScreen() {
  const navigation = useNavigation<any>();
  const [items, setItems] = useState<PlannerItem[]>([]); const [itemType, setItemType] = useState<PlannerItemType | undefined>(); const [status, setStatus] = useState<PlannerItemStatus | undefined>(); const [dueFrom, setDueFrom] = useState(""); const [dueTo, setDueTo] = useState(""); const [upcoming, setUpcoming] = useState(true); const [activeFilters, setActiveFilters] = useState<PlannerFilters>({ upcoming: true }); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Planner is available to students and graduates only."); return; } setItems(await getPlannerItems(activeFilters)); setError(""); } catch (caughtError) { setError(getPlannerErrorMessage(caughtError)); if (isUnauthorizedPlannerError(caughtError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [activeFilters, resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const applyFilters = () => setActiveFilters({ item_type: itemType, status, due_from: dueFrom.trim() || undefined, due_to: dueTo.trim() || undefined, ...(upcoming ? { upcoming: true } : {}) });
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;

  return <ScrollView style={ui.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} colors={[colors.primary]} />}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity>
    <Text style={styles.title}>Planner</Text><Text style={styles.subtitle}>Organize academic, career, and personal priorities in one place.</Text>
    <TouchableOpacity style={ui.primaryButton} onPress={() => navigation.navigate("CreatePlannerItem")}><Text style={ui.primaryButtonText}>Add Planner Item</Text></TouchableOpacity>
    <View style={styles.filterPanel}><View style={styles.filterHeader}><Text style={styles.filterTitle}>Plan view</Text><TouchableOpacity style={[styles.upcoming, upcoming && styles.upcomingSelected]} onPress={() => setUpcoming(!upcoming)}><Text style={upcoming ? styles.upcomingSelectedText : styles.upcomingText}>{upcoming ? "Upcoming" : "All dates"}</Text></TouchableOpacity></View>
      <Text style={styles.filterLabel}>TYPE</Text><View style={styles.choices}>{types.map((item) => <Choice key={item.label} label={item.label} selected={itemType === item.value} onPress={() => setItemType(item.value)} />)}</View>
      <Text style={styles.filterLabel}>STATUS</Text><View style={styles.choices}>{statuses.map((item) => <Choice key={item.label} label={item.label} selected={status === item.value} onPress={() => { setStatus(item.value); if (item.value && item.value !== "pending") setUpcoming(false); }} />)}</View>
      <View style={styles.dates}><TextInput style={[ui.input, styles.dateInput]} value={dueFrom} onChangeText={setDueFrom} placeholder="Due from (YYYY-MM-DD)" placeholderTextColor={colors.textMuted} /><TextInput style={[ui.input, styles.dateInput]} value={dueTo} onChangeText={setDueTo} placeholder="Due to (YYYY-MM-DD)" placeholderTextColor={colors.textMuted} /></View>
      <TouchableOpacity style={[ui.outlineButton, styles.apply]} onPress={applyFilters}><Text style={ui.outlineButtonText}>Apply Filters</Text></TouchableOpacity>
    </View>
    {error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}
    {!error && items.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No planner items found</Text><Text style={styles.emptyText}>Add an assignment, exam, meeting, or personal task to get started.</Text></View> : null}
    {items.map((item) => <TouchableOpacity key={item.id} style={[styles.card, overdue(item) && styles.overdueCard]} onPress={() => navigation.navigate("PlannerItemDetails", { itemId: item.id })}><View style={styles.cardHeader}><Text style={styles.cardTitle}>{item.title}</Text><View style={[styles.statusBadge, item.status === "completed" && styles.completed, item.status === "cancelled" && styles.cancelled, overdue(item) && styles.overdue]}><Text style={styles.status}>{overdue(item) ? "Overdue" : label(item.status)}</Text></View></View><Text style={styles.type}>{label(item.item_type)} · {label(item.priority)} priority</Text><Text style={styles.due}>Due: {item.due_at.slice(0, 16).replace("T", " ")}</Text>{item.description ? <Text style={styles.description} numberOfLines={2}>{item.description}</Text> : null}<Text style={styles.viewAction}>View details</Text></TouchableOpacity>)}
  </ScrollView>;
}

function Choice({ label: choiceLabel, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <TouchableOpacity style={[styles.choice, selected && styles.selected]} onPress={onPress}><Text style={selected ? styles.selectedText : styles.choiceText}>{choiceLabel}</Text></TouchableOpacity>; }

const styles = StyleSheet.create({
  center: { ...ui.centered }, content: { padding: spacing.xl, paddingBottom: 48 }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.lg }, title: { ...typography.screenTitle }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl },
  filterPanel: { ...ui.card, marginTop: spacing.lg }, filterHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md, marginBottom: spacing.lg }, filterTitle: { ...typography.cardTitle }, upcoming: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: colors.backgroundElevated }, upcomingSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, upcomingText: { color: colors.textMuted, fontSize: 12, fontWeight: "800" }, upcomingSelectedText: { color: colors.onPrimary, fontSize: 12, fontWeight: "800" }, filterLabel: { color: colors.secondary, fontSize: 11, fontWeight: "800", letterSpacing: 1, marginBottom: spacing.sm }, choices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.lg }, choice: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: colors.backgroundElevated }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.textMuted, fontSize: 12, fontWeight: "700" }, selectedText: { color: colors.onPrimary, fontSize: 12, fontWeight: "800" }, dates: { gap: spacing.sm }, dateInput: { ...typography.input }, apply: { marginTop: spacing.lg },
  card: { ...ui.card, marginTop: spacing.md }, overdueCard: { borderColor: colors.error, backgroundColor: "#2A1A28" }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, cardTitle: { ...typography.cardTitle, flex: 1 }, type: { color: colors.secondary, fontSize: 13, fontWeight: "700", marginTop: spacing.sm }, statusBadge: { ...ui.badge, backgroundColor: "#3D341D", borderWidth: 1, borderColor: colors.warning }, status: { color: colors.warning, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, completed: { backgroundColor: "#123D3C", borderColor: colors.success }, cancelled: { backgroundColor: colors.backgroundElevated, borderColor: colors.textMuted }, overdue: { backgroundColor: "#48232C", borderColor: colors.error }, due: { ...typography.caption, marginTop: spacing.md }, description: { ...typography.caption, marginTop: spacing.sm }, viewAction: { color: colors.primary, fontSize: 13, fontWeight: "800", marginTop: spacing.md },
  empty: { ...ui.emptyState, ...ui.card, marginTop: spacing.lg }, emptyTitle: { ...typography.cardTitle, marginBottom: spacing.xs }, emptyText: { ...typography.caption, textAlign: "center" }, errorBox: { ...ui.errorState, ...ui.card, marginTop: spacing.lg }, error: { color: colors.error, textAlign: "center", lineHeight: 21 }, retry: { color: colors.primary, fontWeight: "800", marginTop: spacing.sm },
});
