import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { createPlannerItem, getPlannerErrorMessage, getPlannerItemById, isUnauthorizedPlannerError, PlannerItemStatus, PlannerItemType, PlannerPriority, updatePlannerItem } from "../../services/planner.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

type Props = { mode: "create" | "edit" };
const types: { value: PlannerItemType; label: string }[] = [{ value: "assignment", label: "Assignment" }, { value: "exam", label: "Exam" }, { value: "meeting", label: "Meeting" }, { value: "personal", label: "Personal" }, { value: "thesis_research", label: "Thesis / Research" }];
const priorities: PlannerPriority[] = ["low", "medium", "high"];
const statuses: PlannerItemStatus[] = ["pending", "completed", "cancelled"];
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";
const normalizeDateTime = (value: string) => { const match = value.trim().match(/^(\d{4}-\d{2}-\d{2})[T ](\d{2}:\d{2})(?::(\d{2}))?$/); if (!match) return null; const seconds = match[3] || "00"; const parsed = new Date(`${match[1]}T${match[2]}:${seconds}.000Z`); if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== match[1] || parsed.toISOString().slice(11, 19) !== `${match[2]}:${seconds}`) return null; return `${match[1]} ${match[2]}:${seconds}`; };

export default function PlannerItemFormScreen({ mode }: Props) {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const itemId = Number(route.params?.itemId); const isEdit = mode === "edit";
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [itemType, setItemType] = useState<PlannerItemType>("assignment"); const [dueAt, setDueAt] = useState(""); const [priority, setPriority] = useState<PlannerPriority>("medium"); const [status, setStatus] = useState<PlannerItemStatus>("pending"); const [loading, setLoading] = useState(isEdit); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!isEdit) return; if (!Number.isInteger(itemId) || itemId < 1) { setError("The planner item could not be found."); setLoading(false); return; } try { setLoading(true); const item = await getPlannerItemById(itemId); setTitle(item.title); setDescription(item.description || ""); setItemType(item.item_type); setDueAt(item.due_at.slice(0, 16).replace("T", " ")); setPriority(item.priority); setStatus(item.status); setError(""); } catch (requestError) { setError(getPlannerErrorMessage(requestError)); if (isUnauthorizedPlannerError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); } }, [isEdit, itemId, resetForUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const normalizedTitle = title.trim(), normalizedDueAt = normalizeDateTime(dueAt); if (!normalizedTitle) return setError("Planner item title is required."); if (normalizedTitle.length > 200) return setError("Planner item title must be 200 characters or fewer."); if (description.trim().length > 5000) return setError("Description must be 5000 characters or fewer."); if (!normalizedDueAt) return setError("Due date and time must use YYYY-MM-DD HH:mm."); try { setSaving(true); setError(""); const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Planner is available to students and graduates only."); return; } const data = { title: normalizedTitle, description: description.trim() || null, item_type: itemType, due_at: normalizedDueAt, priority, ...(isEdit ? { status } : {}) }; if (isEdit) await updatePlannerItem(itemId, data); else await createPlannerItem(data); Toast.show({ type: "success", text1: isEdit ? "Planner item updated" : "Planner item created" }); navigation.goBack(); } catch (requestError) { setError(getPlannerErrorMessage(requestError)); if (isUnauthorizedPlannerError(requestError)) await resetForUnauthorized(); } finally { setSaving(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingText}>Loading planner item…</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>‹  Cancel</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>ACADEMIC & CAREER PLANNING</Text><Text style={styles.title}>{isEdit ? "Edit Planner Item" : "Add Planner Item"}</Text><Text style={styles.subtitle}>Plan the work that moves your academic and career goals forward.</Text></View><View style={styles.formCard}><Text style={styles.sectionTitle}>Item details</Text><Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Description (optional)" value={description} onChangeText={setDescription} editable={!saving} multiline /><Text style={styles.label}>Type</Text><View style={styles.choices}>{types.map((item) => <Choice key={item.value} label={item.label} selected={itemType === item.value} onPress={() => setItemType(item.value)} disabled={saving} />)}</View><Input label="Due date and time" value={dueAt} onChangeText={setDueAt} editable={!saving} placeholder="YYYY-MM-DD HH:mm" /><Text style={styles.label}>Priority</Text><View style={styles.choices}>{priorities.map((item) => <Choice key={item} label={item} selected={priority === item} onPress={() => setPriority(item)} disabled={saving} />)}</View>{isEdit ? <><Text style={styles.label}>Status</Text><View style={styles.choices}>{statuses.map((item) => <Choice key={item} label={item} selected={status === item} onPress={() => setStatus(item)} disabled={saving} />)}</View></> : null}{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text></View> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text style={ui.primaryButtonText}>{isEdit ? "Save Changes" : "Create Planner Item"}</Text>}</TouchableOpacity></View></ScrollView>;
}
function Choice({ label, selected, onPress, disabled }: { label: string; selected: boolean; onPress: () => void; disabled: boolean }) { return <TouchableOpacity style={[styles.choice, selected && styles.selected]} onPress={onPress} disabled={disabled}><Text style={selected ? styles.selectedText : styles.choiceText}>{label}</Text></TouchableOpacity>; }
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean; placeholder?: string }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} placeholderTextColor={colors.textMuted} {...props} /></View>; }
const styles = StyleSheet.create({ center:ui.centered,loadingText:{...typography.caption,marginTop:spacing.md},page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{marginBottom:spacing.xl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:typography.screenTitle,subtitle:{...typography.caption,marginTop:spacing.sm},formCard:ui.card,sectionTitle:{...typography.cardTitle,marginBottom:spacing.sm},group:{marginTop:spacing.lg},label:{color:colors.text,fontWeight:"700",marginBottom:spacing.sm},input:ui.input,multiline:{minHeight:118,paddingTop:14},choices:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginBottom:spacing.sm},choice:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},selected:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{color:colors.textMuted,fontSize:13,textTransform:"capitalize",fontWeight:"700"},selectedText:{color:colors.onPrimary,fontSize:13,textTransform:"capitalize",fontWeight:"800"},save:{...ui.primaryButton,marginTop:spacing.xl},disabled:ui.disabled,errorBox:{backgroundColor:"rgba(255,113,128,0.12)",borderRadius:radius.md,borderWidth:1,borderColor:"rgba(255,113,128,0.35)",marginTop:spacing.lg,padding:spacing.md},error:{color:colors.error,lineHeight:21,textAlign:"center"} });
