import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { deletePlannerItem, getPlannerErrorMessage, getPlannerItemById, isUnauthorizedPlannerError, PlannerItem, updatePlannerItem } from "../../services/planner.service";

const label = (value: string) => value === "thesis_research" ? "Thesis / Research" : value.charAt(0).toUpperCase() + value.slice(1);
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";
export default function PlannerItemDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const itemId = Number(route.params?.itemId); const [item, setItem] = useState<PlannerItem | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(itemId) || itemId < 1) { setError("The planner item could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Planner is available to students and graduates only."); return; } setItem(await getPlannerItemById(itemId)); setError(""); } catch (requestError) { setError(getPlannerErrorMessage(requestError)); if (isUnauthorizedPlannerError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [itemId, resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const changeStatus = async (status: "completed" | "cancelled") => { try { setWorking(true); setError(""); await updatePlannerItem(itemId, { status }); await load(); Toast.show({ type: "success", text1: status === "completed" ? "Planner item completed" : "Planner item cancelled" }); } catch (requestError) { setError(getPlannerErrorMessage(requestError)); if (isUnauthorizedPlannerError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  const remove = async () => { try { setWorking(true); setError(""); await deletePlannerItem(itemId); Toast.show({ type: "success", text1: "Planner item deleted" }); navigation.navigate("Planner"); } catch (requestError) { setError(getPlannerErrorMessage(requestError)); if (isUnauthorizedPlannerError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Planner item not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate("Planner")}><Text style={styles.back}>Back to Planner</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}><TouchableOpacity onPress={() => navigation.navigate("Planner")} disabled={working}><Text style={styles.back}>Back to Planner</Text></TouchableOpacity><Text style={styles.title}>{item.title}</Text><Text style={styles.type}>{label(item.item_type)} · {label(item.priority)} priority</Text><Text style={styles.status}>{label(item.status)}</Text><Info label="Due" value={item.due_at.slice(0, 16).replace("T", " ")} /><Info label="Description" value={item.description || "Not provided"} /><Info label="Created" value={item.created_at.slice(0, 16).replace("T", " ")} /><Info label="Last updated" value={item.updated_at.slice(0, 16).replace("T", " ")} />{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()} disabled={working}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}<TouchableOpacity style={[styles.edit, working && styles.disabled]} disabled={working} onPress={() => navigation.navigate("EditPlannerItem", { itemId })}><Text style={styles.editText}>Edit Planner Item</Text></TouchableOpacity>{item.status === "pending" ? <><TouchableOpacity style={[styles.complete, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Mark completed?", "This will mark the planner item as completed.", [{ text: "Cancel", style: "cancel" }, { text: "Complete", onPress: () => void changeStatus("completed") }])}><Text style={styles.completeText}>{working ? "Saving…" : "Mark Completed"}</Text></TouchableOpacity><TouchableOpacity style={[styles.cancel, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Cancel planner item?", "This will mark the item as cancelled.", [{ text: "Keep", style: "cancel" }, { text: "Cancel Item", style: "destructive", onPress: () => void changeStatus("cancelled") }])}><Text style={styles.cancelText}>Cancel Item</Text></TouchableOpacity></> : null}<TouchableOpacity style={[styles.remove, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Delete planner item?", `Delete “${item.title}”? This cannot be undone.`, [{ text: "Keep", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void remove() }])}><Text style={styles.removeText}>Delete Planner Item</Text></TouchableOpacity></ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24,backgroundColor:"#fff"},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:28,fontWeight:"bold",color:"#1E3A8A"},type:{color:"#2563EB",fontWeight:"600",marginTop:7},status:{color:"#047857",fontWeight:"700",textTransform:"capitalize",marginTop:6},info:{marginTop:20},label:{color:"#333",fontWeight:"700"},value:{color:"#4B5563",lineHeight:22,marginTop:5},edit:{borderWidth:1,borderColor:"#2563EB",borderRadius:10,padding:14,alignItems:"center",marginTop:28},editText:{color:"#2563EB",fontWeight:"700"},complete:{backgroundColor:"#10B981",borderRadius:10,padding:14,alignItems:"center",marginTop:12},completeText:{color:"#fff",fontWeight:"700"},cancel:{borderWidth:1,borderColor:"#D97706",borderRadius:10,padding:14,alignItems:"center",marginTop:12},cancelText:{color:"#D97706",fontWeight:"700"},remove:{borderWidth:1,borderColor:"#DC2626",borderRadius:10,padding:14,alignItems:"center",marginTop:12},removeText:{color:"#DC2626",fontWeight:"700"},disabled:{opacity:.6},errorBox:{alignItems:"center",marginTop:18},error:{color:"#DC2626",textAlign:"center",lineHeight:21},retry:{color:"#2563EB",fontWeight:"700",marginTop:10} });
