import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import * as DocumentPicker from "expo-document-picker";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { createMyPublication, deleteMyPublication, getMyPublications, getPublicationErrorMessage, isUnauthorizedPublicationError, Publication, PublicationInput, updateMyPublication, uploadMyPublicationFile } from "../../services/publication.service";

type Form = { title: string; authors: string; journal_or_conference: string; publication_date: string; doi: string; publication_url: string; abstract: string };
const emptyForm: Form = { title: "", authors: "", journal_or_conference: "", publication_date: "", doi: "", publication_url: "", abstract: "" };
const datePattern = /^\d{4}-\d{2}-\d{2}$/;
const validDate = (value: string) => { if (!datePattern.test(value)) return false; const date = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value; };
const validUrl = (value: string) => /^https?:\/\/\S+$/i.test(value);
const displayDate = (value: string) => value.slice(0, 10);

export default function PublicationsScreen() {
  const navigation = useNavigation<any>(); const [publications, setPublications] = useState<Publication[]>([]); const [form, setForm] = useState<Form>(emptyForm); const [editingId, setEditingId] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [saving, setSaving] = useState(false); const [errorMessage, setErrorMessage] = useState("");
  const unauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); try { setPublications(await getMyPublications()); setErrorMessage(""); } catch (error) { setErrorMessage(getPublicationErrorMessage(error)); if (isUnauthorizedPublicationError(error)) await unauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [unauthorized]);
  useEffect(() => { load(); }, [load]);
  const setField = (field: keyof Form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const validate = () => { if (!form.title.trim() || !form.authors.trim() || !form.journal_or_conference.trim()) return "Title, authors, and journal or conference are required."; if (![form.title, form.journal_or_conference].every((value) => value.trim().length <= 300) || form.authors.trim().length > 1000) return "One or more fields exceed the allowed length."; if (!validDate(form.publication_date.trim())) return "Publication date must use YYYY-MM-DD."; if (form.doi.trim().length > 255 || form.abstract.length > 5000) return "DOI or abstract exceeds the allowed length."; if (form.publication_url.trim() && !validUrl(form.publication_url.trim())) return "Publication URL must start with http:// or https://."; if (form.publication_url.trim().length > 2048) return "Publication URL must be 2048 characters or fewer."; return null; };
  const payload = (): PublicationInput => ({ title: form.title.trim(), authors: form.authors.trim(), journal_or_conference: form.journal_or_conference.trim(), publication_date: form.publication_date.trim(), doi: form.doi.trim() || null, publication_url: form.publication_url.trim() || null, abstract: form.abstract.trim() || null });
  const reset = () => { setForm(emptyForm); setEditingId(null); };
  const save = async () => { const message = validate(); if (message) { setErrorMessage(message); Toast.show({ type: "error", text1: "Check your publication", text2: message }); return; } setSaving(true); setErrorMessage(""); try { if (editingId === null) await createMyPublication(payload()); else await updateMyPublication(editingId, payload()); const editing = editingId !== null; reset(); await load(); Toast.show({ type: "success", text1: editing ? "Publication updated" : "Publication created", text2: "Your publication has been saved." }); } catch (error) { const text = getPublicationErrorMessage(error); setErrorMessage(text); Toast.show({ type: "error", text1: "Unable to save publication", text2: text }); if (isUnauthorizedPublicationError(error)) await unauthorized(); } finally { setSaving(false); } };
  const edit = (publication: Publication) => { setEditingId(publication.id); setForm({ title: publication.title, authors: publication.authors, journal_or_conference: publication.journal_or_conference, publication_date: displayDate(publication.publication_date), doi: publication.doi || "", publication_url: publication.publication_url || "", abstract: publication.abstract || "" }); setErrorMessage(""); };
  const remove = async (publication: Publication) => { setSaving(true); setErrorMessage(""); try { await deleteMyPublication(publication.id); if (editingId === publication.id) reset(); await load(); Toast.show({ type: "success", text1: "Publication deleted", text2: "Your publication was removed." }); } catch (error) { const text = getPublicationErrorMessage(error); setErrorMessage(text); Toast.show({ type: "error", text1: "Unable to delete publication", text2: text }); if (isUnauthorizedPublicationError(error)) await unauthorized(); } finally { setSaving(false); } };
  if (loading) return <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /></View>;
  return <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.primary} />}>
    <TouchableOpacity style={styles.back} onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.backText}>Back to Profile</Text></TouchableOpacity><Text style={styles.title}>Publications</Text><Text style={styles.subtitle}>Present your graduate research, publications, and scholarly contributions.</Text>
    {!!errorMessage && <View style={styles.errorBox}><Text style={styles.error}>{errorMessage}</Text><TouchableOpacity style={styles.retry} onPress={() => load()} disabled={saving}><Text style={styles.retryText}>Retry</Text></TouchableOpacity></View>}
    <View style={styles.form}><Text style={styles.section}>{editingId === null ? "Add Publication" : "Edit Publication"}</Text><Input label="Title" value={form.title} onChangeText={(v) => setField("title", v)} editable={!saving} /><Input label="Authors" value={form.authors} onChangeText={(v) => setField("authors", v)} editable={!saving} /><Input label="Journal or conference" value={form.journal_or_conference} onChangeText={(v) => setField("journal_or_conference", v)} editable={!saving} /><Input label="Publication date (YYYY-MM-DD)" value={form.publication_date} onChangeText={(v) => setField("publication_date", v)} editable={!saving} autoCapitalize="none" /><Input label="DOI (optional)" value={form.doi} onChangeText={(v) => setField("doi", v)} editable={!saving} autoCapitalize="none" /><Input label="Publication URL (optional)" value={form.publication_url} onChangeText={(v) => setField("publication_url", v)} editable={!saving} autoCapitalize="none" keyboardType="url" /><Input label="Abstract (optional)" value={form.abstract} onChangeText={(v) => setField("abstract", v)} editable={!saving} multiline /><TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={save} disabled={saving}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>{editingId === null ? "Create Publication" : "Save Publication"}</Text>}</TouchableOpacity>{editingId !== null && <TouchableOpacity style={styles.cancel} onPress={reset} disabled={saving}><Text style={styles.cancelText}>Cancel editing</Text></TouchableOpacity>}</View>
    <Text style={styles.section}>My Publications</Text>{publications.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No publications yet</Text><Text style={styles.emptyText}>Add your research publication above to build your graduate profile.</Text></View> : publications.map((publication) => <View key={publication.id} style={styles.card}><Text style={styles.cardTitle}>{publication.title}</Text><Text style={styles.authors}>{publication.authors}</Text><Text style={styles.details}>{publication.journal_or_conference}</Text><Text style={styles.details}>Published: {displayDate(publication.publication_date)}</Text>{publication.doi && <Text style={styles.details}>DOI: {publication.doi}</Text>}{publication.publication_url && <Text style={styles.url} numberOfLines={2}>Publication: {publication.publication_url}</Text>}{publication.abstract && <Text style={styles.abstract}>{publication.abstract}</Text>}<View style={styles.actions}><PublicationUpload publication={publication} disabled={saving} onUploaded={load} onError={setErrorMessage} onUnauthorized={unauthorized} /><TouchableOpacity style={styles.edit} onPress={() => edit(publication)} disabled={saving}><Text style={styles.editText}>Edit</Text></TouchableOpacity><TouchableOpacity style={styles.delete} onPress={() => Alert.alert("Delete publication?", `Delete “${publication.title}”? This cannot be undone.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void remove(publication) }])} disabled={saving}><Text style={styles.deleteText}>Delete</Text></TouchableOpacity></View></View>)}</ScrollView>;
}
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean; autoCapitalize?: "none"; keyboardType?: "url" }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
function PublicationUpload({ publication, disabled, onUploaded, onError, onUnauthorized }: { publication: Publication; disabled: boolean; onUploaded: () => Promise<void>; onError: (message: string) => void; onUnauthorized: () => Promise<void> }) { const [uploading, setUploading] = useState(false); const upload = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "image/jpeg", "image/png"], copyToCacheDirectory: true }); if (result.canceled) return; const file = result.assets[0]; if (!file || (file.size !== undefined && file.size > 10 * 1024 * 1024)) { onError("Choose a PDF, DOCX, JPG, or PNG file no larger than 10 MB."); return; } try { setUploading(true); onError(""); await uploadMyPublicationFile(publication.id, { uri: file.uri, name: file.name, mimeType: file.mimeType || "application/pdf" }); await onUploaded(); Toast.show({ type: "success", text1: "Publication file uploaded" }); } catch (error) { onError(getPublicationErrorMessage(error)); if (isUnauthorizedPublicationError(error)) await onUnauthorized(); } finally { setUploading(false); } }; return <TouchableOpacity style={styles.edit} onPress={() => void upload()} disabled={disabled || uploading}><Text style={styles.editText}>{uploading ? "Uploading…" : "Upload file"}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ loading:ui.centered,container:ui.screen,content:ui.screenContent,back:{alignSelf:"flex-start",marginBottom:spacing.lg},backText:ui.textButton,title:typography.screenTitle,subtitle:{...typography.caption,fontSize:16,marginTop:spacing.xs,marginBottom:spacing.xl},section:{...typography.sectionTitle,marginBottom:spacing.md},form:{...ui.card,marginBottom:spacing.xl},group:{marginBottom:spacing.md},label:{color:colors.text,fontSize:14,fontWeight:"700",marginBottom:spacing.sm},input:ui.input,multiline:{minHeight:104},save:ui.primaryButton,saveText:ui.primaryButtonText,cancel:{...ui.outlineButton,marginTop:spacing.sm,borderColor:colors.textMuted},cancelText:{...ui.outlineButtonText,color:colors.textMuted},disabled:ui.disabled,errorBox:{...ui.errorState,...ui.card,marginBottom:spacing.lg},error:{color:colors.error,textAlign:"center",marginBottom:spacing.sm},retry:ui.outlineButton,retryText:ui.outlineButtonText,empty:{...ui.emptyState,...ui.card},emptyTitle:typography.cardTitle,emptyText:typography.caption,card:{...ui.card,marginBottom:spacing.md},cardTitle:typography.cardTitle,authors:{color:colors.primary,fontWeight:"700",marginTop:spacing.xs},details:{...typography.caption,marginTop:spacing.sm},url:{color:colors.primary,fontSize:14,marginTop:spacing.sm},abstract:{...typography.body,color:colors.textMuted,marginTop:spacing.md},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.lg},edit:{borderWidth:1,borderColor:colors.primary,borderRadius:radius.md,paddingHorizontal:spacing.md,paddingVertical:10},editText:{color:colors.primary,fontWeight:"700"},delete:{borderWidth:1,borderColor:colors.error,borderRadius:radius.md,paddingHorizontal:spacing.md,paddingVertical:10},deleteText:{color:colors.error,fontWeight:"700"} });
