import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { Announcement, getAnnouncement, getAnnouncementErrorMessage, isUnauthorizedAnnouncementError } from "../../services/announcement.service";

const typeLabel = (value: Announcement["announcement_type"]) => value === "academic" ? "Academic" : value === "assignment" ? "Assignment" : "General";
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";
export default function StudentAnnouncementDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const announcementId = Number(route.params?.announcementId); const [item, setItem] = useState<Announcement | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(announcementId) || announcementId < 1) { setError("The announcement could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Announcements are available to students and graduates only."); return; } setItem(await getAnnouncement(announcementId)); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [announcementId, resetForUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Announcement not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate("Announcements")}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} />}><TouchableOpacity onPress={() => navigation.navigate("Announcements")}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>CAMPUSX UPDATE</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.type}>{typeLabel(item.announcement_type)}</Text></View><Info label="Content" value={item.content} />{item.creator_name ? <Info label="Posted by" value={item.creator_name} /> : null}<Info label="Published" value={item.published_at ? item.published_at.slice(0, 10) : "Recently"} />{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { const isContent = label === "Content"; return <View style={[styles.info, isContent && styles.readingCard]}><Text style={styles.label}>{label}</Text><Text style={[styles.value, isContent && styles.readingValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{...ui.card,marginBottom:spacing.md,paddingVertical:spacing.xl,borderColor:colors.primary},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:28,lineHeight:35},type:{alignSelf:"flex-start",color:colors.primary,fontWeight:"700",backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs,marginTop:spacing.lg},info:{...ui.card,marginTop:spacing.md},readingCard:{backgroundColor:colors.backgroundElevated,paddingVertical:spacing.xl},label:{color:colors.text,fontSize:14,fontWeight:"800",letterSpacing:.2},value:{...typography.body,color:colors.textMuted,lineHeight:22,marginTop:spacing.sm},readingValue:{color:colors.text,lineHeight:25},errorBox:{...ui.errorState,...ui.card,marginTop:spacing.lg},error:{color:colors.error,textAlign:"center",lineHeight:21},retry:{...ui.textButton,marginTop:spacing.sm} });
