import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { Announcement, getAnnouncement, getAnnouncementErrorMessage, isUnauthorizedAnnouncementError } from "../../services/announcement.service";

const typeLabel = (value: Announcement["announcement_type"]) => value === "academic" ? "Academic" : value === "assignment" ? "Assignment" : "General";
const isApplicantRole = (role?: string) => role === "student" || role === "graduate";
export default function StudentAnnouncementDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const announcementId = Number(route.params?.announcementId); const [item, setItem] = useState<Announcement | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(announcementId) || announcementId < 1) { setError("The announcement could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !isApplicantRole(session.user.role)) { if (!session) await resetForUnauthorized(); else setError("Announcements are available to students and graduates only."); return; } setItem(await getAnnouncement(announcementId)); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [announcementId, resetForUnauthorized]);
  useEffect(() => { void load(); }, [load]);
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Announcement not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate("Announcements")}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}><TouchableOpacity onPress={() => navigation.navigate("Announcements")}><Text style={styles.back}>Back to Announcements</Text></TouchableOpacity><Text style={styles.title}>{item.title}</Text><Text style={styles.type}>{typeLabel(item.announcement_type)}</Text><Info label="Content" value={item.content} />{item.creator_name ? <Info label="Posted by" value={item.creator_name} /> : null}<Info label="Published" value={item.published_at ? item.published_at.slice(0, 10) : "Recently"} />{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24,backgroundColor:"#fff"},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:28,fontWeight:"bold",color:"#1E3A8A"},type:{color:"#2563EB",fontWeight:"600",marginTop:7},info:{marginTop:20},label:{color:"#333",fontWeight:"700"},value:{color:"#4B5563",lineHeight:22,marginTop:5},errorBox:{alignItems:"center",marginTop:18},error:{color:"#DC2626",textAlign:"center",lineHeight:21},retry:{color:"#2563EB",fontWeight:"700",marginTop:10} });
