import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { getTeamErrorMessage, getTeams, isUnauthorizedTeamError, Team } from "../../services/team.service";

const allowed = (role?: string) => role === "student" || role === "graduate";
export default function TeamsScreen() {
  const navigation = useNavigation<any>(); const [teams, setTeams] = useState<Team[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const reset = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || !allowed(session.user.role)) { if (!session) await reset(); else setError("Project Teams is available to students and graduates only."); return; } setTeams(await getTeams()); setError(""); } catch (error) { setError(getTeamErrorMessage(error)); if (isUnauthorizedTeamError(error)) await reset(); } finally { setLoading(false); setRefreshing(false); } }, [reset]);
  useEffect(() => { void load(); const remove = navigation.addListener("focus", () => void load()); return remove; }, [load, navigation]);
  if (loading) return <View style={s.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={s.back}>Back to Home</Text></TouchableOpacity><Text style={s.title}>Project Teams</Text><Text style={s.subtitle}>Collaborate on projects and track your team tasks.</Text><TouchableOpacity style={s.primary} onPress={() => navigation.navigate("CreateTeam")}><Text style={s.primaryText}>Create Team</Text></TouchableOpacity>{error ? <View style={s.errorBox}><Text style={s.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={s.retry}>Retry</Text></TouchableOpacity></View> : teams.length === 0 ? <View style={s.empty}><Text style={s.emptyTitle}>No project teams yet</Text><Text style={s.emptyText}>Create a team to begin collaborating with classmates.</Text></View> : teams.map((team) => <TouchableOpacity key={team.id} style={s.card} onPress={() => navigation.navigate("TeamDetails", { teamId: team.id })}><Text style={s.cardTitle}>{team.name}</Text>{team.description ? <Text style={s.description} numberOfLines={2}>{team.description}</Text> : null}<Text style={s.detail}>Project progress: {team.progress_percentage}%</Text><Text style={s.detail}>{team.member_count} members · {team.task_count} tasks</Text></TouchableOpacity>)}</ScrollView>;
}
const s = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",backgroundColor:"#fff"},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A"},subtitle:{color:"#666",fontSize:16,lineHeight:22,marginTop:6,marginBottom:18},primary:{backgroundColor:"#10B981",padding:14,borderRadius:10,alignItems:"center"},primaryText:{color:"#fff",fontSize:16,fontWeight:"700"},card:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:16,marginTop:12},cardTitle:{fontSize:18,fontWeight:"700",color:"#333"},description:{color:"#4B5563",lineHeight:21,marginTop:7},detail:{color:"#2563EB",marginTop:7,fontWeight:"600"},empty:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:18,marginTop:16},emptyTitle:{fontSize:18,fontWeight:"700",color:"#333",marginBottom:6},emptyText:{color:"#666",lineHeight:22},errorBox:{alignItems:"center",padding:18,marginTop:16},error:{color:"#DC2626",textAlign:"center",lineHeight:21},retry:{color:"#2563EB",fontWeight:"700",marginTop:10} });
