import { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { getAdminOpportunities } from "../../services/admin-opportunity.service";
import { Opportunity, OpportunityStatus, OpportunityType } from "../../services/opportunity.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: OpportunityType[] = ["internship", "job", "ra", "ta", "research"];
const statuses: OpportunityStatus[] = ["draft", "published", "closed"];
export default function AdminOpportunitiesScreen() {
  const navigation = useNavigation<any>(); const [items,setItems] = useState<Opportunity[]>([]); const [search,setSearch] = useState(""); const [type,setType] = useState<OpportunityType | undefined>(); const [status,setStatus] = useState<OpportunityStatus | undefined>(); const [error,setError] = useState(""); const [loading,setLoading] = useState(true);
  const load = async () => { try { setLoading(true); setItems(await getAdminOpportunities({ search: search || undefined, opportunity_type: type, status })); setError(""); } catch { setError("Unable to load opportunities."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  if (loading) return <View style={ui.centered}><ActivityIndicator color={colors.primary} size="large" /><Text style={styles.loading}>Loading opportunities…</Text></View>;
  return <ScrollView style={ui.screen} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity><Text style={typography.screenTitle}>Opportunity Management</Text><Text style={styles.subtitle}>Review and manage CampusX opportunity listings.</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search opportunities" placeholderTextColor={colors.textMuted} onSubmitEditing={() => void load()} style={styles.input}/><Text style={styles.filterLabel}>TYPE</Text><View style={styles.filterRow}>{types.map(value => <TouchableOpacity key={value} onPress={() => setType(type === value ? undefined : value)} style={[styles.chip,type === value && styles.activeChip]}><Text style={[styles.chipText,type === value && styles.activeChipText]}>{value}</Text></TouchableOpacity>)}</View><Text style={styles.filterLabel}>STATUS</Text><View style={styles.filterRow}>{statuses.map(value => <TouchableOpacity key={value} onPress={() => setStatus(status === value ? undefined : value)} style={[styles.chip,status === value && styles.activeChip]}><Text style={[styles.chipText,status === value && styles.activeChipText]}>{value}</Text></TouchableOpacity>)}</View><TouchableOpacity onPress={() => void load()} style={ui.primaryButton}><Text style={ui.primaryButtonText}>Apply Filters</Text></TouchableOpacity>{error ? <Text style={styles.error}>{error}</Text> : items.length === 0 ? <View style={styles.empty}><Text style={styles.emptyText}>No opportunities match the current filters.</Text></View> : items.map(item => <TouchableOpacity key={item.id} onPress={() => navigation.navigate("AdminOpportunityDetails", { opportunityId:item.id })} style={styles.card}><View style={styles.cardTop}><Text style={styles.cardTitle}>{item.title}</Text><Text style={[styles.status,item.status === "published" && styles.published,item.status === "closed" && styles.closed]}>{item.status}</Text></View><Text style={styles.meta}>{item.opportunity_type} · {item.is_remote ? "Remote" : "On-site"}{item.location ? ` · ${item.location}` : ""}</Text><Text style={styles.detail}>{item.company_name || "CampusX"} · {item.deadline}</Text><Text style={styles.view}>View details</Text></TouchableOpacity>)}</ScrollView>;
}
const styles = StyleSheet.create({ content:{...ui.screenContent},loading:{...typography.caption,marginTop:spacing.md},back:{color:colors.primary,fontWeight:"700",marginBottom:spacing.md},subtitle:{...typography.caption,marginTop:spacing.xs,marginBottom:spacing.lg},input:{...ui.input,marginBottom:spacing.md},filterLabel:{color:colors.textMuted,fontSize:10,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},filterRow:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginBottom:spacing.md},chip:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},activeChip:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{color:colors.textMuted,fontWeight:"700",textTransform:"capitalize"},activeChipText:{color:colors.onPrimary},card:{...ui.card,marginTop:spacing.md},cardTop:{flexDirection:"row",gap:spacing.sm,justifyContent:"space-between"},cardTitle:{...typography.cardTitle,flex:1},status:{color:colors.secondary,backgroundColor:"#292750",paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill,fontSize:11,fontWeight:"800",textTransform:"capitalize",overflow:"hidden"},published:{color:colors.success,backgroundColor:"#123A34"},closed:{color:colors.warning,backgroundColor:"#3B301A"},meta:{color:colors.info,fontSize:13,fontWeight:"700",marginTop:spacing.md,textTransform:"capitalize"},detail:{color:colors.textMuted,fontSize:13,marginTop:spacing.sm},view:{color:colors.primary,fontSize:13,fontWeight:"800",marginTop:spacing.md},error:{color:colors.error,textAlign:"center",marginTop:spacing.lg},empty:{...ui.emptyState},emptyText:{...typography.caption,textAlign:"center"} });
