import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import axios from "axios";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { companyError, Company, getAdminCompanies } from "../../services/company.service";

const label = (status?: Company["approval_status"]) => status === "approved" ? "Approved" : status === "rejected" ? "Rejected" : "Pending";
export default function AdminCompaniesScreen() {
  const navigation = useNavigation<any>(); const [items, setItems] = useState<Company[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const handleError = useCallback(async (requestError: unknown) => { if (axios.isAxiosError(requestError) && requestError.response?.status === 401) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); return; } setError(companyError(requestError)); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (session?.user.role !== "admin") { setError("Administrator access is required to manage companies."); return; } setItems(await getAdminCompanies()); setError(""); } catch (requestError) { await handleError(requestError); } finally { setLoading(false); setRefreshing(false); } }, [handleError]);
  useEffect(() => { load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity><Text style={styles.title}>Manage Companies</Text>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.back}>Retry</Text></TouchableOpacity></View> : null}{!error && items.length === 0 ? <Text style={styles.empty}>No companies have been created yet.</Text> : null}{items.map((item) => <TouchableOpacity key={item.id} style={styles.card} onPress={() => navigation.navigate("AdminCompanyDetails", { companyId: item.id })}><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{item.location || "No location"}</Text>{item.website ? <Text style={styles.detail}>{item.website}</Text> : null}<Text style={[styles.status, item.approval_status === "rejected" && styles.rejected]}>{label(item.approval_status)}</Text></TouchableOpacity>)}</ScrollView>;
}
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 30, fontWeight: "bold", color: "#1E3A8A", marginBottom: 18 }, errorBox: { alignItems: "center", marginVertical: 16 }, error: { color: "#DC2626", textAlign: "center", marginBottom: 10 }, empty: { color: "#666", fontSize: 16, textAlign: "center", marginTop: 24 }, card: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 10, padding: 16, marginBottom: 12 }, name: { fontSize: 18, fontWeight: "700", color: "#333" }, detail: { color: "#4B5563", marginTop: 6 }, status: { color: "#047857", fontWeight: "700", marginTop: 8 }, rejected: { color: "#DC2626" } });
