import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import axios from "axios";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { company, companyError, Company, updateCompanyApproval } from "../../services/company.service";

const label = (status?: Company["approval_status"]) => status === "approved" ? "Approved" : status === "rejected" ? "Rejected" : "Pending";

export default function AdminCompanyDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const companyId = Number(route.params?.companyId);
  const [item, setItem] = useState<Company | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const handleError = useCallback(async (requestError: unknown) => { if (axios.isAxiosError(requestError) && requestError.response?.status === 401) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); return; } setError(companyError(requestError)); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(companyId) || companyId <= 0) { setError("The company could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (session?.user.role !== "admin") { setError("Administrator access is required to manage companies."); return; } setItem(await company(companyId)); setError(""); } catch (requestError) { await handleError(requestError); } finally { setLoading(false); setRefreshing(false); } }, [companyId, handleError]);
  useEffect(() => { load(); }, [load]);
  const updateApproval = async (approval_status: "approved" | "rejected") => { try { setWorking(true); setError(""); await updateCompanyApproval(companyId, approval_status); await load(); Toast.show({ type: "success", text1: approval_status === "approved" ? "Company approved" : "Company rejected" }); } catch (requestError) { await handleError(requestError); } finally { setWorking(false); } };
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Company not found."}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.back}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Companies</Text></TouchableOpacity></View>;
  const canApprove = item.approval_status !== "approved"; const canReject = item.approval_status !== "rejected";
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Companies</Text></TouchableOpacity><Text style={styles.title}>{item.name}</Text><Text style={[styles.status, item.approval_status === "rejected" && styles.rejected]}>{label(item.approval_status)}</Text>{item.logo ? <Image source={{ uri: item.logo }} style={styles.logo} resizeMode="contain" /> : null}<Info label="Description" value={item.description || "Not provided"} /><Info label="Website" value={item.website || "Not provided"} /><Info label="Location" value={item.location || "Not provided"} />{item.created_at ? <Info label="Created" value={item.created_at.slice(0, 10)} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{canApprove ? <TouchableOpacity style={[styles.approve, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Approve company?", "This will make the company available to recruiters.", [{ text: "Cancel", style: "cancel" }, { text: "Approve", onPress: () => void updateApproval("approved") }])}><Text style={styles.approveText}>{working ? "Saving…" : "Approve"}</Text></TouchableOpacity> : null}{canReject ? <TouchableOpacity style={[styles.reject, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Reject company?", "This will mark the company as rejected.", [{ text: "Cancel", style: "cancel" }, { text: "Reject", style: "destructive", onPress: () => void updateApproval("rejected") }])}><Text style={styles.rejectText}>{working ? "Saving…" : "Reject"}</Text></TouchableOpacity> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 28, fontWeight: "bold", color: "#1E3A8A" }, status: { color: "#047857", fontWeight: "700", marginTop: 8 }, rejected: { color: "#DC2626" }, logo: { width: "100%", height: 120, marginTop: 18, borderRadius: 10, backgroundColor: "#F3F4F6" }, info: { marginTop: 20 }, label: { color: "#333", fontWeight: "700" }, value: { color: "#4B5563", marginTop: 5, lineHeight: 22 }, approve: { backgroundColor: "#10B981", borderRadius: 10, padding: 14, alignItems: "center", marginTop: 28 }, approveText: { color: "#fff", fontWeight: "700" }, reject: { borderWidth: 1, borderColor: "#DC2626", borderRadius: 10, padding: 14, alignItems: "center", marginTop: 12 }, rejectText: { color: "#DC2626", fontWeight: "700" }, disabled: { opacity: 0.6 }, error: { color: "#DC2626", textAlign: "center", marginTop: 18 } });
