import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import axios from "axios";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { company, companyError, Company, updateCompanyApproval } from "../../services/company.service";

const label = (status?: Company["approval_status"]) => status === "approved" ? "Approved" : status === "rejected" ? "Rejected" : "Pending";

export default function AdminCompanyDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const companyId = Number(route.params?.companyId);
  const [item, setItem] = useState<Company | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const handleError = useCallback(async (requestError: unknown) => { if (axios.isAxiosError(requestError) && requestError.response?.status === 401) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); return; } setError(companyError(requestError)); }, [navigation]);
  const load = useCallback(async (refresh = false) => { if (!Number.isInteger(companyId) || companyId <= 0) { setError("The company could not be found."); setLoading(false); return; } refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (session?.user.role !== "admin") { setError("Administrator access is required to manage companies."); return; } setItem(await company(companyId)); setError(""); } catch (requestError) { await handleError(requestError); } finally { setLoading(false); setRefreshing(false); } }, [companyId, handleError]);
  useEffect(() => { load(); }, [load]);
  const updateApproval = async (approval_status: "approved" | "rejected") => { try { setWorking(true); setError(""); await updateCompanyApproval(companyId, approval_status); await load(); Toast.show({ type: "success", text1: approval_status === "approved" ? "Company approved" : "Company rejected" }); } catch (requestError) { await handleError(requestError); } finally { setWorking(false); } };
  if (loading && !item) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  if (!item) return <View style={styles.center}><Text style={styles.error}>{error || "Company not found."}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.back}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Companies</Text></TouchableOpacity></View>;
  const canApprove = item.approval_status !== "approved"; const canReject = item.approval_status !== "rejected";
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.primary} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Companies</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>COMPANY REVIEW</Text><Text style={styles.title}>{item.name}</Text><Text style={[styles.status, item.approval_status === "rejected" && styles.rejected]}>{label(item.approval_status)}</Text></View>{item.logo ? <Image source={{ uri: item.logo }} style={styles.logo} resizeMode="contain" /> : null}<Info label="Description" value={item.description || "Not provided"} /><Info label="Website" value={item.website || "Not provided"} /><Info label="Location" value={item.location || "Not provided"} />{item.created_at ? <Info label="Created" value={item.created_at.slice(0, 10)} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{canApprove ? <TouchableOpacity style={[styles.approve, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Approve company?", "This will make the company available to recruiters.", [{ text: "Cancel", style: "cancel" }, { text: "Approve", onPress: () => void updateApproval("approved") }])}><Text style={styles.approveText}>{working ? "Saving…" : "Approve"}</Text></TouchableOpacity> : null}{canReject ? <TouchableOpacity style={[styles.reject, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Reject company?", "This will mark the company as rejected.", [{ text: "Cancel", style: "cancel" }, { text: "Reject", style: "destructive", onPress: () => void updateApproval("rejected") }])}><Text style={styles.rejectText}>{working ? "Saving…" : "Reject"}</Text></TouchableOpacity> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { const isDescription = label === "Description"; return <View style={[styles.info, isDescription && styles.readingCard]}><Text style={styles.label}>{label}</Text><Text style={[styles.value, isDescription && styles.readingValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{...ui.card,paddingVertical:spacing.xl,borderColor:colors.primary},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:28,lineHeight:35},status:{alignSelf:"flex-start",color:colors.success,fontWeight:"700",marginTop:spacing.md,backgroundColor:colors.surfaceRaised,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},rejected:{color:colors.error},logo:{width:"100%",height:120,marginTop:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surface},info:{...ui.card,marginTop:spacing.md},readingCard:{backgroundColor:colors.backgroundElevated,paddingVertical:spacing.xl},label:{color:colors.text,fontSize:14,fontWeight:"800",letterSpacing:.2},value:{...typography.body,color:colors.textMuted,marginTop:spacing.sm,lineHeight:22},readingValue:{color:colors.text,lineHeight:25},approve:{...ui.primaryButton,marginTop:spacing.xl},approveText:ui.primaryButtonText,reject:{...ui.outlineButton,marginTop:spacing.sm,borderColor:colors.error},rejectText:{...ui.outlineButtonText,color:colors.error},disabled:ui.disabled,error:{color:colors.error,textAlign:"center",marginTop:spacing.lg} });
