import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { Announcement, getAnnouncementErrorMessage, getAnnouncements, isUnauthorizedAnnouncementError } from "../../services/announcement.service";

const label = (value: string) => value === "all" ? "All users" : value.charAt(0).toUpperCase() + value.slice(1);
export default function AdminAnnouncementsScreen() {
  const navigation = useNavigation<any>(); const [items, setItems] = useState<Announcement[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || session.user.role !== "admin") { if (!session) await resetForUnauthorized(); else setError("Administrator access is required to manage announcements."); return; } setItems(await getAnnouncements()); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity><Text style={styles.title}>Manage Announcements</Text><Text style={styles.subtitle}>Manage faculty and platform-wide announcement visibility.</Text><TouchableOpacity style={styles.create} onPress={() => navigation.navigate("AdminCreateAnnouncement")}><Text style={styles.createText}>Create Announcement</Text></TouchableOpacity>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity></View> : null}{!error && items.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No announcements yet</Text><Text style={styles.emptyText}>Create an announcement for a selected CampusX audience.</Text></View> : null}{items.map((item) => <TouchableOpacity key={item.id} style={styles.card} onPress={() => navigation.navigate("AdminAnnouncementDetails", { announcementId: item.id })}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.type}>{label(item.announcement_type)} · {label(item.audience)}</Text><Text style={styles.status}>{label(item.status)}{item.published_at ? ` · ${item.published_at.slice(0, 10)}` : ""}</Text><Text style={styles.preview} numberOfLines={2}>{item.content}</Text>{item.creator_name ? <Text style={styles.creator}>Created by {item.creator_name}</Text> : null}</TouchableOpacity>)}</ScrollView>;
}
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A"},subtitle:{color:"#666",fontSize:16,lineHeight:22,marginTop:6,marginBottom:18},create:{backgroundColor:"#10B981",padding:14,borderRadius:10,alignItems:"center",marginBottom:18},createText:{color:"#fff",fontWeight:"700",fontSize:16},errorBox:{alignItems:"center",marginVertical:16},error:{color:"#DC2626",textAlign:"center",marginBottom:10},empty:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:18},emptyTitle:{color:"#333",fontSize:18,fontWeight:"700",marginBottom:6},emptyText:{color:"#666",lineHeight:22},card:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:16,marginTop:12},cardTitle:{fontSize:18,fontWeight:"700",color:"#333"},type:{color:"#2563EB",fontWeight:"600",marginTop:5},status:{color:"#047857",fontWeight:"700",marginTop:6},preview:{color:"#4B5563",marginTop:8,lineHeight:21},creator:{color:"#6B7280",marginTop:8,fontSize:13} });
