import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { getAdminUser, AdminUserDetail, adminUserError } from "../../services/admin-user.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

export default function AdminUserDetailsScreen() {
  const navigation = useNavigation<any>();
  const route = useRoute<any>();
  const [user, setUser] = useState<AdminUserDetail | null>(null);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); setUser(await getAdminUser(Number(route.params?.userId))); } catch (requestError) { setError(adminUserError(requestError)); } }, [route.params?.userId]);
  useEffect(() => { void load(); }, [load]);
  if (!user) return <View style={ui.centered}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></> : <><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loading}>Loading user…</Text></>}</View>;
  const records: Array<[string, number]> = [["Skills", user.skills_count], ["Resumes", user.resumes_count], ["Certificates", user.certificates_count], ["Projects", user.projects_count], ["Publications", user.publications_count], ["Applications", user.applications_count], ["Opportunities", user.opportunities_count]];
  return <ScrollView style={ui.screen} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Users</Text></TouchableOpacity><View style={styles.hero}><View style={styles.avatar}><Text style={styles.initials}>{user.full_name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</Text></View><View style={styles.heroCopy}><Text style={styles.name}>{user.full_name}</Text><Text style={styles.email}>{user.email}</Text><View style={styles.roleBadge}><Text style={styles.role}>{user.role}</Text></View></View></View><View style={styles.infoCard}><Info label="Account created" value={user.created_at} /></View><Text style={styles.sectionTitle}>Related records</Text><View style={styles.grid}>{records.map(([label, value]) => <View key={label} style={styles.stat}><Text style={styles.value}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View></ScrollView>;
}

function Info({ label, value }: { label: string; value: string }) { return <View style={styles.infoRow}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>; }

const styles = StyleSheet.create({ content: { ...ui.screenContent }, back: { ...ui.textButton, marginBottom: spacing.lg }, loading: { ...typography.caption, marginTop: spacing.md }, error: { color: colors.error, textAlign: "center" }, retry: { ...ui.textButton, marginTop: spacing.md }, hero: { ...ui.card, flexDirection: "row", alignItems: "center", gap: spacing.md, marginBottom: spacing.md, borderColor: colors.primary }, avatar: { width: 58, height: 58, borderRadius: radius.pill, alignItems: "center", justifyContent: "center", backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.secondary }, initials: { color: colors.secondary, fontSize: 19, fontWeight: "800" }, heroCopy: { flex: 1 }, name: { ...typography.cardTitle }, email: { ...typography.caption, marginTop: spacing.xs }, roleBadge: { ...ui.badge, backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border, marginTop: spacing.sm }, role: { color: colors.primary, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, infoCard: { ...ui.card }, infoRow: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md }, infoLabel: { color: colors.textMuted, fontWeight: "700" }, infoValue: { color: colors.text, flexShrink: 1, textAlign: "right" }, sectionTitle: { ...typography.sectionTitle, marginTop: spacing.xl, marginBottom: spacing.md }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, stat: { width: "48%", minHeight: 92, borderRadius: radius.md, padding: spacing.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, justifyContent: "space-between" }, value: { color: colors.secondary, fontSize: 25, fontWeight: "800" }, statLabel: { color: colors.textMuted, fontSize: 12, fontWeight: "700", marginTop: spacing.sm }, });
