import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { createThesisMilestone, deleteThesisMilestone, getThesisMilestones, ThesisMilestone, updateThesisMilestone, thesisError } from "../../services/thesis-milestone.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const blank: { title: string; description: string; due_date: string; status: ThesisMilestone["status"]; progress_percentage: string } = { title: "", description: "", due_date: "", status: "pending", progress_percentage: "0" };

const statusStyle = (status: ThesisMilestone["status"]) => status === "completed" ? styles.completed : status === "in_progress" ? styles.inProgress : styles.pending;

export default function ThesisMilestonesScreen() {
  const navigation = useNavigation<any>();
  const [items, setItems] = useState<ThesisMilestone[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setLoading(true); setItems(await getThesisMilestones()); setError(""); } catch (caughtError) { setError(thesisError(caughtError)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const progress = Number(form.progress_percentage); if (!form.title.trim() || !/^\d{4}-\d{2}-\d{2}$/.test(form.due_date) || !Number.isInteger(progress) || progress < 0 || progress > 100) { setError("Enter a title, due date (YYYY-MM-DD), and progress from 0 to 100."); return; } try { setSaving(true); const data = { title: form.title.trim(), description: form.description.trim() || null, due_date: form.due_date, status: form.status, progress_percentage: progress }; if (editing) await updateThesisMilestone(editing, data); else await createThesisMilestone(data); setForm(blank); setEditing(null); await load(); } catch (caughtError) { setError(thesisError(caughtError)); } finally { setSaving(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  const overallProgress = items.length ? Math.round(items.reduce((total, item) => total + item.progress_percentage, 0) / items.length) : 0;

  return <ScrollView style={ui.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity>
    <Text style={styles.title}>Thesis Milestones</Text><Text style={styles.subtitle}>Plan your research work and keep your graduate progress visible.</Text>
    {items.length ? <View style={styles.overallCard}><View style={styles.overallHeader}><View><Text style={styles.cardEyebrow}>RESEARCH PROGRESS</Text><Text style={styles.overallTitle}>Your current milestone progress</Text></View><Text style={styles.overallPercent}>{overallProgress}%</Text></View><View style={ui.progressTrack}><View style={[ui.progressFill, { width: `${overallProgress}%` }]} /></View><Text style={styles.overallCaption}>{items.length} {items.length === 1 ? "milestone" : "milestones"} tracked</Text></View> : null}
    <Text style={styles.sectionTitle}>{editing ? "Edit milestone" : "Add a milestone"}</Text>
    <View style={styles.formCard}><TextInput style={[ui.input, styles.input]} placeholder="Milestone title" placeholderTextColor={colors.textMuted} value={form.title} onChangeText={(title) => setForm({ ...form, title })} /><TextInput style={[ui.input, styles.input, styles.area]} placeholder="Description (optional)" placeholderTextColor={colors.textMuted} multiline value={form.description} onChangeText={(description) => setForm({ ...form, description })} /><TextInput style={[ui.input, styles.input]} placeholder="Due date (YYYY-MM-DD)" placeholderTextColor={colors.textMuted} value={form.due_date} onChangeText={(due_date) => setForm({ ...form, due_date })} /><TextInput style={[ui.input, styles.input]} placeholder="Progress (0-100)" placeholderTextColor={colors.textMuted} keyboardType="number-pad" value={form.progress_percentage} onChangeText={(progress_percentage) => setForm({ ...form, progress_percentage })} /><View style={styles.choices}>{(["pending", "in_progress", "completed"] as const).map((status) => <TouchableOpacity key={status} style={[styles.choice, form.status === status && styles.selected]} onPress={() => setForm({ ...form, status })}><Text style={form.status === status ? styles.selectedText : styles.choiceText}>{status.replace("_", " ")}</Text></TouchableOpacity>)}</View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[ui.primaryButton, saving && ui.disabled]} disabled={saving} onPress={() => void save()}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text style={ui.primaryButtonText}>{editing ? "Save Milestone" : "Add Milestone"}</Text>}</TouchableOpacity>{editing ? <TouchableOpacity onPress={() => { setEditing(null); setForm(blank); }}><Text style={styles.cancel}>Cancel editing</Text></TouchableOpacity> : null}</View>
    <Text style={styles.sectionTitle}>Your milestones</Text>
    {items.length === 0 ? <View style={styles.emptyState}><Text style={styles.emptyTitle}>No thesis milestones yet</Text><Text style={styles.emptyText}>Add your first research milestone to begin tracking progress.</Text></View> : items.map((item) => <View key={item.id} style={styles.card}><View style={styles.cardHeader}><Text style={styles.cardTitle}>{item.title}</Text><View style={[styles.statusBadge, statusStyle(item.status)]}><Text style={styles.statusText}>{item.status.replace("_", " ")}</Text></View></View><Text style={styles.due}>Due {item.due_date.slice(0, 10)}</Text>{item.description ? <Text style={styles.description}>{item.description}</Text> : null}<View style={styles.progressHeader}><Text style={styles.progressLabel}>Milestone progress</Text><Text style={styles.progressValue}>{item.progress_percentage}%</Text></View><View style={ui.progressTrack}><View style={[ui.progressFill, { width: `${Math.max(0, Math.min(100, item.progress_percentage))}%` }]} /></View><View style={styles.actions}><TouchableOpacity onPress={() => { setEditing(item.id); setForm({ title: item.title, description: item.description || "", due_date: item.due_date.slice(0, 10), status: item.status, progress_percentage: String(item.progress_percentage) }); }}><Text style={styles.edit}>Edit</Text></TouchableOpacity><TouchableOpacity onPress={() => Alert.alert("Delete milestone?", item.title, [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => void deleteThesisMilestone(item.id).then(load).catch((caughtError) => setError(thesisError(caughtError))) }])}><Text style={styles.delete}>Delete</Text></TouchableOpacity></View></View>)}
  </ScrollView>;
}

const styles = StyleSheet.create({
  center: { ...ui.centered }, content: { padding: spacing.xl, paddingBottom: 48 }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.lg }, title: { ...typography.screenTitle }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl }, sectionTitle: { ...typography.sectionTitle, fontSize: 19, marginTop: spacing.xl, marginBottom: spacing.md },
  overallCard: { ...ui.card, backgroundColor: colors.surfaceRaised }, overallHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md, marginBottom: spacing.lg }, cardEyebrow: { color: colors.secondary, fontSize: 11, fontWeight: "800", letterSpacing: 1 }, overallTitle: { ...typography.cardTitle, marginTop: spacing.xs }, overallPercent: { color: colors.primary, fontSize: 28, fontWeight: "800" }, overallCaption: { ...typography.caption, marginTop: spacing.md },
  formCard: { ...ui.card }, input: { ...typography.input, marginBottom: spacing.md }, area: { minHeight: 92, textAlignVertical: "top" }, choices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.lg }, choice: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, backgroundColor: colors.backgroundElevated }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.textMuted, fontSize: 12, fontWeight: "700", textTransform: "capitalize" }, selectedText: { color: colors.onPrimary, fontSize: 12, fontWeight: "800", textTransform: "capitalize" }, error: { color: colors.error, textAlign: "center", marginBottom: spacing.md }, cancel: { color: colors.primary, fontWeight: "700", textAlign: "center", marginTop: spacing.md },
  emptyState: { ...ui.emptyState, ...ui.card }, emptyTitle: { ...typography.cardTitle, marginBottom: spacing.xs }, emptyText: { ...typography.caption, textAlign: "center" }, card: { ...ui.card, marginBottom: spacing.md }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, cardTitle: { ...typography.cardTitle, flex: 1 }, statusBadge: { ...ui.badge }, statusText: { color: colors.text, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, pending: { backgroundColor: "#3D341D", borderWidth: 1, borderColor: colors.warning }, inProgress: { backgroundColor: "#183755", borderWidth: 1, borderColor: colors.info }, completed: { backgroundColor: "#123D3C", borderWidth: 1, borderColor: colors.success }, due: { color: colors.warning, fontSize: 13, fontWeight: "700", marginTop: spacing.sm }, description: { ...typography.caption, marginTop: spacing.sm }, progressHeader: { flexDirection: "row", justifyContent: "space-between", marginTop: spacing.lg, marginBottom: spacing.sm }, progressLabel: { color: colors.textMuted, fontSize: 12, fontWeight: "700" }, progressValue: { color: colors.primary, fontSize: 13, fontWeight: "800" }, actions: { flexDirection: "row", gap: spacing.lg, marginTop: spacing.lg, paddingTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider }, edit: { color: colors.primary, fontWeight: "800" }, delete: { color: colors.error, fontWeight: "800" },
});
