import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { getProfile, getProfileErrorMessage } from "../../services/profile.service";
import { createOpportunity, getOpportunityErrorMessage, isUnauthorizedOpportunityError, OpportunityInput, OpportunityType } from "../../services/opportunity.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: Array<["job" | "internship", string]> = [["job", "Job"], ["internship", "Internship"]];
const initial = { title: "", description: "", opportunity_type: "job" as OpportunityType, deadline: "", location: "", is_remote: false };
const validate = (form: typeof initial) => !form.title.trim() ? "Title is required." : !form.description.trim() ? "Description is required." : !types.some(([type]) => type === form.opportunity_type) ? "Select Job or Internship." : !/^\d{4}-\d{2}-\d{2}$/.test(form.deadline) || new Date(`${form.deadline}T23:59:59`).getTime() < Date.now() ? "Deadline must be a current or future date in YYYY-MM-DD format." : "";

export default function CreateRecruiterOpportunityScreen() {
  const navigation = useNavigation<any>(); const [form, setForm] = useState(initial); const [companyId, setCompanyId] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const loadCompany = useCallback(async () => { try { setLoading(true); const profile = await getProfile(); const recruiter = profile.recruiter_profile; if (profile.user.role !== "recruiter") setError("Recruiter access is required."); else if (!recruiter || recruiter.company_approval_status !== "approved") setError("You need an approved company before creating a Job or Internship."); else { setCompanyId(recruiter.company_id); setError(""); } } catch (requestError) { setError(getProfileErrorMessage(requestError)); if (isUnauthorizedOpportunityError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); } }, [resetForUnauthorized]);
  useEffect(() => { loadCompany(); }, [loadCompany]);
  const update = <K extends keyof typeof initial>(key: K, value: typeof initial[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { const validation = validate(form); if (validation) { setError(validation); return; } if (!companyId) { setError("You need an approved company before creating a Job or Internship."); return; } try { setSaving(true); setError(""); const input: OpportunityInput = { ...form, title: form.title.trim(), description: form.description.trim(), location: form.location.trim() || null, company_id: companyId }; const opportunity = await createOpportunity(input); Toast.show({ type: "success", text1: "Draft created", text2: "Publish it when it is ready." }); navigation.replace("RecruiterOpportunityDetails", { opportunityId: opportunity.id }); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); if (isUnauthorizedOpportunityError(requestError)) await resetForUnauthorized(); } finally { setSaving(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  if (!companyId) return <View style={styles.center}><Text style={styles.error}>{error || "You need an approved company before creating a Job or Internship."}</Text><TouchableOpacity onPress={() => navigation.navigate("RecruiterProfile")}><Text style={styles.back}>Go to Recruiter Profile</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.navigate("SelectCompany")}><Text style={styles.back}>Select Company</Text></TouchableOpacity><TouchableOpacity onPress={loadCompany}><Text style={styles.back}>Retry</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Jobs & Internships</Text></TouchableOpacity><Text style={styles.title}>Create Job or Internship</Text><Field label="Title" value={form.title} onChangeText={(value) => update("title", value)} /><Field label="Description" value={form.description} multiline onChangeText={(value) => update("description", value)} /><Text style={styles.label}>Opportunity type</Text><View style={styles.types}>{types.map(([type, label]) => <TouchableOpacity key={type} style={[styles.type, form.opportunity_type === type && styles.selected]} onPress={() => update("opportunity_type", type)}><Text style={form.opportunity_type === type ? styles.selectedText : styles.typeText}>{label}</Text></TouchableOpacity>)}</View><Field label="Deadline (YYYY-MM-DD)" value={form.deadline} placeholder="2027-12-31" onChangeText={(value) => update("deadline", value)} /><Field label="Location (optional)" value={form.location} onChangeText={(value) => update("location", value)} /><View style={styles.remote}><Text style={styles.label}>Remote opportunity</Text><Switch value={form.is_remote} onValueChange={(value) => update("is_remote", value)} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.submit, saving && styles.disabled]} disabled={saving} onPress={submit}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.submitText}>Save Draft</Text>}</TouchableOpacity></ScrollView>;
}
function Field({ label, multiline = false, ...props }: { label: string; value: string; placeholder?: string; multiline?: boolean; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
const styles = StyleSheet.create({ center: { ...ui.centered }, page: { ...ui.screen }, content: { ...ui.screenContent }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.md }, title: { ...typography.screenTitle, marginBottom: spacing.xl }, field: { marginBottom: spacing.md }, label: { color: colors.text, fontWeight: "700", marginBottom: spacing.xs }, input: { ...ui.input }, multiline: { minHeight: 110, textAlignVertical: "top" }, types: { gap: spacing.sm, marginBottom: spacing.md }, type: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, typeText: { color: colors.textMuted, fontWeight: "700" }, selectedText: { color: colors.onPrimary, fontWeight: "800" }, remote: { ...ui.card, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing.lg }, error: { color: colors.error, marginBottom: spacing.md, textAlign: "center" }, submit: { ...ui.primaryButton }, submitText: { ...ui.primaryButtonText }, disabled: { ...ui.disabled } });
