import { useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { companyError, createCompany } from "../../services/company.service";

const isHttpUrl=(value:string)=>{try{const url=new URL(value);return url.protocol==="http:"||url.protocol==="https:"}catch{return false}};
export default function CreateCompanyScreen(){const navigation=useNavigation<any>();const[form,setForm]=useState({name:"",description:"",website:"",logo:"",location:""});const[error,setError]=useState("");const[saving,setSaving]=useState(false);const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));const submit=async()=>{const name=form.name.trim(),website=form.website.trim(),logo=form.logo.trim();if(!name||name.length>150)return setError("Company name is required and must be 150 characters or fewer.");if(form.description.length>5000)return setError("Description is too long.");if(form.location.length>150)return setError("Location must be 150 characters or fewer.");if(website&&!isHttpUrl(website))return setError("Website must be a valid HTTP or HTTPS URL.");if(logo&&!isHttpUrl(logo))return setError("Logo URL must be a valid HTTP or HTTPS URL.");try{setSaving(true);setError("");await createCompany({name,description:form.description.trim()||null,website:website||null,logo:logo||null,location:form.location.trim()||null});Toast.show({type:"success",text1:"Pending Admin Approval",text2:"Your company has been submitted for review."});navigation.goBack()}catch(requestError){setError(companyError(requestError))}finally{setSaving(false)}};return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={styles.back}>Back to Recruiter Profile</Text></TouchableOpacity><Text style={styles.title}>Create Company</Text><Text style={styles.note}>New companies remain pending until an administrator approves them.</Text>{(["name","description","website","logo","location"] as const).map(field=><TextInput key={field} style={[styles.input,field==="description"&&styles.multiline]} multiline={field==="description"} placeholder={{name:"Company Name",description:"Description",website:"Website",logo:"Logo URL",location:"Location"}[field]} value={form[field]} onChangeText={value=>set(field,value)} editable={!saving} autoCapitalize={field==="website"||field==="logo"?"none":"sentences"}/>) }{error?<Text style={styles.error}>{error}</Text>:null}<TouchableOpacity style={[styles.button,saving&&styles.disabled]} onPress={submit} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>Submit for Approval</Text>}</TouchableOpacity></ScrollView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"#fff"},content:{padding:24},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:28,fontWeight:"bold",color:"#1E3A8A"},note:{color:"#4B5563",marginTop:8,marginBottom:14},input:{borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:12,marginTop:10},multiline:{minHeight:100,textAlignVertical:"top"},error:{color:"#DC2626",marginTop:12},button:{backgroundColor:"#2563EB",borderRadius:10,padding:15,alignItems:"center",marginTop:16},buttonText:{color:"#fff",fontWeight:"700"},disabled:{opacity:.6}});
