import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { getOpportunity, getOpportunityErrorMessage, isUnauthorizedOpportunityError, OpportunityInput, OpportunityType, updateOpportunity } from "../../services/opportunity.service";

type Form = { title: string; description: string; opportunity_type: OpportunityType; deadline: string; location: string; is_remote: boolean };
const validTypes = new Set<OpportunityType>(["job", "internship"]);
const validate = (form: Form) => !form.title.trim() ? "Title is required." : !form.description.trim() ? "Description is required." : !validTypes.has(form.opportunity_type) ? "Only Job and Internship opportunities can be edited here." : !/^\d{4}-\d{2}-\d{2}$/.test(form.deadline) || new Date(`${form.deadline}T23:59:59`).getTime() < Date.now() ? "Deadline must be a current or future date in YYYY-MM-DD format." : "";

export default function EditRecruiterOpportunityScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const [form, setForm] = useState<Form | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(opportunityId) || opportunityId <= 0) { setError("The opportunity could not be found."); return; } try { const item = await getOpportunity(opportunityId); if (item.status === "closed") { setError("Closed opportunities cannot be edited."); return; } if (!validTypes.has(item.opportunity_type)) { setError("This opportunity cannot be edited as a recruiter opportunity."); return; } setForm({ title: item.title, description: item.description, opportunity_type: item.opportunity_type, deadline: item.deadline.slice(0, 10), location: item.location || "", is_remote: Boolean(item.is_remote) }); setError(""); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); if (isUnauthorizedOpportunityError(requestError)) await resetForUnauthorized(); } }, [opportunityId, resetForUnauthorized]);
  useEffect(() => { load(); }, [load]);
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const submit = async () => { if (!form) return; const validation = validate(form); if (validation) { setError(validation); return; } try { setSaving(true); setError(""); const input: OpportunityInput = { ...form, title: form.title.trim(), description: form.description.trim(), location: form.location.trim() || null }; await updateOpportunity(opportunityId, input); Toast.show({ type: "success", text1: "Opportunity updated" }); navigation.goBack(); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); if (isUnauthorizedOpportunityError(requestError)) await resetForUnauthorized(); } finally { setSaving(false); } };
  if (!form) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color="#2563EB" />}</View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Details</Text></TouchableOpacity><Text style={styles.title}>Edit Opportunity</Text><Field label="Title" value={form.title} onChangeText={(value) => update("title", value)} /><Field label="Description" value={form.description} multiline onChangeText={(value) => update("description", value)} /><Text style={styles.typeNote}>{form.opportunity_type === "job" ? "Job" : "Internship"}</Text><Field label="Deadline (YYYY-MM-DD)" value={form.deadline} onChangeText={(value) => update("deadline", value)} /><Field label="Location (optional)" value={form.location} onChangeText={(value) => update("location", value)} /><View style={styles.remote}><Text style={styles.label}>Remote opportunity</Text><Switch value={form.is_remote} onValueChange={(value) => update("is_remote", value)} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.submit, saving && styles.disabled]} disabled={saving} onPress={submit}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.submitText}>Save Changes</Text>}</TouchableOpacity></ScrollView>;
}
function Field({ label, multiline = false, ...props }: { label: string; value: string; multiline?: boolean; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 28, fontWeight: "bold", color: "#1E3A8A", marginBottom: 18 }, typeNote: { color: "#2563EB", fontWeight: "700", marginBottom: 16 }, field: { marginBottom: 14 }, label: { color: "#333", fontWeight: "600", marginBottom: 6 }, input: { borderWidth: 1, borderColor: "#d1d5db", borderRadius: 10, padding: 12, color: "#333" }, multiline: { minHeight: 110 }, remote: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 4, marginBottom: 16 }, error: { color: "#DC2626", marginBottom: 12, textAlign: "center" }, submit: { backgroundColor: "#10B981", borderRadius: 10, padding: 15, alignItems: "center" }, submitText: { color: "#fff", fontWeight: "700", fontSize: 16 }, disabled: { opacity: 0.65 } });
