import { useCallback, useEffect, useState, type ReactNode } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { appError, Application, ApplicationStatus, getRecruiterApplicantRankings, unauthorized, updateApplicationStatus } from "../../services/application.service";
import { getOpportunity, Opportunity } from "../../services/opportunity.service";

const nextActions: Partial<Record<ApplicationStatus, Array<["reviewing" | "shortlisted" | "rejected" | "accepted", string]>>> = { submitted: [["reviewing", "Start Reviewing"]], reviewing: [["shortlisted", "Shortlist"], ["rejected", "Reject"]], shortlisted: [["accepted", "Accept"], ["rejected", "Reject"]] };

export default function RecruiterApplicationDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const applicationId = Number(route.params?.application?.id);
  const [application, setApplication] = useState<Application | null>(route.params?.application || null); const [opportunity, setOpportunity] = useState<Opportunity | null>(null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { const session = await getStoredAuthSession(); if (session?.user.role !== "recruiter") { setError("Recruiter access is required to view this application."); return; } const [applications, loadedOpportunity] = await Promise.all([getRecruiterApplicantRankings(opportunityId), getOpportunity(opportunityId)]); const current = applications.find((item) => item.id === applicationId); if (!current) { setError("Application was not found."); return; } setApplication(current); setOpportunity(loadedOpportunity); setError(""); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } }, [applicationId, navigation, opportunityId]);
  useEffect(() => { load(); }, [load]);
  const changeStatus = async (status: "reviewing" | "shortlisted" | "rejected" | "accepted", label: string) => { try { setWorking(true); setError(""); await updateApplicationStatus(applicationId, status); await load(); Toast.show({ type: "success", text1: `Application ${label.toLowerCase()}` }); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } finally { setWorking(false); } };
  if (!application) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color="#2563EB" />}</View>;
  const actions = nextActions[application.status] || [];
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Applications</Text></TouchableOpacity><Text style={styles.title}>{application.applicant_name || "Applicant"}</Text><Text style={styles.status}>{application.status}</Text><Section title="Applicant"><Info label="Email" value={application.applicant_email || "Not available"} /><Info label="Role" value={application.applicant_role || "Applicant"} /></Section><Section title="Skill Match">{application.skill_match?.can_calculate ? <><Info label="Match" value={`${application.skill_match.percentage}% (${application.skill_match.matched_skill_count}/${application.skill_match.total_required_skills} required skills)`} /><Info label="Matched skills" value={application.skill_match.matched_skills.map((skill) => skill.skill_name).join(", ") || "None"} /><Info label="Missing skills" value={application.skill_match.missing_skills.map((skill) => skill.skill_name).join(", ") || "None"} /></> : <Info label="Status" value={application.skill_match?.message || "This opportunity has no required skills yet, so a match cannot be calculated."} />}</Section><Section title="Opportunity"><Info label="Title" value={opportunity?.title || application.opportunity_title} /><Info label="Type" value={opportunity?.opportunity_type || application.opportunity_type || "Not available"} /><Info label="Company" value={opportunity?.company_name || "Not available"} /></Section><Section title="Application"><Info label="Submitted" value={application.submitted_at.slice(0, 10)} /><Info label="Cover letter" value={application.cover_letter || "Not provided"} /></Section><Section title="Selected Resume"><Info label="Title" value={application.resume_title || "No resume selected"} /><Info label="File URL" value={application.resume_file_url || "Not provided"} /></Section>{error ? <Text style={styles.error}>{error}</Text> : null}{actions.map(([status, label]) => <TouchableOpacity key={status} style={[styles.action, status === "rejected" && styles.reject, working && styles.disabled]} disabled={working} onPress={() => Alert.alert(`${label} application?`, "This action follows the application workflow.", [{ text: "Cancel", style: "cancel" }, { text: label, style: status === "rejected" ? "destructive" : "default", onPress: () => void changeStatus(status, label) }])}><Text style={[styles.actionText, status === "rejected" && styles.rejectText]}>{working ? "Saving…" : label}</Text></TouchableOpacity>)}</ScrollView>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 28, fontWeight: "bold", color: "#1E3A8A" }, status: { color: "#2563EB", fontWeight: "700", textTransform: "capitalize", marginTop: 7 }, section: { borderTopWidth: 1, borderTopColor: "#E5E7EB", paddingTop: 18, marginTop: 20 }, sectionTitle: { color: "#1E3A8A", fontWeight: "700", fontSize: 18 }, info: { marginTop: 12 }, label: { color: "#666", fontWeight: "600" }, value: { color: "#333", marginTop: 4, lineHeight: 21 }, action: { borderWidth: 1, borderColor: "#2563EB", borderRadius: 10, padding: 14, alignItems: "center", marginTop: 14 }, actionText: { color: "#2563EB", fontWeight: "700" }, reject: { borderColor: "#DC2626" }, rejectText: { color: "#DC2626" }, disabled: { opacity: 0.6 }, error: { color: "#DC2626", textAlign: "center", marginTop: 18 } });
