import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { Announcement, AnnouncementType, getAnnouncementErrorMessage, getAnnouncements, isUnauthorizedAnnouncementError } from "../../services/announcement.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: ({ v?: AnnouncementType; l: string })[] = [{ l: "All" }, { v: "academic", l: "Academic" }, { v: "assignment", l: "Assignment" }, { v: "general", l: "General" }];

export default function RecruiterAnnouncementsScreen() {
  const n = useNavigation<any>(); const [x, setX] = useState<Announcement[]>([]); const [q, setQ] = useState(""); const [t, setT] = useState<AnnouncementType>(); const [active, setActive] = useState<any>({}); const [l, setL] = useState(true); const [r, setR] = useState(false); const [e, setE] = useState("");
  const reset = useCallback(async () => { await clearAuthSession(); n.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [n]);
  const load = useCallback(async (refresh = false) => { refresh ? setR(true) : setL(true); try { const session = await getStoredAuthSession(); if (!session || session.user.role !== "recruiter") { if (!session) await reset(); else setE("Recruiter access is required."); return; } setX(await getAnnouncements(active)); setE(""); } catch (requestError) { setE(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await reset(); } finally { setL(false); setR(false); } }, [active, reset]);
  useEffect(() => { void load(); const off = n.addListener("focus", () => void load()); return off; }, [load, n]);
  if (l) return <View style={s.center}><ActivityIndicator color={colors.primary} size="large" /><Text style={s.loadingText}>Loading announcements…</Text></View>;
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={r} onRefresh={() => void load(true)} tintColor={colors.primary} />}><TouchableOpacity onPress={() => n.goBack()}><Text style={s.back}>‹  Back to Home</Text></TouchableOpacity><View style={s.hero}><Text style={s.eyebrow}>CAMPUS UPDATES</Text><Text style={s.title}>Announcements</Text><Text style={s.subtitle}>Stay connected with relevant academic and CampusX updates.</Text></View><View style={s.filterCard}><TextInput style={s.input} value={q} onChangeText={setQ} placeholder="Search announcements" placeholderTextColor={colors.textMuted} /><View style={s.row}>{types.map((item) => <TouchableOpacity key={item.l} style={[s.choice, t === item.v && s.selected]} onPress={() => setT(item.v)}><Text style={t === item.v ? s.selectedText : s.choiceText}>{item.l}</Text></TouchableOpacity>)}</View><TouchableOpacity style={s.apply} onPress={() => setActive({ search: q.trim() || undefined, announcement_type: t })}><Text style={ui.outlineButtonText}>Apply Filters</Text></TouchableOpacity></View>{e ? <View style={s.errorBox}><Text style={s.err}>{e}</Text><TouchableOpacity onPress={() => void load()}><Text style={s.retry}>Retry</Text></TouchableOpacity></View> : !x.length ? <View style={s.emptyCard}><Text style={s.empty}>No announcements found.</Text></View> : x.map((announcement) => <TouchableOpacity key={announcement.id} style={s.card} onPress={() => n.navigate("RecruiterAnnouncementDetails", { announcementId: announcement.id })}><View style={s.cardTop}><Text style={s.name}>{announcement.title}</Text><View style={s.typeBadge}><Text style={s.type}>{announcement.announcement_type}</Text></View></View><Text numberOfLines={2} style={s.description}>{announcement.content}</Text>{announcement.creator_name ? <Text style={s.meta}>Posted by {announcement.creator_name}</Text> : null}<Text style={s.meta}>Published {announcement.published_at?.slice(0, 10) || "recently"}</Text></TouchableOpacity>)}</ScrollView>;
}

const s = StyleSheet.create({
  center: ui.centered, loadingText: { ...typography.caption, marginTop: spacing.md }, page: ui.screen, content: ui.screenContent,
  back: { ...ui.textButton, marginBottom: spacing.lg }, hero: { marginBottom: spacing.xl }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: "800", letterSpacing: 1.1, marginBottom: spacing.sm }, title: typography.screenTitle, subtitle: { ...typography.caption, marginTop: spacing.sm },
  filterCard: ui.card, input: ui.input, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md }, choice: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.input, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.pill }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.textMuted, fontWeight: "700" }, selectedText: { color: colors.onPrimary, fontWeight: "800" }, apply: { ...ui.outlineButton, minHeight: 46, marginTop: spacing.lg },
  errorBox: { backgroundColor: "rgba(255,113,128,0.12)", borderRadius: radius.md, borderWidth: 1, borderColor: "rgba(255,113,128,0.35)", alignItems: "center", marginTop: spacing.lg, padding: spacing.md }, err: { color: colors.error, textAlign: "center" }, retry: { ...ui.textButton, marginTop: spacing.sm }, emptyCard: { ...ui.card, ...ui.emptyState, marginTop: spacing.lg }, empty: typography.caption,
  card: { ...ui.card, marginTop: spacing.md }, cardTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.sm }, name: { ...typography.cardTitle, flex: 1 }, typeBadge: { backgroundColor: "rgba(137,120,255,0.18)", borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs }, type: { color: colors.secondary, fontSize: 12, fontWeight: "800", textTransform: "capitalize" }, description: { ...typography.body, color: colors.textMuted, marginTop: spacing.md }, meta: { ...typography.caption, marginTop: spacing.sm },
});
