import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { closeOpportunity, deleteOpportunity, getOpportunity, getOpportunityErrorMessage, isUnauthorizedOpportunityError, Opportunity, publishOpportunity } from "../../services/opportunity.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const labels: Record<"job" | "internship", string> = { job: "Job", internship: "Internship" };
export default function RecruiterOpportunityDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const [opportunity, setOpportunity] = useState<Opportunity | null>(null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(opportunityId) || opportunityId <= 0) { setError("The opportunity could not be found."); return; } try { const item = await getOpportunity(opportunityId); if (item.opportunity_type !== "job" && item.opportunity_type !== "internship") { setError("This opportunity cannot be managed as a recruiter opportunity."); return; } setOpportunity(item); setError(""); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); if (isUnauthorizedOpportunityError(requestError)) await resetForUnauthorized(); } }, [opportunityId, resetForUnauthorized]);
  useEffect(() => { load(); const unsubscribe = navigation.addListener("focus", () => load()); return unsubscribe; }, [load, navigation]);
  const action = async (kind: "publish" | "close" | "delete") => { try { setWorking(true); setError(""); if (kind === "publish") { await publishOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity published" }); await load(); } else if (kind === "close") { await closeOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity closed" }); await load(); } else { await deleteOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity deleted" }); navigation.goBack(); } } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); if (isUnauthorizedOpportunityError(requestError)) await resetForUnauthorized(); } finally { setWorking(false); } };
  if (!opportunity) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color={colors.primary} />}</View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Jobs & Internships</Text></TouchableOpacity><View style={styles.hero}><View style={styles.badges}><Text style={styles.type}>{labels[opportunity.opportunity_type as "job" | "internship"]}</Text><Text style={[styles.status, opportunity.status === "published" && styles.publishedStatus, opportunity.status === "closed" && styles.closedStatus]}>{opportunity.status}</Text></View><Text style={styles.title}>{opportunity.title}</Text><Text style={styles.company}>{opportunity.company_name || "Associated company"}</Text></View><View style={styles.infoCard}><Info label="Description" value={opportunity.description} /><Info label="Deadline" value={opportunity.deadline.slice(0, 10)} /><Info label="Location" value={opportunity.location || "Not provided"} /><Info label="Work style" value={opportunity.is_remote ? "Remote" : "On-site"} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.skills} disabled={working} onPress={() => navigation.navigate("OpportunitySkills", { opportunityId })}><Text style={styles.skillsText}>Manage Required Skills</Text></TouchableOpacity><TouchableOpacity style={styles.applications} disabled={working} onPress={() => navigation.navigate("RecruiterApplications", { opportunityId })}><Text style={styles.applicationsText}>View Applications</Text></TouchableOpacity>{opportunity.status !== "closed" ? <TouchableOpacity style={styles.edit} disabled={working} onPress={() => navigation.navigate("EditRecruiterOpportunity", { opportunityId })}><Text style={styles.editText}>Edit Opportunity</Text></TouchableOpacity> : null}{opportunity.status === "draft" ? <TouchableOpacity style={styles.primary} disabled={working} onPress={() => Alert.alert("Publish opportunity?", "Students will be able to browse and apply.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void action("publish") }])}><Text style={styles.primaryText}>{working ? "Publishing…" : "Publish"}</Text></TouchableOpacity> : null}{opportunity.status === "published" ? <TouchableOpacity style={styles.close} disabled={working} onPress={() => Alert.alert("Close opportunity?", "It will no longer accept applications.", [{ text: "Cancel", style: "cancel" }, { text: "Close", style: "destructive", onPress: () => void action("close") }])}><Text style={styles.closeText}>{working ? "Closing…" : "Close Opportunity"}</Text></TouchableOpacity> : null}{opportunity.status === "draft" ? <TouchableOpacity style={styles.delete} disabled={working} onPress={() => Alert.alert("Delete draft?", "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void action("delete") }])}><Text style={styles.deleteText}>Delete Draft</Text></TouchableOpacity> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{...ui.centered},page:{...ui.screen},content:{...ui.screenContent},back:{color:colors.primary,fontWeight:"700",marginBottom:spacing.md},hero:{...ui.card,backgroundColor:colors.backgroundElevated,marginBottom:spacing.md},badges:{flexDirection:"row",gap:spacing.sm,marginBottom:spacing.md},title:{...typography.screenTitle,fontSize:27},company:{color:colors.textMuted,fontWeight:"700",marginTop:spacing.sm},type:{color:colors.primary,backgroundColor:"#103553",paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill,fontWeight:"800",overflow:"hidden"},status:{color:colors.secondary,backgroundColor:"#292750",paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill,fontWeight:"800",textTransform:"capitalize",overflow:"hidden"},publishedStatus:{color:colors.success,backgroundColor:"#123A34"},closedStatus:{color:colors.warning,backgroundColor:"#3B301A"},infoCard:{...ui.card},info:{borderTopWidth:1,borderTopColor:colors.divider,paddingTop:spacing.md,marginTop:spacing.md},label:{color:colors.text,fontWeight:"800"},value:{color:colors.textMuted,marginTop:spacing.xs,lineHeight:22},primary:{...ui.primaryButton,marginTop:spacing.lg},primaryText:{...ui.primaryButtonText},edit:{...ui.outlineButton,minHeight:48,marginTop:spacing.sm},editText:{...ui.outlineButtonText},skills:{borderWidth:1,borderColor:colors.secondary,backgroundColor:"#242148",padding:14,borderRadius:radius.md,alignItems:"center",marginTop:spacing.xl},skillsText:{color:colors.secondary,fontWeight:"800"},applications:{borderWidth:1,borderColor:colors.secondary,padding:14,borderRadius:radius.md,alignItems:"center",marginTop:spacing.sm},applicationsText:{color:colors.secondary,fontWeight:"800"},close:{borderWidth:1,borderColor:colors.warning,padding:14,borderRadius:radius.md,alignItems:"center",marginTop:spacing.sm},closeText:{color:colors.warning,fontWeight:"800"},delete:{borderWidth:1,borderColor:colors.error,padding:14,borderRadius:radius.md,alignItems:"center",marginTop:spacing.sm},deleteText:{color:colors.error,fontWeight:"800"},error:{color:colors.error,textAlign:"center",marginTop:spacing.md} });
