import { useCallback, useEffect, useState, type ReactNode } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { appError, Application, ApplicationStatus, getRecruiterApplicantRankings, unauthorized, updateApplicationStatus } from "../../services/application.service";
import { getOpportunity, Opportunity } from "../../services/opportunity.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const nextActions: Partial<Record<ApplicationStatus, Array<["reviewing" | "shortlisted" | "rejected" | "accepted", string]>>> = { submitted: [["reviewing", "Start Reviewing"]], reviewing: [["shortlisted", "Shortlist"], ["rejected", "Reject"]], shortlisted: [["accepted", "Accept"], ["rejected", "Reject"]] };

export default function RecruiterApplicationDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const applicationId = Number(route.params?.application?.id);
  const [application, setApplication] = useState<Application | null>(route.params?.application || null); const [opportunity, setOpportunity] = useState<Opportunity | null>(null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { const session = await getStoredAuthSession(); if (session?.user.role !== "recruiter") { setError("Recruiter access is required to view this application."); return; } const [applications, loadedOpportunity] = await Promise.all([getRecruiterApplicantRankings(opportunityId), getOpportunity(opportunityId)]); const current = applications.find((item) => item.id === applicationId); if (!current) { setError("Application was not found."); return; } setApplication(current); setOpportunity(loadedOpportunity); setError(""); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } }, [applicationId, navigation, opportunityId]);
  useEffect(() => { load(); }, [load]);
  const changeStatus = async (status: "reviewing" | "shortlisted" | "rejected" | "accepted", label: string) => { try { setWorking(true); setError(""); await updateApplicationStatus(applicationId, status); await load(); Toast.show({ type: "success", text1: `Application ${label.toLowerCase()}` }); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } finally { setWorking(false); } };
  if (!application) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color={colors.primary} />}</View>;
  const actions = nextActions[application.status] || [];
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Applications</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>APPLICANT REVIEW</Text><Text style={styles.title}>{application.applicant_name || "Applicant"}</Text><Text style={[styles.status, application.status === "accepted" && styles.acceptedStatus, application.status === "rejected" && styles.rejectedStatus, application.status === "shortlisted" && styles.shortlistedStatus]}>{application.status}</Text></View><Section title="Applicant"><Info label="Email" value={application.applicant_email || "Not available"} /><Info label="Role" value={application.applicant_role || "Applicant"} /></Section><Section title="Skill Match">{application.skill_match?.can_calculate ? <><Info label="Match" value={`${application.skill_match.percentage}% (${application.skill_match.matched_skill_count}/${application.skill_match.total_required_skills} required skills)`} /><Info label="Matched skills" value={application.skill_match.matched_skills.map((skill) => skill.skill_name).join(", ") || "None"} /><Info label="Missing skills" value={application.skill_match.missing_skills.map((skill) => skill.skill_name).join(", ") || "None"} /></> : <Info label="Status" value={application.skill_match?.message || "This opportunity has no required skills yet, so a match cannot be calculated."} />}</Section><Section title="Opportunity"><Info label="Title" value={opportunity?.title || application.opportunity_title} /><Info label="Type" value={opportunity?.opportunity_type || application.opportunity_type || "Not available"} /><Info label="Company" value={opportunity?.company_name || "Not available"} /></Section><Section title="Application"><Info label="Submitted" value={application.submitted_at.slice(0, 10)} /><Info label="Cover letter" value={application.cover_letter || "Not provided"} /></Section><Section title="Selected Resume"><Info label="Title" value={application.resume_title || "No resume selected"} /><Info label="File URL" value={application.resume_file_url || "Not provided"} /></Section>{error ? <Text style={styles.error}>{error}</Text> : null}{actions.map(([status, label]) => <TouchableOpacity key={status} style={[styles.action, status === "rejected" && styles.reject, working && styles.disabled]} disabled={working} onPress={() => Alert.alert(`${label} application?`, "This action follows the application workflow.", [{ text: "Cancel", style: "cancel" }, { text: label, style: status === "rejected" ? "destructive" : "default", onPress: () => void changeStatus(status, label) }])}><Text style={[styles.actionText, status === "rejected" && styles.rejectText]}>{working ? "Saving…" : label}</Text></TouchableOpacity>)}</ScrollView>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{...ui.centered},page:{...ui.screen},content:{...ui.screenContent},back:{color:colors.primary,fontWeight:"700",marginBottom:spacing.md},hero:{...ui.card,backgroundColor:colors.backgroundElevated,marginBottom:spacing.md},eyebrow:{color:colors.primary,fontSize:10,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:27},status:{alignSelf:"flex-start",color:colors.info,backgroundColor:"#103553",fontWeight:"800",textTransform:"capitalize",marginTop:spacing.md,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderRadius:radius.pill,overflow:"hidden"},acceptedStatus:{color:colors.success,backgroundColor:"#123A34"},rejectedStatus:{color:colors.error,backgroundColor:"#3A2028"},shortlistedStatus:{color:colors.secondary,backgroundColor:"#292750"},section:{...ui.card,marginTop:spacing.md},sectionTitle:{...typography.cardTitle},info:{borderTopWidth:1,borderTopColor:colors.divider,paddingTop:spacing.md,marginTop:spacing.md},label:{color:colors.text,fontWeight:"800",fontSize:13},value:{color:colors.textMuted,marginTop:spacing.xs,lineHeight:21},action:{...ui.outlineButton,minHeight:48,marginTop:spacing.md},actionText:{...ui.outlineButtonText},reject:{borderColor:colors.error,backgroundColor:"#321C2A"},rejectText:{color:colors.error},disabled:{...ui.disabled},error:{color:colors.error,textAlign:"center",marginTop:spacing.md} });
