import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { getProfile, getProfileErrorMessage, ProfileResponse, updateRecruiterProfile } from "../../services/profile.service";

export default function RecruiterProfileScreen() {
  const navigation = useNavigation<any>(); const [profile, setProfile] = useState<ProfileResponse | null>(null); const [jobTitle, setJobTitle] = useState(""); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (refresh=false) => { refresh ? setRefreshing(true) : setLoading(true); try { const data=await getProfile(); if(data.user.role!=="recruiter"){setError("Recruiter access is required.");return;} setProfile(data);setJobTitle(data.recruiter_profile?.job_title||"");setError(""); } catch(e){setError(getProfileErrorMessage(e));} finally{setLoading(false);setRefreshing(false);} },[]);
  useEffect(()=>{load();},[load]);
  const save=async()=>{if(!profile?.recruiter_profile)return;if(!jobTitle.trim()){setError("Job title is required.");return;}try{setSaving(true);setError("");await updateRecruiterProfile(profile.recruiter_profile.company_id,jobTitle.trim());await load();Toast.show({type:"success",text1:"Recruiter profile updated"});}catch(e){setError(getProfileErrorMessage(e));}finally{setSaving(false);}};
  if(loading&&!profile)return <View style={s.center}><ActivityIndicator size="large" color="#2563EB"/></View>;
  if(!profile)return <View style={s.center}><Text style={s.error}>{error||"Unable to load recruiter profile."}</Text><TouchableOpacity onPress={()=>load()}><Text style={s.link}>Retry</Text></TouchableOpacity></View>;
  const recruiter=profile.recruiter_profile;
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)}/>}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.link}>Back to Home</Text></TouchableOpacity><Text style={s.title}>Recruiter Profile</Text><Text style={s.name}>{profile.user.full_name}</Text><Text style={s.detail}>{profile.user.email}</Text><Text style={s.detail}>Role: {profile.user.role}</Text>{error?<Text style={s.error}>{error}</Text>:null}{recruiter?<View style={s.card}><Text style={s.heading}>Associated Company</Text><Text style={s.company}>{recruiter.company_name}</Text><Text style={s.detail}>{recruiter.company_website||"No website"}</Text><Text style={s.detail}>{recruiter.company_location||"No location"}</Text><Text style={s.status}>{recruiter.company_approval_status==="approved"?"Company Approved":recruiter.company_approval_status==="pending"?"Pending Admin Approval":"Company Rejected"}</Text><Text style={s.label}>Job title</Text><TextInput style={s.input} value={jobTitle} onChangeText={setJobTitle} editable={!saving}/><TouchableOpacity style={s.primary} disabled={saving} onPress={save}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Edit Recruiter Profile</Text>}</TouchableOpacity><TouchableOpacity style={s.button} onPress={()=>navigation.navigate("CompanyDetails",{companyId:recruiter.company_id})}><Text style={s.buttonText}>View / Manage Company</Text></TouchableOpacity></View>:<View style={s.card}><Text style={s.empty}>No approved company associated yet.</Text></View>}<TouchableOpacity style={s.button} onPress={()=>navigation.navigate("CreateCompany")}><Text style={s.buttonText}>Create Company</Text></TouchableOpacity><TouchableOpacity style={s.button} onPress={()=>navigation.navigate("SelectCompany")}><Text style={s.buttonText}>Select Company</Text></TouchableOpacity></ScrollView>;
}
const s=StyleSheet.create({center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24},link:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:29,fontWeight:"bold",color:"#1E3A8A"},name:{fontSize:20,fontWeight:"700",marginTop:16},detail:{color:"#4B5563",marginTop:5},card:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:16,marginTop:24},heading:{fontSize:18,fontWeight:"700",color:"#1E3A8A"},company:{fontSize:18,fontWeight:"600",marginTop:10},status:{color:"#047857",fontWeight:"700",marginTop:10},label:{fontWeight:"600",marginTop:18},input:{borderWidth:1,borderColor:"#ddd",borderRadius:8,padding:11,marginTop:6},primary:{backgroundColor:"#10B981",padding:13,borderRadius:8,alignItems:"center",marginTop:12},primaryText:{color:"#fff",fontWeight:"700"},button:{borderWidth:1,borderColor:"#2563EB",padding:14,borderRadius:10,alignItems:"center",marginTop:14},buttonText:{color:"#2563EB",fontWeight:"700"},empty:{color:"#666"},error:{color:"#DC2626",textAlign:"center",marginTop:14}});
