import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { companies, companyError, Company } from "../../services/company.service";
import { getProfile, getProfileErrorMessage, updateRecruiterProfile } from "../../services/profile.service";

export default function SelectCompanyScreen() {
  const navigation = useNavigation<any>(); const [items,setItems]=useState<Company[]>([]); const [jobTitle,setJobTitle]=useState(""); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [selecting,setSelecting]=useState<number|null>(null); const [error,setError]=useState("");
  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);try{const [available,profile]=await Promise.all([companies(),getProfile()]);if(profile.user.role!=="recruiter"){setError("Recruiter access is required.");return;}const title=profile.recruiter_profile?.job_title?.trim();if(!title){setError("Set your recruiter job title before selecting a company.");return;}setItems(available);setJobTitle(title);setError("");}catch(e){setError(companyError(e)||getProfileErrorMessage(e));}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{load();},[load]);
  const select=async(item:Company)=>{if(item.approval_status!=="approved")return;try{setSelecting(item.id);setError("");await updateRecruiterProfile(item.id,jobTitle);Toast.show({type:"success",text1:"Company selected",text2:"Your recruiter profile has been updated."});navigation.reset({index:0,routes:[{name:"RecruiterProfile"}]});}catch(e){setError(getProfileErrorMessage(e));}finally{setSelecting(null);}};
  if(loading)return <View style={s.center}><ActivityIndicator size="large" color="#2563EB"/></View>;
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)}/>}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>Back to Recruiter Profile</Text></TouchableOpacity><Text style={s.title}>Select Company</Text>{error?<View style={s.errorBox}><Text style={s.error}>{error}</Text><TouchableOpacity onPress={()=>load()}><Text style={s.back}>Retry</Text></TouchableOpacity></View>:null}{!error&&items.length===0?<Text style={s.empty}>No companies are available right now.</Text>:null}{items.map(item=>{const approved=item.approval_status==="approved";const label=approved?"Select":item.approval_status==="pending"?"Pending Admin Approval":"Rejected";return <View key={item.id} style={s.card}><Text style={s.name}>{item.name}</Text><Text style={s.detail}>{item.location||"Location not provided"}</Text><Text style={[s.status,approved?s.approved:s.disabledStatus]}>{label}</Text><TouchableOpacity style={[s.button,!approved&&s.disabled]} disabled={!approved||selecting!==null} onPress={()=>select(item)}>{selecting===item.id?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{label}</Text>}</TouchableOpacity></View>})}</ScrollView>;
}
const s=StyleSheet.create({center:{flex:1,justifyContent:"center",alignItems:"center"},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:29,fontWeight:"bold",color:"#1E3A8A",marginBottom:16},card:{borderWidth:1,borderColor:"#E5E7EB",borderRadius:10,padding:16,marginBottom:12},name:{fontSize:18,fontWeight:"700",color:"#333"},detail:{color:"#4B5563",marginTop:6},status:{fontWeight:"700",marginTop:8},approved:{color:"#047857"},disabledStatus:{color:"#B45309"},button:{backgroundColor:"#2563EB",borderRadius:8,padding:12,alignItems:"center",marginTop:12},disabled:{backgroundColor:"#9CA3AF"},buttonText:{color:"#fff",fontWeight:"700"},empty:{color:"#666",textAlign:"center",marginTop:24},errorBox:{alignItems:"center",marginBottom:12},error:{color:"#DC2626",textAlign:"center",marginBottom:8}});
