import { useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { AcademicResourceInput, AcademicResourceType, createResource, getAcademicResourceErrorMessage, isUnauthorizedAcademicResourceError } from "../../services/academic-resource.service";

const types: { value: AcademicResourceType; label: string }[] = [{ value: "lecture_notes", label: "Lecture Notes" }, { value: "slides", label: "Slides" }, { value: "lab_manual", label: "Lab Manual" }, { value: "previous_questions", label: "Previous Questions" }, { value: "research_material", label: "Research Material" }, { value: "other", label: "Other" }];
const validUrl = (value: string) => /^https?:\/\/\S+$/i.test(value);

export default function CreateResourceScreen() {
  const navigation = useNavigation<any>(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [resourceType, setResourceType] = useState<AcademicResourceType>("lecture_notes"); const [subject, setSubject] = useState(""); const [resourceUrl, setResourceUrl] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const save = async () => { const normalizedTitle = title.trim(), normalizedUrl = resourceUrl.trim(); if (!normalizedTitle) return setError("Resource title is required."); if (normalizedTitle.length > 200) return setError("Resource title must be 200 characters or fewer."); if (description.trim().length > 5000 || subject.trim().length > 150) return setError("Description or subject is too long."); if (normalizedUrl && (!validUrl(normalizedUrl) || normalizedUrl.length > 2048)) return setError("External URL must be a valid http or https URL."); const data: AcademicResourceInput = { title: normalizedTitle, description: description.trim() || null, resource_type: resourceType, subject: subject.trim() || null, resource_url: normalizedUrl || null }; try { setSaving(true); setError(""); await createResource(data); Toast.show({ type: "success", text1: "Resource created", text2: "Saved as a draft." }); navigation.goBack(); } catch (requestError) { const message = getAcademicResourceErrorMessage(requestError); setError(message); if (isUnauthorizedAcademicResourceError(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } finally { setSaving(false); } };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity><Text style={styles.title}>Create Resource</Text><Text style={styles.subtitle}>This creates metadata with an optional external link. It will start as a draft.</Text><Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Description (optional)" value={description} onChangeText={setDescription} editable={!saving} multiline /><Text style={styles.label}>Resource type</Text><View style={styles.typeList}>{types.map((type) => <TouchableOpacity key={type.value} style={[styles.typeButton, resourceType === type.value && styles.selectedType]} onPress={() => setResourceType(type.value)} disabled={saving}><Text style={resourceType === type.value ? styles.selectedText : styles.typeText}>{type.label}</Text></TouchableOpacity>)}</View><Input label="Subject (optional)" value={subject} onChangeText={setSubject} editable={!saving} /><Input label="External URL (optional)" value={resourceUrl} onChangeText={setResourceUrl} editable={!saving} autoCapitalize="none" keyboardType="url" />{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>Create Draft Resource</Text>}</TouchableOpacity></ScrollView>;
}
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean; autoCapitalize?: "none"; keyboardType?: "url" }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
const styles = StyleSheet.create({ page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A"},subtitle:{color:"#666",lineHeight:22,marginTop:6,marginBottom:20},group:{marginBottom:14},label:{color:"#333",fontWeight:"600",marginBottom:6},input:{borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:12,fontSize:16,color:"#333"},multiline:{minHeight:96},typeList:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:18},typeButton:{borderWidth:1,borderColor:"#2563EB",borderRadius:8,padding:9},selectedType:{backgroundColor:"#2563EB"},typeText:{color:"#2563EB",fontSize:13},selectedText:{color:"#fff",fontSize:13},save:{backgroundColor:"#10B981",padding:15,borderRadius:10,alignItems:"center",marginTop:16},saveText:{color:"#fff",fontWeight:"700",fontSize:16},disabled:{opacity:.65},error:{color:"#DC2626",lineHeight:21,marginTop:4} });
