import { useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { AcademicResourceInput, AcademicResourceType, createResource, getAcademicResourceErrorMessage, isUnauthorizedAcademicResourceError } from "../../services/academic-resource.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: { value: AcademicResourceType; label: string }[] = [{ value: "lecture_notes", label: "Lecture Notes" }, { value: "slides", label: "Slides" }, { value: "lab_manual", label: "Lab Manual" }, { value: "previous_questions", label: "Previous Questions" }, { value: "research_material", label: "Research Material" }, { value: "other", label: "Other" }];
const validUrl = (value: string) => /^https?:\/\/\S+$/i.test(value);

export default function CreateResourceScreen() {
  const navigation = useNavigation<any>(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [resourceType, setResourceType] = useState<AcademicResourceType>("lecture_notes"); const [subject, setSubject] = useState(""); const [resourceUrl, setResourceUrl] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const save = async () => { const normalizedTitle = title.trim(), normalizedUrl = resourceUrl.trim(); if (!normalizedTitle) return setError("Resource title is required."); if (normalizedTitle.length > 200) return setError("Resource title must be 200 characters or fewer."); if (description.trim().length > 5000 || subject.trim().length > 150) return setError("Description or subject is too long."); if (normalizedUrl && (!validUrl(normalizedUrl) || normalizedUrl.length > 2048)) return setError("External URL must be a valid http or https URL."); const data: AcademicResourceInput = { title: normalizedTitle, description: description.trim() || null, resource_type: resourceType, subject: subject.trim() || null, resource_url: normalizedUrl || null }; try { setSaving(true); setError(""); await createResource(data); Toast.show({ type: "success", text1: "Resource created", text2: "Saved as a draft." }); navigation.goBack(); } catch (requestError) { const message = getAcademicResourceErrorMessage(requestError); setError(message); if (isUnauthorizedAcademicResourceError(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } finally { setSaving(false); } };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>‹  Back to Resources</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>FACULTY RESOURCE HUB</Text><Text style={styles.title}>Create Resource</Text><Text style={styles.subtitle}>Create draft resource details with an optional external link.</Text></View><View style={styles.formCard}><Text style={styles.sectionTitle}>Resource details</Text><Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Description (optional)" value={description} onChangeText={setDescription} editable={!saving} multiline /><Text style={styles.label}>Resource type</Text><View style={styles.typeList}>{types.map((type) => <TouchableOpacity key={type.value} style={[styles.typeButton, resourceType === type.value && styles.selectedType]} onPress={() => setResourceType(type.value)} disabled={saving}><Text style={resourceType === type.value ? styles.selectedText : styles.typeText}>{type.label}</Text></TouchableOpacity>)}</View><Input label="Subject (optional)" value={subject} onChangeText={setSubject} editable={!saving} /><Input label="External URL (optional)" value={resourceUrl} onChangeText={setResourceUrl} editable={!saving} autoCapitalize="none" keyboardType="url" />{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text></View> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text style={ui.primaryButtonText}>Create Draft Resource</Text>}</TouchableOpacity></View></ScrollView>;
}
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean; autoCapitalize?: "none"; keyboardType?: "url" }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} placeholderTextColor={colors.textMuted} {...props} /></View>; }
const styles = StyleSheet.create({ page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{marginBottom:spacing.xl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:typography.screenTitle,subtitle:{...typography.caption,marginTop:spacing.sm},formCard:ui.card,sectionTitle:{...typography.cardTitle,marginBottom:spacing.sm},group:{marginTop:spacing.lg},label:{color:colors.text,fontWeight:"700",marginBottom:spacing.sm},input:ui.input,multiline:{minHeight:106,paddingTop:14},typeList:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginBottom:spacing.sm},typeButton:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},selectedType:{backgroundColor:colors.primary,borderColor:colors.primary},typeText:{color:colors.textMuted,fontSize:13,fontWeight:"700"},selectedText:{color:colors.onPrimary,fontSize:13,fontWeight:"800"},save:{...ui.primaryButton,marginTop:spacing.xl},disabled:ui.disabled,errorBox:{backgroundColor:"rgba(255,113,128,0.12)",borderRadius:radius.md,borderWidth:1,borderColor:"rgba(255,113,128,0.35)",marginTop:spacing.lg,padding:spacing.md},error:{color:colors.error,lineHeight:21,textAlign:"center"} });
