import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { getOpportunity, getOpportunityErrorMessage, OpportunityInput, OpportunityType, updateOpportunity } from "../../services/opportunity.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: Array<[OpportunityType, string]> = [["ra", "Research Assistant (RA)"], ["ta", "Teaching Assistant (TA)"], ["research", "Research"]];
type Form = { title: string; description: string; opportunity_type: OpportunityType; deadline: string; location: string; is_remote: boolean };
const validate = (form: Form) => !form.title.trim() ? "Title is required." : !form.description.trim() ? "Description is required." : !types.some(([type]) => type === form.opportunity_type) ? "Select a valid faculty opportunity type." : !/^\d{4}-\d{2}-\d{2}$/.test(form.deadline) || new Date(`${form.deadline}T23:59:59`).getTime() < Date.now() ? "Deadline must be a current or future date in YYYY-MM-DD format." : "";

export default function EditOpportunityScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId);
  const [form, setForm] = useState<Form | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const opportunity = await getOpportunity(opportunityId); if (opportunity.status === "closed") { setError("Closed opportunities cannot be edited."); return; } if (!types.some(([type]) => type === opportunity.opportunity_type)) { setError("This opportunity cannot be edited as a faculty opportunity."); return; } setForm({ title: opportunity.title, description: opportunity.description, opportunity_type: opportunity.opportunity_type, deadline: opportunity.deadline.slice(0, 10), location: opportunity.location || "", is_remote: Boolean(opportunity.is_remote) }); setError(""); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); } }, [opportunityId]);
  useEffect(() => { load(); }, [load]);
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const submit = async () => { if (!form) return; const validation = validate(form); if (validation) { setError(validation); return; } try { setSaving(true); setError(""); const input: OpportunityInput = { ...form, title: form.title.trim(), description: form.description.trim(), location: form.location.trim() || null }; await updateOpportunity(opportunityId, input); Toast.show({ type: "success", text1: "Opportunity updated" }); navigation.goBack(); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); } finally { setSaving(false); } };
  if (!form) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color={colors.primary} />}</View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Details</Text></TouchableOpacity><Text style={styles.title}>Edit Opportunity</Text><Text style={styles.subtitle}>Update the academic opportunity while keeping its existing workflow intact.</Text><View style={styles.formCard}><Field label="Title" value={form.title} onChangeText={(value) => update("title", value)} /><Field label="Description" value={form.description} multiline onChangeText={(value) => update("description", value)} /><Text style={styles.label}>Opportunity type</Text><View style={styles.types}>{types.map(([type, label]) => <TouchableOpacity key={type} style={[styles.type, form.opportunity_type === type && styles.typeSelected]} onPress={() => update("opportunity_type", type)}><Text style={form.opportunity_type === type ? styles.typeTextSelected : styles.typeText}>{label}</Text></TouchableOpacity>)}</View><Field label="Deadline (YYYY-MM-DD)" value={form.deadline} onChangeText={(value) => update("deadline", value)} /><Field label="Location (optional)" value={form.location} onChangeText={(value) => update("location", value)} /><View style={styles.remote}><Text style={styles.label}>Remote opportunity</Text><Switch value={form.is_remote} onValueChange={(value) => update("is_remote", value)} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.submit, saving && styles.disabled]} disabled={saving} onPress={submit}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text style={styles.submitText}>Save Changes</Text>}</TouchableOpacity></View></ScrollView>;
}

function Field({ label, multiline = false, ...props }: { label: string; value: string; multiline?: boolean; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
const styles = StyleSheet.create({ center: ui.centered, page: ui.screen, content: ui.screenContent, back: { ...ui.textButton, marginBottom: spacing.lg }, title: typography.screenTitle, subtitle: { ...typography.caption, fontSize: 16, marginTop: spacing.xs, marginBottom: spacing.lg }, formCard: ui.card, field: { marginBottom: spacing.md }, label: { color: colors.text, fontWeight: "700", marginBottom: spacing.sm }, input: ui.input, multiline: { minHeight: 110 }, types: { gap: spacing.sm, marginBottom: spacing.md }, type: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, backgroundColor: colors.input }, typeSelected: { backgroundColor: colors.secondary, borderColor: colors.secondary }, typeText: { color: colors.textMuted }, typeTextSelected: { color: colors.onDark, fontWeight: "700" }, remote: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.xs, marginBottom: spacing.lg }, error: { color: colors.error, marginBottom: spacing.md, textAlign: "center" }, submit: ui.primaryButton, submitText: ui.primaryButtonText, disabled: ui.disabled });
