import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import * as DocumentPicker from "expo-document-picker";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { AcademicResourceStatus, AcademicResourceType, getAcademicResourceErrorMessage, getResource, isUnauthorizedAcademicResourceError, updateResource, uploadResourceFile } from "../../services/academic-resource.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const types: { value: AcademicResourceType; label: string }[] = [{ value: "lecture_notes", label: "Lecture Notes" }, { value: "slides", label: "Slides" }, { value: "lab_manual", label: "Lab Manual" }, { value: "previous_questions", label: "Previous Questions" }, { value: "research_material", label: "Research Material" }, { value: "other", label: "Other" }];
const statuses: AcademicResourceStatus[] = ["draft", "published", "archived"];
const validUrl = (value: string) => /^https?:\/\/\S+$/i.test(value);

export default function EditResourceScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const resourceId = Number(route.params?.resourceId);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [resourceType, setResourceType] = useState<AcademicResourceType>("lecture_notes"); const [subject, setSubject] = useState(""); const [resourceUrl, setResourceUrl] = useState(""); const [status, setStatus] = useState<AcademicResourceStatus>("draft"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const unauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(resourceId) || resourceId < 1) { setError("The resource could not be found."); setLoading(false); return; } try { setLoading(true); const resource = await getResource(resourceId); setTitle(resource.title); setDescription(resource.description || ""); setResourceType(resource.resource_type); setSubject(resource.subject || ""); setResourceUrl(resource.resource_url || ""); setStatus(resource.status); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setLoading(false); } }, [resourceId, unauthorized]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const normalizedTitle = title.trim(), normalizedUrl = resourceUrl.trim(); if (!normalizedTitle) return setError("Resource title is required."); if (normalizedTitle.length > 200) return setError("Resource title must be 200 characters or fewer."); if (description.trim().length > 5000 || subject.trim().length > 150) return setError("Description or subject is too long."); if (normalizedUrl && (!validUrl(normalizedUrl) || normalizedUrl.length > 2048)) return setError("External URL must be a valid http or https URL."); try { setSaving(true); setError(""); await updateResource(resourceId, { title: normalizedTitle, description: description.trim() || null, resource_type: resourceType, subject: subject.trim() || null, resource_url: normalizedUrl || null, status }); Toast.show({ type: "success", text1: "Resource updated" }); navigation.goBack(); } catch (requestError) { const message = getAcademicResourceErrorMessage(requestError); setError(message); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setSaving(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.loadingText}>Loading resource…</Text></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>‹  Cancel</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>FACULTY RESOURCE HUB</Text><Text style={styles.title}>Edit Resource</Text><Text style={styles.subtitle}>Keep your resource details and delivery material up to date.</Text></View><View style={styles.formCard}><Text style={styles.sectionTitle}>Resource details</Text><Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Description (optional)" value={description} onChangeText={setDescription} editable={!saving} multiline /><Text style={styles.label}>Resource type</Text><View style={styles.choiceList}>{types.map((type) => <Choice key={type.value} label={type.label} selected={resourceType === type.value} onPress={() => setResourceType(type.value)} disabled={saving} />)}</View><Input label="Subject (optional)" value={subject} onChangeText={setSubject} editable={!saving} /><Input label="External URL (optional)" value={resourceUrl} onChangeText={setResourceUrl} editable={!saving} autoCapitalize="none" keyboardType="url" /><Text style={styles.label}>Status</Text><View style={styles.choiceList}>{statuses.map((value) => <Choice key={value} label={value} selected={status === value} onPress={() => setStatus(value)} disabled={saving} />)}</View><View style={styles.uploadCard}><Text style={styles.uploadTitle}>Resource file</Text><Text style={styles.uploadHint}>Upload a replacement PDF, DOCX, JPG, or PNG file up to 10 MB.</Text><ResourceUpload resourceId={resourceId} disabled={saving} onUploaded={load} onError={setError} onUnauthorized={unauthorized} /></View>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text></View> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color={colors.onPrimary} /> : <Text style={ui.primaryButtonText}>Save Changes</Text>}</TouchableOpacity></View></ScrollView>;
}
function Choice({ label, selected, onPress, disabled }: { label: string; selected: boolean; onPress: () => void; disabled: boolean }) { return <TouchableOpacity style={[styles.choice, selected && styles.selected]} onPress={onPress} disabled={disabled}><Text style={selected ? styles.selectedText : styles.choiceText}>{label}</Text></TouchableOpacity>; }
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean; autoCapitalize?: "none"; keyboardType?: "url" }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} placeholderTextColor={colors.textMuted} {...props} /></View>; }
function ResourceUpload({ resourceId, disabled, onUploaded, onError, onUnauthorized }: { resourceId: number; disabled: boolean; onUploaded: () => Promise<void>; onError: (message: string) => void; onUnauthorized: () => Promise<void> }) { const [uploading, setUploading] = useState(false); const upload = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "image/jpeg", "image/png"], copyToCacheDirectory: true }); if (result.canceled) return; const file = result.assets[0]; if (!file || (file.size !== undefined && file.size > 10 * 1024 * 1024)) { onError("Choose a PDF, DOCX, JPG, or PNG file no larger than 10 MB."); return; } try { setUploading(true); onError(""); await uploadResourceFile(resourceId, { uri: file.uri, name: file.name, mimeType: file.mimeType || "application/pdf" }); await onUploaded(); Toast.show({ type: "success", text1: "Resource file uploaded" }); } catch (error) { onError(getAcademicResourceErrorMessage(error)); if (isUnauthorizedAcademicResourceError(error)) await onUnauthorized(); } finally { setUploading(false); } }; return <TouchableOpacity style={[styles.upload, (disabled || uploading) && styles.disabled]} disabled={disabled || uploading} onPress={() => void upload()}><Text style={styles.uploadText}>{uploading ? "Uploading…" : "Upload Resource File"}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ center:ui.centered,loadingText:{...typography.caption,marginTop:spacing.md},page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{marginBottom:spacing.xl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:typography.screenTitle,subtitle:{...typography.caption,marginTop:spacing.sm},formCard:ui.card,sectionTitle:{...typography.cardTitle,marginBottom:spacing.sm},group:{marginTop:spacing.lg},label:{color:colors.text,fontWeight:"700",marginBottom:spacing.sm},input:ui.input,multiline:{minHeight:106,paddingTop:14},choiceList:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginBottom:spacing.sm},choice:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},selected:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{color:colors.textMuted,fontSize:13,textTransform:"capitalize",fontWeight:"700"},selectedText:{color:colors.onPrimary,fontSize:13,textTransform:"capitalize",fontWeight:"800"},uploadCard:{backgroundColor:colors.input,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,marginTop:spacing.lg},uploadTitle:{...typography.cardTitle,fontSize:16},uploadHint:{...typography.caption,marginTop:spacing.xs},upload:{...ui.outlineButton,minHeight:46,marginTop:spacing.md},uploadText:ui.outlineButtonText,save:{...ui.primaryButton,marginTop:spacing.xl},disabled:ui.disabled,errorBox:{backgroundColor:"rgba(255,113,128,0.12)",borderRadius:radius.md,borderWidth:1,borderColor:"rgba(255,113,128,0.35)",marginTop:spacing.lg,padding:spacing.md},error:{color:colors.error,lineHeight:21,textAlign:"center"} });
