import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import * as DocumentPicker from "expo-document-picker";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { AcademicResourceStatus, AcademicResourceType, getAcademicResourceErrorMessage, getResource, isUnauthorizedAcademicResourceError, updateResource, uploadResourceFile } from "../../services/academic-resource.service";

const types: { value: AcademicResourceType; label: string }[] = [{ value: "lecture_notes", label: "Lecture Notes" }, { value: "slides", label: "Slides" }, { value: "lab_manual", label: "Lab Manual" }, { value: "previous_questions", label: "Previous Questions" }, { value: "research_material", label: "Research Material" }, { value: "other", label: "Other" }];
const statuses: AcademicResourceStatus[] = ["draft", "published", "archived"];
const validUrl = (value: string) => /^https?:\/\/\S+$/i.test(value);

export default function EditResourceScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const resourceId = Number(route.params?.resourceId);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [resourceType, setResourceType] = useState<AcademicResourceType>("lecture_notes"); const [subject, setSubject] = useState(""); const [resourceUrl, setResourceUrl] = useState(""); const [status, setStatus] = useState<AcademicResourceStatus>("draft"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const unauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(resourceId) || resourceId < 1) { setError("The resource could not be found."); setLoading(false); return; } try { setLoading(true); const resource = await getResource(resourceId); setTitle(resource.title); setDescription(resource.description || ""); setResourceType(resource.resource_type); setSubject(resource.subject || ""); setResourceUrl(resource.resource_url || ""); setStatus(resource.status); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setLoading(false); } }, [resourceId, unauthorized]);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { const normalizedTitle = title.trim(), normalizedUrl = resourceUrl.trim(); if (!normalizedTitle) return setError("Resource title is required."); if (normalizedTitle.length > 200) return setError("Resource title must be 200 characters or fewer."); if (description.trim().length > 5000 || subject.trim().length > 150) return setError("Description or subject is too long."); if (normalizedUrl && (!validUrl(normalizedUrl) || normalizedUrl.length > 2048)) return setError("External URL must be a valid http or https URL."); try { setSaving(true); setError(""); await updateResource(resourceId, { title: normalizedTitle, description: description.trim() || null, resource_type: resourceType, subject: subject.trim() || null, resource_url: normalizedUrl || null, status }); Toast.show({ type: "success", text1: "Resource updated" }); navigation.goBack(); } catch (requestError) { const message = getAcademicResourceErrorMessage(requestError); setError(message); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setSaving(false); } };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => navigation.goBack()} disabled={saving}><Text style={styles.back}>Cancel</Text></TouchableOpacity><Text style={styles.title}>Edit Resource</Text><Input label="Title" value={title} onChangeText={setTitle} editable={!saving} /><Input label="Description (optional)" value={description} onChangeText={setDescription} editable={!saving} multiline /><Text style={styles.label}>Resource type</Text><View style={styles.choiceList}>{types.map((type) => <Choice key={type.value} label={type.label} selected={resourceType === type.value} onPress={() => setResourceType(type.value)} disabled={saving} />)}</View><Input label="Subject (optional)" value={subject} onChangeText={setSubject} editable={!saving} /><Input label="External URL (optional)" value={resourceUrl} onChangeText={setResourceUrl} editable={!saving} autoCapitalize="none" keyboardType="url" /><Text style={styles.label}>Status</Text><View style={styles.choiceList}>{statuses.map((value) => <Choice key={value} label={value} selected={status === value} onPress={() => setStatus(value)} disabled={saving} />)}</View><ResourceUpload resourceId={resourceId} disabled={saving} onUploaded={load} onError={setError} onUnauthorized={unauthorized} />{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.save, saving && styles.disabled]} onPress={() => void save()} disabled={saving}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>Save Changes</Text>}</TouchableOpacity></ScrollView>;
}
function Choice({ label, selected, onPress, disabled }: { label: string; selected: boolean; onPress: () => void; disabled: boolean }) { return <TouchableOpacity style={[styles.choice, selected && styles.selected]} onPress={onPress} disabled={disabled}><Text style={selected ? styles.selectedText : styles.choiceText}>{label}</Text></TouchableOpacity>; }
function Input({ label, multiline = false, ...props }: { label: string; value: string; onChangeText: (value: string) => void; editable: boolean; multiline?: boolean; autoCapitalize?: "none"; keyboardType?: "url" }) { return <View style={styles.group}><Text style={styles.label}>{label}</Text><TextInput style={[styles.input, multiline && styles.multiline]} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} {...props} /></View>; }
function ResourceUpload({ resourceId, disabled, onUploaded, onError, onUnauthorized }: { resourceId: number; disabled: boolean; onUploaded: () => Promise<void>; onError: (message: string) => void; onUnauthorized: () => Promise<void> }) { const [uploading, setUploading] = useState(false); const upload = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "image/jpeg", "image/png"], copyToCacheDirectory: true }); if (result.canceled) return; const file = result.assets[0]; if (!file || (file.size !== undefined && file.size > 10 * 1024 * 1024)) { onError("Choose a PDF, DOCX, JPG, or PNG file no larger than 10 MB."); return; } try { setUploading(true); onError(""); await uploadResourceFile(resourceId, { uri: file.uri, name: file.name, mimeType: file.mimeType || "application/pdf" }); await onUploaded(); Toast.show({ type: "success", text1: "Resource file uploaded" }); } catch (error) { onError(getAcademicResourceErrorMessage(error)); if (isUnauthorizedAcademicResourceError(error)) await onUnauthorized(); } finally { setUploading(false); } }; return <TouchableOpacity style={[styles.upload, (disabled || uploading) && styles.disabled]} disabled={disabled || uploading} onPress={() => void upload()}><Text style={styles.uploadText}>{uploading ? "Uploading…" : "Upload Resource File"}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:30,fontWeight:"bold",color:"#1E3A8A",marginBottom:20},group:{marginBottom:14},label:{color:"#333",fontWeight:"600",marginBottom:6},input:{borderWidth:1,borderColor:"#ddd",borderRadius:10,padding:12,fontSize:16,color:"#333"},multiline:{minHeight:96},choiceList:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:18},choice:{borderWidth:1,borderColor:"#2563EB",borderRadius:8,padding:9},selected:{backgroundColor:"#2563EB"},choiceText:{color:"#2563EB",fontSize:13,textTransform:"capitalize"},selectedText:{color:"#fff",fontSize:13,textTransform:"capitalize"},upload:{borderWidth:1,borderColor:"#2563EB",borderRadius:10,padding:13,alignItems:"center",marginTop:4},uploadText:{color:"#2563EB",fontWeight:"700"},save:{backgroundColor:"#10B981",padding:15,borderRadius:10,alignItems:"center",marginTop:16},saveText:{color:"#fff",fontWeight:"700",fontSize:16},disabled:{opacity:.65},error:{color:"#DC2626",lineHeight:21,marginTop:4} });
