import { useCallback, useEffect, useState, type ReactNode } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { appError, Application, ApplicationStatus, getOpportunityApplications, unauthorized, updateApplicationStatus } from "../../services/application.service";

const nextActions: Partial<Record<ApplicationStatus, Array<["reviewing" | "shortlisted" | "rejected" | "accepted", string]>>> = { submitted: [["reviewing", "Start Reviewing"]], reviewing: [["shortlisted", "Shortlist"], ["rejected", "Reject"]], shortlisted: [["accepted", "Accept"], ["rejected", "Reject"]] };

export default function FacultyApplicationDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const applicationId = Number(route.params?.application?.id);
  const [application, setApplication] = useState<Application | null>(route.params?.application || null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { const session = await getStoredAuthSession(); if (session?.user.role !== "faculty") { setError("Faculty access is required to view this application."); return; } const applications = await getOpportunityApplications(opportunityId); const current = applications.find((item) => item.id === applicationId); if (!current) { setError("Application was not found."); return; } setApplication(current); setError(""); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } }, [applicationId, navigation, opportunityId]);
  useEffect(() => { load(); }, [load]);
  const changeStatus = async (status: "reviewing" | "shortlisted" | "rejected" | "accepted", label: string) => { try { setWorking(true); setError(""); await updateApplicationStatus(applicationId, status); await load(); Toast.show({ type: "success", text1: `Application ${label.toLowerCase()}` }); } catch (requestError) { setError(appError(requestError)); } finally { setWorking(false); } };
  if (!application) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color={colors.primary} />}</View>;
  const actions = nextActions[application.status] || [];
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Applications</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>APPLICANT REVIEW</Text><Text style={styles.title}>{application.applicant_name || "Applicant"}</Text><Text style={styles.status}>{application.status}</Text></View><Section title="Applicant"><Info label="Email" value={application.applicant_email || "Not available"} /><Info label="Role" value={application.applicant_role || "Applicant"} /></Section><Section title="Opportunity"><Info label="Title" value={application.opportunity_title} /><Info label="Type" value={application.opportunity_type || "Not available"} /><Info label="Deadline" value={application.deadline?.slice(0, 10) || "Not available"} /></Section><Section title="Application"><Info label="Submitted" value={application.submitted_at.slice(0, 10)} /><Info label="Cover letter" value={application.cover_letter || "Not provided"} /></Section><Section title="Selected Resume"><Info label="Title" value={application.resume_title || "No resume selected"} /><Info label="Summary" value={application.resume_summary || "Not provided"} /><Info label="File URL" value={application.resume_file_url || "Not provided"} /></Section>{error ? <Text style={styles.error}>{error}</Text> : null}{actions.map(([status, label]) => <TouchableOpacity key={status} style={[styles.action, status === "rejected" && styles.reject, working && styles.disabled]} disabled={working} onPress={() => Alert.alert(`${label} application?`, "This action follows the application workflow.", [{ text: "Cancel", style: "cancel" }, { text: label, style: status === "rejected" ? "destructive" : "default", onPress: () => void changeStatus(status, label) }])}><Text style={[styles.actionText, status === "rejected" && styles.rejectText]}>{working ? "Saving…" : label}</Text></TouchableOpacity>)}</ScrollView>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{...ui.card,borderColor:colors.primary,paddingVertical:spacing.xl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:28,lineHeight:35},status:{alignSelf:"flex-start",color:colors.primary,fontWeight:"700",textTransform:"capitalize",marginTop:spacing.md,backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},section:{...ui.card,paddingTop:spacing.lg,marginTop:spacing.md},sectionTitle:typography.cardTitle,info:{marginTop:spacing.md},label:{color:colors.textMuted,fontWeight:"700",fontSize:13},value:{...typography.body,color:colors.text,marginTop:spacing.xs,lineHeight:21},action:{...ui.outlineButton,marginTop:spacing.md},actionText:ui.outlineButtonText,reject:{borderColor:colors.error},rejectText:{color:colors.error},disabled:ui.disabled,error:{color:colors.error,textAlign:"center",marginTop:spacing.lg} });
