import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { AcademicResource, deleteResource, getAcademicResourceErrorMessage, getResource, isUnauthorizedAcademicResourceError, updateResource } from "../../services/academic-resource.service";

const typeLabels: Record<AcademicResource["resource_type"], string> = { lecture_notes: "Lecture Notes", slides: "Slides", lab_manual: "Lab Manual", previous_questions: "Previous Questions", research_material: "Research Material", other: "Other" };

export default function FacultyResourceDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const resourceId = Number(route.params?.resourceId);
  const [resource, setResource] = useState<AcademicResource | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const unauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(resourceId) || resourceId < 1) { setError("The resource could not be found."); setLoading(false); return; } try { setLoading(true); setResource(await getResource(resourceId)); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setLoading(false); } }, [resourceId, unauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const publish = async () => { try { setWorking(true); setError(""); await updateResource(resourceId, { status: "published" }); await load(); Toast.show({ type: "success", text1: "Resource published" }); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setWorking(false); } };
  const remove = async () => { try { setWorking(true); setError(""); await deleteResource(resourceId); Toast.show({ type: "success", text1: "Resource deleted" }); navigation.goBack(); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setWorking(false); } };
  if (loading && !resource) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  if (!resource) return <View style={styles.center}><Text style={styles.error}>{error || "Resource not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()} disabled={working}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>RESOURCE MANAGEMENT</Text><Text style={styles.title}>{resource.title}</Text><View style={styles.badges}><Text style={styles.type}>{typeLabels[resource.resource_type]}</Text><Text style={styles.status}>{resource.status}</Text></View></View><Info label="Subject" value={resource.subject || "Not provided"} /><Info label="Description" value={resource.description || "Not provided"} />{resource.resource_url ? <Info label="External resource" value={resource.resource_url} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.edit, working && styles.disabled]} disabled={working} onPress={() => navigation.navigate("EditResource", { resourceId })}><Text style={styles.editText}>Edit Resource</Text></TouchableOpacity>{resource.status === "draft" ? <TouchableOpacity style={[styles.publish, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Publish resource?", "Students and graduates will be able to access this resource.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void publish() }])}><Text style={styles.publishText}>{working ? "Saving…" : "Publish"}</Text></TouchableOpacity> : null}<TouchableOpacity style={[styles.remove, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Delete resource?", `Delete “${resource.title}”? This cannot be undone.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void remove() }])}><Text style={styles.removeText}>Delete Resource</Text></TouchableOpacity></ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { const isDescription = label === "Description"; return <View style={[styles.info, isDescription && styles.readingCard]}><Text style={styles.label}>{label}</Text><Text style={[styles.value, isDescription && styles.readingValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},hero:{...ui.card,paddingVertical:spacing.xl,marginBottom:spacing.md,borderColor:colors.primary},eyebrow:{color:colors.primary,fontSize:12,fontWeight:"800",letterSpacing:1.1,marginBottom:spacing.sm},title:{...typography.screenTitle,fontSize:28,lineHeight:35},badges:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.lg},type:{color:colors.primary,fontWeight:"700",backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},status:{color:colors.success,fontWeight:"700",textTransform:"capitalize",backgroundColor:colors.surfaceRaised,borderRadius:radius.pill,paddingHorizontal:spacing.md,paddingVertical:spacing.xs},info:{...ui.card,marginTop:spacing.md},readingCard:{backgroundColor:colors.backgroundElevated,paddingVertical:spacing.xl},label:{color:colors.text,fontSize:14,fontWeight:"800",letterSpacing:.2},value:{...typography.body,color:colors.textMuted,lineHeight:22,marginTop:spacing.sm},readingValue:{color:colors.text,lineHeight:25},edit:{...ui.outlineButton,marginTop:spacing.xl},editText:ui.outlineButtonText,publish:{...ui.primaryButton,marginTop:spacing.sm},publishText:ui.primaryButtonText,remove:{...ui.outlineButton,marginTop:spacing.sm,borderColor:colors.error},removeText:{...ui.outlineButtonText,color:colors.error},disabled:ui.disabled,error:{color:colors.error,textAlign:"center",lineHeight:21,marginTop:spacing.lg} });
