import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { appError, Application, getOpportunityApplications, unauthorized } from "../../services/application.service";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";

const statusStyle = (status: string) => status === "accepted" ? styles.accepted : status === "rejected" ? styles.rejected : status === "shortlisted" ? styles.shortlisted : status === "reviewing" ? styles.reviewing : status === "withdrawn" ? styles.withdrawn : styles.submittedStatus;

export default function FacultyApplicationsScreen() {
  const navigation = useNavigation<any>();
  const route = useRoute<any>();
  const opportunityId = Number(route.params?.opportunityId);
  const [applications, setApplications] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (session?.user.role !== "faculty") { setError("Faculty access is required to view these applications."); return; } setApplications(await getOpportunityApplications(opportunityId)); setError(""); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } finally { setLoading(false); setRefreshing(false); } }, [navigation, opportunityId]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;

  return <ScrollView style={ui.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} colors={[colors.primary]} />}>
    <TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Opportunity</Text></TouchableOpacity>
    <Text style={styles.title}>Applications</Text><Text style={styles.subtitle}>Review applicants for this opportunity and open a profile for full details.</Text>
    {applications.length ? <View style={styles.contextCard}><Text style={styles.contextEyebrow}>APPLICANT REVIEW</Text><Text style={styles.contextTitle}>{applications.length} {applications.length === 1 ? "application" : "applications"} received</Text><Text style={styles.contextDetail}>Select an applicant to review their application and available actions.</Text></View> : null}
    {error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Retry</Text></TouchableOpacity></View> : null}
    {!error && applications.length === 0 ? <View style={styles.emptyState}><Text style={styles.emptyTitle}>No applications yet</Text><Text style={styles.emptyText}>No applications have been submitted yet.</Text></View> : null}
    {applications.map((application) => <TouchableOpacity key={application.id} style={styles.card} onPress={() => navigation.navigate("FacultyApplicationDetails", { application, opportunityId })}><View style={styles.cardHeader}><View style={styles.applicantWrap}><View style={styles.avatar}><Text style={styles.avatarText}>{(application.applicant_name || "Applicant").charAt(0).toUpperCase()}</Text></View><View style={styles.applicantCopy}><Text style={styles.name}>{application.applicant_name || "Applicant"}</Text><Text style={styles.detail}>{application.applicant_email || "Email unavailable"}</Text></View></View><View style={[styles.statusBadge, statusStyle(application.status)]}><Text style={styles.status}>{application.status}</Text></View></View><View style={styles.infoRow}><Text style={styles.infoLabel}>Role</Text><Text style={styles.infoValue}>{application.applicant_role || "Applicant"}</Text></View><View style={styles.infoRow}><Text style={styles.infoLabel}>Resume</Text><Text style={styles.infoValue}>{application.resume_title || "No resume selected"}</Text></View><View style={styles.cardFooter}><Text style={styles.applicationDate}>Submitted {application.submitted_at.slice(0, 10)}</Text><Text style={styles.reviewAction}>Review application</Text></View></TouchableOpacity>)}
  </ScrollView>;
}

const styles = StyleSheet.create({
  center: { ...ui.centered }, content: { padding: spacing.xl, paddingBottom: 48 }, back: { color: colors.primary, fontWeight: "700", marginBottom: spacing.lg }, title: { ...typography.screenTitle }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.xs, marginBottom: spacing.xl },
  contextCard: { ...ui.card, backgroundColor: colors.surfaceRaised, marginBottom: spacing.lg }, contextEyebrow: { color: colors.secondary, fontSize: 11, fontWeight: "800", letterSpacing: 1 }, contextTitle: { ...typography.cardTitle, marginTop: spacing.sm }, contextDetail: { ...typography.caption, marginTop: spacing.sm },
  card: { ...ui.card, marginBottom: spacing.md }, cardHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: spacing.md }, applicantWrap: { flex: 1, flexDirection: "row", alignItems: "center", gap: spacing.md }, avatar: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center", backgroundColor: colors.backgroundElevated, borderWidth: 1, borderColor: colors.primary }, avatarText: { color: colors.primary, fontWeight: "800", fontSize: 17 }, applicantCopy: { flex: 1 }, name: { ...typography.cardTitle, fontSize: 17 }, detail: { ...typography.caption, marginTop: spacing.xs }, statusBadge: { ...ui.badge }, status: { color: colors.text, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, submittedStatus: { backgroundColor: "#183755", borderWidth: 1, borderColor: colors.info }, reviewing: { backgroundColor: "#3D341D", borderWidth: 1, borderColor: colors.warning }, shortlisted: { backgroundColor: "#292750", borderWidth: 1, borderColor: colors.secondary }, accepted: { backgroundColor: "#123D3C", borderWidth: 1, borderColor: colors.success }, rejected: { backgroundColor: "#48232C", borderWidth: 1, borderColor: colors.error }, withdrawn: { backgroundColor: colors.backgroundElevated, borderWidth: 1, borderColor: colors.textMuted },
  infoRow: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md, marginTop: spacing.md }, infoLabel: { color: colors.textMuted, fontSize: 12, fontWeight: "700" }, infoValue: { color: colors.text, fontSize: 13, fontWeight: "600", flex: 1, textAlign: "right" }, cardFooter: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md, paddingTop: spacing.md, marginTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.divider }, applicationDate: { color: colors.textMuted, fontSize: 12, fontWeight: "700" }, reviewAction: { color: colors.primary, fontSize: 13, fontWeight: "800" },
  emptyState: { ...ui.emptyState, ...ui.card, marginTop: spacing.lg }, emptyTitle: { ...typography.cardTitle, marginBottom: spacing.xs }, emptyText: { ...typography.caption, textAlign: "center" }, errorBox: { ...ui.errorState, ...ui.card, marginTop: spacing.lg }, error: { color: colors.error, textAlign: "center", marginBottom: spacing.sm }, retry: { color: colors.primary, fontWeight: "800" },
});
