import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { closeOpportunity, deleteOpportunity, getOpportunity, getOpportunityErrorMessage, Opportunity, publishOpportunity } from "../../services/opportunity.service";

const labels: Record<Opportunity["opportunity_type"], string> = { internship: "Internship", job: "Job", ra: "Research Assistant (RA)", ta: "Teaching Assistant (TA)", research: "Research" };
export default function FacultyOpportunityDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const [opportunity, setOpportunity] = useState<Opportunity | null>(null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { setOpportunity(await getOpportunity(opportunityId)); setError(""); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); } }, [opportunityId]);
  useEffect(() => { load(); const unsubscribe = navigation.addListener("focus", () => load()); return unsubscribe; }, [load, navigation]);
  const action = async (kind: "publish" | "close" | "delete") => { try { setWorking(true); setError(""); if (kind === "publish") { await publishOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity published" }); await load(); } else if (kind === "close") { await closeOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity closed" }); await load(); } else { await deleteOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity deleted" }); navigation.goBack(); } } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); } finally { setWorking(false); } };
  if (!opportunity) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color={colors.primary} />}</View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Opportunities</Text></TouchableOpacity><View style={styles.hero}><Text style={styles.eyebrow}>FACULTY OPPORTUNITY</Text><Text style={styles.title}>{opportunity.title}</Text><View style={styles.badges}><Text style={styles.type}>{labels[opportunity.opportunity_type]}</Text><Text style={styles.status}>{opportunity.status}</Text></View></View><Info label="Description" value={opportunity.description} /><Info label="Deadline" value={opportunity.deadline.slice(0, 10)} /><Info label="Location" value={opportunity.location || "Not provided"} /><Info label="Work style" value={opportunity.is_remote ? "Remote" : "On-site"} />{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.skills} disabled={working} onPress={() => navigation.navigate("OpportunitySkills", { opportunityId })}><Text style={styles.skillsText}>Manage Required Skills</Text></TouchableOpacity>{opportunity.status !== "closed" ? <TouchableOpacity style={styles.edit} disabled={working} onPress={() => navigation.navigate("EditOpportunity", { opportunityId })}><Text style={styles.editText}>Edit Opportunity</Text></TouchableOpacity> : null}{opportunity.status === "draft" ? <TouchableOpacity style={styles.primary} disabled={working} onPress={() => Alert.alert("Publish opportunity?", "Students will be able to browse and apply.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void action("publish") }])}><Text style={styles.primaryText}>{working ? "Publishing…" : "Publish"}</Text></TouchableOpacity> : null}{opportunity.status === "published" ? <TouchableOpacity style={styles.close} disabled={working} onPress={() => Alert.alert("Close opportunity?", "It will no longer accept applications.", [{ text: "Cancel", style: "cancel" }, { text: "Close", style: "destructive", onPress: () => void action("close") }])}><Text style={styles.closeText}>{working ? "Closing…" : "Close Opportunity"}</Text></TouchableOpacity> : null}<TouchableOpacity style={styles.applications} disabled={working} onPress={() => navigation.navigate("FacultyApplications", { opportunityId })}><Text style={styles.applicationsText}>View Applications</Text></TouchableOpacity>{opportunity.status === "draft" ? <TouchableOpacity style={styles.delete} disabled={working} onPress={() => Alert.alert("Delete draft?", "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void action("delete") }])}><Text style={styles.deleteText}>Delete Draft</Text></TouchableOpacity> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { const isDescription = label === "Description"; return <View style={[styles.info, isDescription && styles.readingCard]}><Text style={styles.label}>{label}</Text><Text style={[styles.value, isDescription && styles.readingValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ center: ui.centered, page: ui.screen, content: ui.screenContent, back: { ...ui.textButton, marginBottom: spacing.lg }, hero: { ...ui.card, paddingVertical: spacing.xl, marginBottom: spacing.md, borderColor: colors.primary }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: "800", letterSpacing: 1.1, marginBottom: spacing.sm }, title: { ...typography.screenTitle, fontSize: 28, lineHeight: 35 }, badges: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.lg }, type: { color: colors.primary, fontWeight: "700", backgroundColor: colors.input, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.xs }, status: { color: colors.success, fontWeight: "700", textTransform: "capitalize", backgroundColor: colors.surfaceRaised, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.xs }, info: { ...ui.card, marginTop: spacing.md }, readingCard: { backgroundColor: colors.backgroundElevated, paddingVertical: spacing.xl }, label: { color: colors.text, fontSize: 14, fontWeight: "800", letterSpacing: .2 }, value: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, lineHeight: 22 }, readingValue: { color: colors.text, lineHeight: 25 }, primary: { ...ui.primaryButton, marginTop: spacing.lg }, primaryText: ui.primaryButtonText, edit: { ...ui.outlineButton, marginTop: spacing.sm }, editText: ui.outlineButtonText, skills: { ...ui.outlineButton, marginTop: spacing.xl, borderColor: colors.secondary }, skillsText: { ...ui.outlineButtonText, color: colors.secondary }, close: { ...ui.outlineButton, marginTop: spacing.sm, borderColor: colors.warning }, closeText: { ...ui.outlineButtonText, color: colors.warning }, applications: { ...ui.outlineButton, marginTop: spacing.sm, borderColor: colors.secondary }, applicationsText: { ...ui.outlineButtonText, color: colors.secondary }, delete: { ...ui.outlineButton, marginTop: spacing.sm, borderColor: colors.error }, deleteText: { ...ui.outlineButtonText, color: colors.error }, error: { color: colors.error, textAlign: "center", marginTop: spacing.lg } });
