import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { appError, Application, getOpportunityApplications, unauthorized } from "../../services/application.service";

export default function FacultyApplicationsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId);
  const [applications, setApplications] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (session?.user.role !== "faculty") { setError("Faculty access is required to view these applications."); return; } setApplications(await getOpportunityApplications(opportunityId)); setError(""); } catch (requestError) { setError(appError(requestError)); if (unauthorized(requestError)) { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); } } finally { setLoading(false); setRefreshing(false); } }, [navigation, opportunityId]);
  useEffect(() => { load(); }, [load]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Opportunity</Text></TouchableOpacity><Text style={styles.title}>Applications</Text>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => load()}><Text style={styles.back}>Retry</Text></TouchableOpacity></View> : null}{!error && applications.length === 0 ? <Text style={styles.empty}>No applications have been submitted yet.</Text> : null}{applications.map((application) => <TouchableOpacity key={application.id} style={styles.card} onPress={() => navigation.navigate("FacultyApplicationDetails", { application, opportunityId })}><Text style={styles.name}>{application.applicant_name || "Applicant"}</Text><Text style={styles.detail}>{application.applicant_email || "Email unavailable"}</Text><Text style={styles.detail}>Role: {application.applicant_role || "Applicant"}</Text><Text style={styles.status}>{application.status}</Text><Text style={styles.detail}>Submitted: {application.submitted_at.slice(0, 10)}</Text><Text style={styles.detail}>Resume: {application.resume_title || "No resume selected"}</Text></TouchableOpacity>)}</ScrollView>;
}
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 30, fontWeight: "bold", color: "#1E3A8A", marginBottom: 18 }, empty: { color: "#666", textAlign: "center", marginTop: 24, fontSize: 16 }, errorBox: { alignItems: "center", marginVertical: 16 }, error: { color: "#DC2626", textAlign: "center", marginBottom: 10 }, card: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 10, padding: 16, marginBottom: 12 }, name: { fontSize: 18, fontWeight: "700", color: "#333" }, detail: { color: "#4B5563", marginTop: 6 }, status: { color: "#2563EB", fontWeight: "700", textTransform: "capitalize", marginTop: 8 } });
