import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { clearAuthSession, getStoredAuthSession } from "../../services/authservice";
import { colors, radius, spacing, typography, ui } from "../../theme/CampusXTheme";
import { Announcement, getAnnouncementErrorMessage, getAnnouncements, isUnauthorizedAnnouncementError } from "../../services/announcement.service";

const label = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);
export default function FacultyAnnouncementsScreen() {
  const navigation = useNavigation<any>(); const [items, setItems] = useState<Announcement[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const resetForUnauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); try { const session = await getStoredAuthSession(); if (!session || session.user.role !== "faculty") { if (!session) await resetForUnauthorized(); else setError("Faculty access is required to manage announcements."); return; } setItems(await getAnnouncements()); setError(""); } catch (requestError) { setError(getAnnouncementErrorMessage(requestError)); if (isUnauthorizedAnnouncementError(requestError)) await resetForUnauthorized(); } finally { setLoading(false); setRefreshing(false); } }, [resetForUnauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} />}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Home</Text></TouchableOpacity><Text style={styles.title}>Academic Announcements</Text><Text style={styles.subtitle}>Create and manage updates for students and graduates.</Text><TouchableOpacity style={styles.create} onPress={() => navigation.navigate("CreateAnnouncement")}><Text style={styles.createText}>Create Announcement</Text></TouchableOpacity>{error ? <View style={styles.errorBox}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity></View> : null}{!error && items.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No announcements yet</Text><Text style={styles.emptyText}>Create a draft announcement when you are ready.</Text></View> : null}{items.map((item) => <TouchableOpacity key={item.id} style={styles.card} onPress={() => navigation.navigate("FacultyAnnouncementDetails", { announcementId: item.id })}><Text style={styles.cardTitle}>{item.title}</Text><View style={styles.cardMeta}><Text style={styles.type}>{label(item.announcement_type)} · {label(item.audience)}</Text><Text style={styles.status}>{label(item.status)}{item.published_at ? ` · ${item.published_at.slice(0, 10)}` : ""}</Text></View><Text style={styles.preview} numberOfLines={2}>{item.content}</Text></TouchableOpacity>)}</ScrollView>;
}
const styles = StyleSheet.create({ center:ui.centered,page:ui.screen,content:ui.screenContent,back:{...ui.textButton,marginBottom:spacing.lg},title:typography.screenTitle,subtitle:{...typography.caption,fontSize:16,lineHeight:22,marginTop:spacing.xs,marginBottom:spacing.lg},create:{...ui.primaryButton,marginBottom:spacing.lg},createText:ui.primaryButtonText,errorBox:{...ui.errorState,...ui.card,marginVertical:spacing.md},error:{color:colors.error,textAlign:"center",marginBottom:spacing.sm},empty:{...ui.emptyState,...ui.card},emptyTitle:typography.cardTitle,emptyText:typography.caption,card:{...ui.card,marginTop:spacing.md},cardTitle:typography.cardTitle,cardMeta:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,marginTop:spacing.sm},type:{color:colors.primary,fontWeight:"700",backgroundColor:colors.input,borderRadius:radius.pill,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},status:{color:colors.success,fontWeight:"700",backgroundColor:colors.surfaceRaised,borderRadius:radius.pill,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},preview:{...typography.body,color:colors.textMuted,marginTop:spacing.md,lineHeight:21} });
