import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { closeOpportunity, deleteOpportunity, getOpportunity, getOpportunityErrorMessage, Opportunity, publishOpportunity } from "../../services/opportunity.service";

const labels: Record<Opportunity["opportunity_type"], string> = { internship: "Internship", job: "Job", ra: "Research Assistant (RA)", ta: "Teaching Assistant (TA)", research: "Research" };
export default function FacultyOpportunityDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const opportunityId = Number(route.params?.opportunityId); const [opportunity, setOpportunity] = useState<Opportunity | null>(null); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const load = useCallback(async () => { try { setOpportunity(await getOpportunity(opportunityId)); setError(""); } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); } }, [opportunityId]);
  useEffect(() => { load(); const unsubscribe = navigation.addListener("focus", () => load()); return unsubscribe; }, [load, navigation]);
  const action = async (kind: "publish" | "close" | "delete") => { try { setWorking(true); setError(""); if (kind === "publish") { await publishOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity published" }); await load(); } else if (kind === "close") { await closeOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity closed" }); await load(); } else { await deleteOpportunity(opportunityId); Toast.show({ type: "success", text1: "Opportunity deleted" }); navigation.goBack(); } } catch (requestError) { setError(getOpportunityErrorMessage(requestError)); } finally { setWorking(false); } };
  if (!opportunity) return <View style={styles.center}>{error ? <><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load}><Text style={styles.back}>Retry</Text></TouchableOpacity></> : <ActivityIndicator size="large" color="#2563EB" />}</View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Opportunities</Text></TouchableOpacity><Text style={styles.title}>{opportunity.title}</Text><Text style={styles.type}>{labels[opportunity.opportunity_type]}</Text><Text style={styles.status}>{opportunity.status}</Text><Info label="Description" value={opportunity.description} /><Info label="Deadline" value={opportunity.deadline.slice(0, 10)} /><Info label="Location" value={opportunity.location || "Not provided"} /><Info label="Work style" value={opportunity.is_remote ? "Remote" : "On-site"} />{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.skills} disabled={working} onPress={() => navigation.navigate("OpportunitySkills", { opportunityId })}><Text style={styles.skillsText}>Manage Required Skills</Text></TouchableOpacity>{opportunity.status !== "closed" ? <TouchableOpacity style={styles.edit} disabled={working} onPress={() => navigation.navigate("EditOpportunity", { opportunityId })}><Text style={styles.editText}>Edit Opportunity</Text></TouchableOpacity> : null}{opportunity.status === "draft" ? <TouchableOpacity style={styles.primary} disabled={working} onPress={() => Alert.alert("Publish opportunity?", "Students will be able to browse and apply.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void action("publish") }])}><Text style={styles.primaryText}>{working ? "Publishing…" : "Publish"}</Text></TouchableOpacity> : null}{opportunity.status === "published" ? <TouchableOpacity style={styles.close} disabled={working} onPress={() => Alert.alert("Close opportunity?", "It will no longer accept applications.", [{ text: "Cancel", style: "cancel" }, { text: "Close", style: "destructive", onPress: () => void action("close") }])}><Text style={styles.closeText}>{working ? "Closing…" : "Close Opportunity"}</Text></TouchableOpacity> : null}<TouchableOpacity style={styles.applications} disabled={working} onPress={() => navigation.navigate("FacultyApplications", { opportunityId })}><Text style={styles.applicationsText}>View Applications</Text></TouchableOpacity>{opportunity.status === "draft" ? <TouchableOpacity style={styles.delete} disabled={working} onPress={() => Alert.alert("Delete draft?", "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void action("delete") }])}><Text style={styles.deleteText}>Delete Draft</Text></TouchableOpacity> : null}</ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24 }, page: { flex: 1, backgroundColor: "#fff" }, content: { padding: 24, paddingBottom: 48 }, back: { color: "#2563EB", fontWeight: "600", marginBottom: 16 }, title: { fontSize: 28, fontWeight: "bold", color: "#1E3A8A" }, type: { color: "#2563EB", fontWeight: "600", marginTop: 8 }, status: { color: "#047857", fontWeight: "700", textTransform: "capitalize", marginTop: 6 }, info: { marginTop: 20 }, label: { color: "#333", fontWeight: "700" }, value: { color: "#4B5563", marginTop: 5, lineHeight: 22 }, primary: { backgroundColor: "#10B981", padding: 14, borderRadius: 10, alignItems: "center", marginTop: 18 }, primaryText: { color: "#fff", fontWeight: "700" }, edit: { borderWidth: 1, borderColor: "#2563EB", padding: 14, borderRadius: 10, alignItems: "center", marginTop: 12 }, editText: { color: "#2563EB", fontWeight: "700" }, skills: { borderWidth: 1, borderColor: "#7C3AED", padding: 14, borderRadius: 10, alignItems: "center", marginTop: 28 }, skillsText: { color: "#6D28D9", fontWeight: "700" }, close: { borderWidth: 1, borderColor: "#EA580C", padding: 14, borderRadius: 10, alignItems: "center", marginTop: 12 }, closeText: { color: "#C2410C", fontWeight: "700" }, applications: { borderWidth: 1, borderColor: "#7C3AED", padding: 14, borderRadius: 10, alignItems: "center", marginTop: 12 }, applicationsText: { color: "#6D28D9", fontWeight: "700" }, delete: { borderWidth: 1, borderColor: "#DC2626", padding: 14, borderRadius: 10, alignItems: "center", marginTop: 12 }, deleteText: { color: "#DC2626", fontWeight: "700" }, error: { color: "#DC2626", textAlign: "center", marginTop: 18 } });
