import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useNavigation, useRoute } from "@react-navigation/native";
import Toast from "react-native-toast-message";
import { clearAuthSession } from "../../services/authservice";
import { AcademicResource, deleteResource, getAcademicResourceErrorMessage, getResource, isUnauthorizedAcademicResourceError, updateResource } from "../../services/academic-resource.service";

const typeLabels: Record<AcademicResource["resource_type"], string> = { lecture_notes: "Lecture Notes", slides: "Slides", lab_manual: "Lab Manual", previous_questions: "Previous Questions", research_material: "Research Material", other: "Other" };

export default function FacultyResourceDetailsScreen() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const resourceId = Number(route.params?.resourceId);
  const [resource, setResource] = useState<AcademicResource | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const unauthorized = useCallback(async () => { await clearAuthSession(); navigation.reset({ index: 0, routes: [{ name: "Welcome" }] }); }, [navigation]);
  const load = useCallback(async () => { if (!Number.isInteger(resourceId) || resourceId < 1) { setError("The resource could not be found."); setLoading(false); return; } try { setLoading(true); setResource(await getResource(resourceId)); setError(""); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setLoading(false); } }, [resourceId, unauthorized]);
  useEffect(() => { void load(); const unsubscribe = navigation.addListener("focus", () => void load()); return unsubscribe; }, [load, navigation]);
  const publish = async () => { try { setWorking(true); setError(""); await updateResource(resourceId, { status: "published" }); await load(); Toast.show({ type: "success", text1: "Resource published" }); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setWorking(false); } };
  const remove = async () => { try { setWorking(true); setError(""); await deleteResource(resourceId); Toast.show({ type: "success", text1: "Resource deleted" }); navigation.goBack(); } catch (requestError) { setError(getAcademicResourceErrorMessage(requestError)); if (isUnauthorizedAcademicResourceError(requestError)) await unauthorized(); } finally { setWorking(false); } };
  if (loading && !resource) return <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>;
  if (!resource) return <View style={styles.center}><Text style={styles.error}>{error || "Resource not found."}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.back}>Retry</Text></TouchableOpacity><TouchableOpacity onPress={() => navigation.goBack()}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity></View>;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => navigation.goBack()} disabled={working}><Text style={styles.back}>Back to Resources</Text></TouchableOpacity><Text style={styles.title}>{resource.title}</Text><Text style={styles.type}>{typeLabels[resource.resource_type]}</Text><Text style={styles.status}>{resource.status}</Text><Info label="Subject" value={resource.subject || "Not provided"} /><Info label="Description" value={resource.description || "Not provided"} />{resource.resource_url ? <Info label="External resource" value={resource.resource_url} /> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={[styles.edit, working && styles.disabled]} disabled={working} onPress={() => navigation.navigate("EditResource", { resourceId })}><Text style={styles.editText}>Edit Resource</Text></TouchableOpacity>{resource.status === "draft" ? <TouchableOpacity style={[styles.publish, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Publish resource?", "Students and graduates will be able to access this resource.", [{ text: "Cancel", style: "cancel" }, { text: "Publish", onPress: () => void publish() }])}><Text style={styles.publishText}>{working ? "Saving…" : "Publish"}</Text></TouchableOpacity> : null}<TouchableOpacity style={[styles.remove, working && styles.disabled]} disabled={working} onPress={() => Alert.alert("Delete resource?", `Delete “${resource.title}”? This cannot be undone.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void remove() }])}><Text style={styles.removeText}>Delete Resource</Text></TouchableOpacity></ScrollView>;
}
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ center:{flex:1,justifyContent:"center",alignItems:"center",padding:24},page:{flex:1,backgroundColor:"#fff"},content:{padding:24,paddingBottom:48},back:{color:"#2563EB",fontWeight:"600",marginBottom:16},title:{fontSize:28,fontWeight:"bold",color:"#1E3A8A"},type:{color:"#2563EB",fontWeight:"600",marginTop:7},status:{color:"#047857",fontWeight:"700",textTransform:"capitalize",marginTop:6},info:{marginTop:20},label:{color:"#333",fontWeight:"700"},value:{color:"#4B5563",lineHeight:22,marginTop:5},edit:{borderWidth:1,borderColor:"#2563EB",borderRadius:10,padding:14,alignItems:"center",marginTop:28},editText:{color:"#2563EB",fontWeight:"700"},publish:{backgroundColor:"#10B981",borderRadius:10,padding:14,alignItems:"center",marginTop:12},publishText:{color:"#fff",fontWeight:"700"},remove:{borderWidth:1,borderColor:"#DC2626",borderRadius:10,padding:14,alignItems:"center",marginTop:12},removeText:{color:"#DC2626",fontWeight:"700"},disabled:{opacity:.6},error:{color:"#DC2626",textAlign:"center",lineHeight:21,marginTop:18} });
