import { StyleSheet } from "react-native";

export const colors = {
  background: "#171022",
  backgroundElevated: "#1D1528",
  surface: "#24172F",
  surfaceRaised: "#33213D",
  input: "#2B1C35",
  primary: "#C99AF5",
  primaryPressed: "#B98AEF",
  secondary: "#F29BEA",
  accent: "#D84EDB",
  accentSoft: "#40284B",
  text: "#FFF8FF",
  textMuted: "#C9BFD0",
  border: "#5A3D68",
  divider: "#40284B",
  success: "#7DD6AF",
  warning: "#F2C879",
  error: "#F28CA5",
  info: "#D8B4FA",
  onPrimary: "#21172A",
  onDark: "#FFF8FF",
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
} as const;

export const radius = {
  sm: 10,
  md: 14,
  lg: 20,
  pill: 999,
} as const;

export const typography = {
  screenTitle: { fontSize: 30, fontWeight: "700" as const, lineHeight: 38, color: colors.text },
  sectionTitle: { fontSize: 21, fontWeight: "700" as const, lineHeight: 28, color: colors.text },
  cardTitle: { fontSize: 18, fontWeight: "700" as const, lineHeight: 24, color: colors.text },
  body: { fontSize: 16, lineHeight: 23, color: colors.text },
  caption: { fontSize: 14, lineHeight: 20, color: colors.textMuted },
  button: { fontSize: 16, fontWeight: "700" as const, lineHeight: 21 },
  input: { fontSize: 16, color: colors.text },
} as const;

export const ui = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  screenContent: { padding: spacing.xl, paddingBottom: spacing.xxl },
  centered: { flex: 1, justifyContent: "center", alignItems: "center", padding: spacing.xl },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing.lg,
    elevation: 4,
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
  },
  input: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: 14,
    color: colors.text,
  },
  primaryButton: {
    minHeight: 52,
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
    elevation: 3,
    shadowColor: colors.secondary,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  secondaryButton: {
    minHeight: 52,
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.secondary,
    borderRadius: radius.pill,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
  },
  outlineButton: {
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.pill,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
  },
  textButton: { color: colors.primary, ...typography.button },
  primaryButtonText: { color: colors.onPrimary, ...typography.button },
  secondaryButtonText: { color: colors.primary, ...typography.button },
  outlineButtonText: { color: colors.primary, ...typography.button },
  disabled: { opacity: 0.55 },
  badge: { alignSelf: "flex-start", borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  progressTrack: { height: 8, overflow: "hidden", borderRadius: radius.pill, backgroundColor: colors.divider },
  progressFill: { height: "100%", borderRadius: radius.pill, backgroundColor: colors.secondary },
  emptyState: { alignItems: "center", paddingVertical: spacing.xxl, paddingHorizontal: spacing.xl },
  errorState: { alignItems: "center", padding: spacing.lg },
});

export const navigationColors = {
  primary: colors.primary,
  background: colors.background,
  card: colors.backgroundElevated,
  text: colors.text,
  border: colors.border,
  notification: colors.error,
};
